/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the active_conservation_projects service. Represents a row in the &quot;whp_active_conservation_projects&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.active_conservation_projectsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.active_conservation_projectsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see active_conservation_projects
 * @see com.iucn.whp.dbservice.model.impl.active_conservation_projectsImpl
 * @see com.iucn.whp.dbservice.model.impl.active_conservation_projectsModelImpl
 * @generated
 */
public interface active_conservation_projectsModel extends BaseModel<active_conservation_projects> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a active_conservation_projects model instance should use the {@link active_conservation_projects} interface instead.
	 */

	/**
	 * Returns the primary key of this active_conservation_projects.
	 *
	 * @return the primary key of this active_conservation_projects
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this active_conservation_projects.
	 *
	 * @param primaryKey the primary key of this active_conservation_projects
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the acpid of this active_conservation_projects.
	 *
	 * @return the acpid of this active_conservation_projects
	 */
	public long getAcpid();

	/**
	 * Sets the acpid of this active_conservation_projects.
	 *
	 * @param acpid the acpid of this active_conservation_projects
	 */
	public void setAcpid(long acpid);

	/**
	 * Returns the assessment_version_id of this active_conservation_projects.
	 *
	 * @return the assessment_version_id of this active_conservation_projects
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this active_conservation_projects.
	 *
	 * @param assessment_version_id the assessment_version_id of this active_conservation_projects
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the organization_individual of this active_conservation_projects.
	 *
	 * @return the organization_individual of this active_conservation_projects
	 */
	@AutoEscape
	public String getOrganization_individual();

	/**
	 * Sets the organization_individual of this active_conservation_projects.
	 *
	 * @param organization_individual the organization_individual of this active_conservation_projects
	 */
	public void setOrganization_individual(String organization_individual);

	/**
	 * Returns the description of this active_conservation_projects.
	 *
	 * @return the description of this active_conservation_projects
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this active_conservation_projects.
	 *
	 * @param description the description of this active_conservation_projects
	 */
	public void setDescription(String description);

	/**
	 * Returns the contact_details of this active_conservation_projects.
	 *
	 * @return the contact_details of this active_conservation_projects
	 */
	@AutoEscape
	public String getContact_details();

	/**
	 * Sets the contact_details of this active_conservation_projects.
	 *
	 * @param contact_details the contact_details of this active_conservation_projects
	 */
	public void setContact_details(String contact_details);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		active_conservation_projects active_conservation_projects);

	public int hashCode();

	public CacheModel<active_conservation_projects> toCacheModel();

	public active_conservation_projects toEscapedModel();

	public String toString();

	public String toXmlString();
}