/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the assessment_whvalues_whcriterion service. Represents a row in the &quot;whp_assessment_whvalues_whcriterion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.assessment_whvalues_whcriterionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.assessment_whvalues_whcriterionImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_whvalues_whcriterion
 * @see com.iucn.whp.dbservice.model.impl.assessment_whvalues_whcriterionImpl
 * @see com.iucn.whp.dbservice.model.impl.assessment_whvalues_whcriterionModelImpl
 * @generated
 */
public interface assessment_whvalues_whcriterionModel extends BaseModel<assessment_whvalues_whcriterion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assessment_whvalues_whcriterion model instance should use the {@link assessment_whvalues_whcriterion} interface instead.
	 */

	/**
	 * Returns the primary key of this assessment_whvalues_whcriterion.
	 *
	 * @return the primary key of this assessment_whvalues_whcriterion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assessment_whvalues_whcriterion.
	 *
	 * @param primaryKey the primary key of this assessment_whvalues_whcriterion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wh_criteria_id of this assessment_whvalues_whcriterion.
	 *
	 * @return the wh_criteria_id of this assessment_whvalues_whcriterion
	 */
	public long getWh_criteria_id();

	/**
	 * Sets the wh_criteria_id of this assessment_whvalues_whcriterion.
	 *
	 * @param wh_criteria_id the wh_criteria_id of this assessment_whvalues_whcriterion
	 */
	public void setWh_criteria_id(long wh_criteria_id);

	/**
	 * Returns the whvalues_id of this assessment_whvalues_whcriterion.
	 *
	 * @return the whvalues_id of this assessment_whvalues_whcriterion
	 */
	public long getWhvalues_id();

	/**
	 * Sets the whvalues_id of this assessment_whvalues_whcriterion.
	 *
	 * @param whvalues_id the whvalues_id of this assessment_whvalues_whcriterion
	 */
	public void setWhvalues_id(long whvalues_id);

	/**
	 * Returns the criterion of this assessment_whvalues_whcriterion.
	 *
	 * @return the criterion of this assessment_whvalues_whcriterion
	 */
	public long getCriterion();

	/**
	 * Sets the criterion of this assessment_whvalues_whcriterion.
	 *
	 * @param criterion the criterion of this assessment_whvalues_whcriterion
	 */
	public void setCriterion(long criterion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		assessment_whvalues_whcriterion assessment_whvalues_whcriterion);

	public int hashCode();

	public CacheModel<assessment_whvalues_whcriterion> toCacheModel();

	public assessment_whvalues_whcriterion toEscapedModel();

	public String toString();

	public String toXmlString();
}