/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the assessment_status service. Represents a row in the &quot;whp_assessment_status&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.assessment_statusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.assessment_statusImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_status
 * @see com.iucn.whp.dbservice.model.impl.assessment_statusImpl
 * @see com.iucn.whp.dbservice.model.impl.assessment_statusModelImpl
 * @generated
 */
public interface assessment_statusModel extends BaseModel<assessment_status> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assessment_status model instance should use the {@link assessment_status} interface instead.
	 */

	/**
	 * Returns the primary key of this assessment_status.
	 *
	 * @return the primary key of this assessment_status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assessment_status.
	 *
	 * @param primaryKey the primary key of this assessment_status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the statusid of this assessment_status.
	 *
	 * @return the statusid of this assessment_status
	 */
	public long getStatusid();

	/**
	 * Sets the statusid of this assessment_status.
	 *
	 * @param statusid the statusid of this assessment_status
	 */
	public void setStatusid(long statusid);

	/**
	 * Returns the status of this assessment_status.
	 *
	 * @return the status of this assessment_status
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this assessment_status.
	 *
	 * @param status the status of this assessment_status
	 */
	public void setStatus(String status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(assessment_status assessment_status);

	public int hashCode();

	public CacheModel<assessment_status> toCacheModel();

	public assessment_status toEscapedModel();

	public String toString();

	public String toXmlString();
}