/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the assessment_validation service. Represents a row in the &quot;whp_assessment_validation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.assessment_validationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.assessment_validationImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_validation
 * @see com.iucn.whp.dbservice.model.impl.assessment_validationImpl
 * @see com.iucn.whp.dbservice.model.impl.assessment_validationModelImpl
 * @generated
 */
public interface assessment_validationModel extends BaseModel<assessment_validation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assessment_validation model instance should use the {@link assessment_validation} interface instead.
	 */

	/**
	 * Returns the primary key of this assessment_validation.
	 *
	 * @return the primary key of this assessment_validation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assessment_validation.
	 *
	 * @param primaryKey the primary key of this assessment_validation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the assessment_ver_val_id of this assessment_validation.
	 *
	 * @return the assessment_ver_val_id of this assessment_validation
	 */
	public long getAssessment_ver_val_id();

	/**
	 * Sets the assessment_ver_val_id of this assessment_validation.
	 *
	 * @param assessment_ver_val_id the assessment_ver_val_id of this assessment_validation
	 */
	public void setAssessment_ver_val_id(long assessment_ver_val_id);

	/**
	 * Returns the assessment_version_id of this assessment_validation.
	 *
	 * @return the assessment_version_id of this assessment_validation
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this assessment_validation.
	 *
	 * @param assessment_version_id the assessment_version_id of this assessment_validation
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the assessment_step of this assessment_validation.
	 *
	 * @return the assessment_step of this assessment_validation
	 */
	public long getAssessment_step();

	/**
	 * Sets the assessment_step of this assessment_validation.
	 *
	 * @param assessment_step the assessment_step of this assessment_validation
	 */
	public void setAssessment_step(long assessment_step);

	/**
	 * Returns the validation_complete of this assessment_validation.
	 *
	 * @return the validation_complete of this assessment_validation
	 */
	public boolean getValidation_complete();

	/**
	 * Returns <code>true</code> if this assessment_validation is validation_complete.
	 *
	 * @return <code>true</code> if this assessment_validation is validation_complete; <code>false</code> otherwise
	 */
	public boolean isValidation_complete();

	/**
	 * Sets whether this assessment_validation is validation_complete.
	 *
	 * @param validation_complete the validation_complete of this assessment_validation
	 */
	public void setValidation_complete(boolean validation_complete);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(assessment_validation assessment_validation);

	public int hashCode();

	public CacheModel<assessment_validation> toCacheModel();

	public assessment_validation toEscapedModel();

	public String toString();

	public String toXmlString();
}