/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the assessment_whvalues service. Represents a row in the &quot;whp_assessment_whvalues&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.assessment_whvaluesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.assessment_whvaluesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_whvalues
 * @see com.iucn.whp.dbservice.model.impl.assessment_whvaluesImpl
 * @see com.iucn.whp.dbservice.model.impl.assessment_whvaluesModelImpl
 * @generated
 */
public interface assessment_whvaluesModel extends BaseModel<assessment_whvalues> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assessment_whvalues model instance should use the {@link assessment_whvalues} interface instead.
	 */

	/**
	 * Returns the primary key of this assessment_whvalues.
	 *
	 * @return the primary key of this assessment_whvalues
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assessment_whvalues.
	 *
	 * @param primaryKey the primary key of this assessment_whvalues
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whvalues_id of this assessment_whvalues.
	 *
	 * @return the whvalues_id of this assessment_whvalues
	 */
	public long getWhvalues_id();

	/**
	 * Sets the whvalues_id of this assessment_whvalues.
	 *
	 * @param whvalues_id the whvalues_id of this assessment_whvalues
	 */
	public void setWhvalues_id(long whvalues_id);

	/**
	 * Returns the vn of this assessment_whvalues.
	 *
	 * @return the vn of this assessment_whvalues
	 */
	public long getVn();

	/**
	 * Sets the vn of this assessment_whvalues.
	 *
	 * @param vn the vn of this assessment_whvalues
	 */
	public void setVn(long vn);

	/**
	 * Returns the assessment_version_id of this assessment_whvalues.
	 *
	 * @return the assessment_version_id of this assessment_whvalues
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this assessment_whvalues.
	 *
	 * @param assessment_version_id the assessment_version_id of this assessment_whvalues
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the values of this assessment_whvalues.
	 *
	 * @return the values of this assessment_whvalues
	 */
	@AutoEscape
	public String getValues();

	/**
	 * Sets the values of this assessment_whvalues.
	 *
	 * @param values the values of this assessment_whvalues
	 */
	public void setValues(String values);

	/**
	 * Returns the description of this assessment_whvalues.
	 *
	 * @return the description of this assessment_whvalues
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this assessment_whvalues.
	 *
	 * @param description the description of this assessment_whvalues
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(assessment_whvalues assessment_whvalues);

	public int hashCode();

	public CacheModel<assessment_whvalues> toCacheModel();

	public assessment_whvalues toEscapedModel();

	public String toString();

	public String toXmlString();
}