/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the assessment_lang_lkp service. Represents a row in the &quot;whp_assessment_lang_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.assessment_lang_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.assessment_lang_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_lang_lkp
 * @see com.iucn.whp.dbservice.model.impl.assessment_lang_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.assessment_lang_lkpModelImpl
 * @generated
 */
public interface assessment_lang_lkpModel extends BaseModel<assessment_lang_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assessment_lang_lkp model instance should use the {@link assessment_lang_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this assessment_lang_lkp.
	 *
	 * @return the primary key of this assessment_lang_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assessment_lang_lkp.
	 *
	 * @param primaryKey the primary key of this assessment_lang_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the languageid of this assessment_lang_lkp.
	 *
	 * @return the languageid of this assessment_lang_lkp
	 */
	public long getLanguageid();

	/**
	 * Sets the languageid of this assessment_lang_lkp.
	 *
	 * @param languageid the languageid of this assessment_lang_lkp
	 */
	public void setLanguageid(long languageid);

	/**
	 * Returns the languagecode of this assessment_lang_lkp.
	 *
	 * @return the languagecode of this assessment_lang_lkp
	 */
	@AutoEscape
	public String getLanguagecode();

	/**
	 * Sets the languagecode of this assessment_lang_lkp.
	 *
	 * @param languagecode the languagecode of this assessment_lang_lkp
	 */
	public void setLanguagecode(String languagecode);

	/**
	 * Returns the languagename of this assessment_lang_lkp.
	 *
	 * @return the languagename of this assessment_lang_lkp
	 */
	@AutoEscape
	public String getLanguagename();

	/**
	 * Sets the languagename of this assessment_lang_lkp.
	 *
	 * @param languagename the languagename of this assessment_lang_lkp
	 */
	public void setLanguagename(String languagename);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(assessment_lang_lkp assessment_lang_lkp);

	public int hashCode();

	public CacheModel<assessment_lang_lkp> toCacheModel();

	public assessment_lang_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}