/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the assessment_stages service. Represents a row in the &quot;whp_assessment_stages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.assessment_stagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.assessment_stagesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_stages
 * @see com.iucn.whp.dbservice.model.impl.assessment_stagesImpl
 * @see com.iucn.whp.dbservice.model.impl.assessment_stagesModelImpl
 * @generated
 */
public interface assessment_stagesModel extends BaseModel<assessment_stages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a assessment_stages model instance should use the {@link assessment_stages} interface instead.
	 */

	/**
	 * Returns the primary key of this assessment_stages.
	 *
	 * @return the primary key of this assessment_stages
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this assessment_stages.
	 *
	 * @param primaryKey the primary key of this assessment_stages
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stageid of this assessment_stages.
	 *
	 * @return the stageid of this assessment_stages
	 */
	public long getStageid();

	/**
	 * Sets the stageid of this assessment_stages.
	 *
	 * @param stageid the stageid of this assessment_stages
	 */
	public void setStageid(long stageid);

	/**
	 * Returns the stage of this assessment_stages.
	 *
	 * @return the stage of this assessment_stages
	 */
	@AutoEscape
	public String getStage();

	/**
	 * Sets the stage of this assessment_stages.
	 *
	 * @param stage the stage of this assessment_stages
	 */
	public void setStage(String stage);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(assessment_stages assessment_stages);

	public int hashCode();

	public CacheModel<assessment_stages> toCacheModel();

	public assessment_stages toEscapedModel();

	public String toString();

	public String toXmlString();
}