/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the benefits_summary service. Represents a row in the &quot;whp_benefits_summary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.benefits_summaryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.benefits_summaryImpl}.
 * </p>
 *
 * @author alok.sen
 * @see benefits_summary
 * @see com.iucn.whp.dbservice.model.impl.benefits_summaryImpl
 * @see com.iucn.whp.dbservice.model.impl.benefits_summaryModelImpl
 * @generated
 */
public interface benefits_summaryModel extends BaseModel<benefits_summary> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a benefits_summary model instance should use the {@link benefits_summary} interface instead.
	 */

	/**
	 * Returns the primary key of this benefits_summary.
	 *
	 * @return the primary key of this benefits_summary
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this benefits_summary.
	 *
	 * @param primaryKey the primary key of this benefits_summary
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the benefits_summary_id of this benefits_summary.
	 *
	 * @return the benefits_summary_id of this benefits_summary
	 */
	public long getBenefits_summary_id();

	/**
	 * Sets the benefits_summary_id of this benefits_summary.
	 *
	 * @param benefits_summary_id the benefits_summary_id of this benefits_summary
	 */
	public void setBenefits_summary_id(long benefits_summary_id);

	/**
	 * Returns the assessment_version_id of this benefits_summary.
	 *
	 * @return the assessment_version_id of this benefits_summary
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this benefits_summary.
	 *
	 * @param assessment_version_id the assessment_version_id of this benefits_summary
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the summary of this benefits_summary.
	 *
	 * @return the summary of this benefits_summary
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this benefits_summary.
	 *
	 * @param summary the summary of this benefits_summary
	 */
	public void setSummary(String summary);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(benefits_summary benefits_summary);

	public int hashCode();

	public CacheModel<benefits_summary> toCacheModel();

	public benefits_summary toEscapedModel();

	public String toString();

	public String toXmlString();
}