/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the benefits service. Represents a row in the &quot;whp_benefits&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.benefitsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.benefitsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see benefits
 * @see com.iucn.whp.dbservice.model.impl.benefitsImpl
 * @see com.iucn.whp.dbservice.model.impl.benefitsModelImpl
 * @generated
 */
public interface benefitsModel extends BaseModel<benefits> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a benefits model instance should use the {@link benefits} interface instead.
	 */

	/**
	 * Returns the primary key of this benefits.
	 *
	 * @return the primary key of this benefits
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this benefits.
	 *
	 * @param primaryKey the primary key of this benefits
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the benefits_id of this benefits.
	 *
	 * @return the benefits_id of this benefits
	 */
	public long getBenefits_id();

	/**
	 * Sets the benefits_id of this benefits.
	 *
	 * @param benefits_id the benefits_id of this benefits
	 */
	public void setBenefits_id(long benefits_id);

	/**
	 * Returns the assessment_version_id of this benefits.
	 *
	 * @return the assessment_version_id of this benefits
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this benefits.
	 *
	 * @param assessment_version_id the assessment_version_id of this benefits
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the selected_benefit of this benefits.
	 *
	 * @return the selected_benefit of this benefits
	 */
	public long getSelected_benefit();

	/**
	 * Sets the selected_benefit of this benefits.
	 *
	 * @param selected_benefit the selected_benefit of this benefits
	 */
	public void setSelected_benefit(long selected_benefit);

	/**
	 * Returns the summary of this benefits.
	 *
	 * @return the summary of this benefits
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this benefits.
	 *
	 * @param summary the summary of this benefits
	 */
	public void setSummary(String summary);

	/**
	 * Returns the data_deficient of this benefits.
	 *
	 * @return the data_deficient of this benefits
	 */
	public boolean getData_deficient();

	/**
	 * Returns <code>true</code> if this benefits is data_deficient.
	 *
	 * @return <code>true</code> if this benefits is data_deficient; <code>false</code> otherwise
	 */
	public boolean isData_deficient();

	/**
	 * Sets whether this benefits is data_deficient.
	 *
	 * @param data_deficient the data_deficient of this benefits
	 */
	public void setData_deficient(boolean data_deficient);

	/**
	 * Returns the community_within_site of this benefits.
	 *
	 * @return the community_within_site of this benefits
	 */
	public long getCommunity_within_site();

	/**
	 * Sets the community_within_site of this benefits.
	 *
	 * @param community_within_site the community_within_site of this benefits
	 */
	public void setCommunity_within_site(long community_within_site);

	/**
	 * Returns the community_outside_site of this benefits.
	 *
	 * @return the community_outside_site of this benefits
	 */
	public long getCommunity_outside_site();

	/**
	 * Sets the community_outside_site of this benefits.
	 *
	 * @param community_outside_site the community_outside_site of this benefits
	 */
	public void setCommunity_outside_site(long community_outside_site);

	/**
	 * Returns the wider_community of this benefits.
	 *
	 * @return the wider_community of this benefits
	 */
	public long getWider_community();

	/**
	 * Sets the wider_community of this benefits.
	 *
	 * @param wider_community the wider_community of this benefits
	 */
	public void setWider_community(long wider_community);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(benefits benefits);

	public int hashCode();

	public CacheModel<benefits> toCacheModel();

	public benefits toEscapedModel();

	public String toString();

	public String toXmlString();
}