/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the benefit_checktype_lkp service. Represents a row in the &quot;whp_benefit_checktype_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.benefit_checktype_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.benefit_checktype_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see benefit_checktype_lkp
 * @see com.iucn.whp.dbservice.model.impl.benefit_checktype_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.benefit_checktype_lkpModelImpl
 * @generated
 */
public interface benefit_checktype_lkpModel extends BaseModel<benefit_checktype_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a benefit_checktype_lkp model instance should use the {@link benefit_checktype_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this benefit_checktype_lkp.
	 *
	 * @return the primary key of this benefit_checktype_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this benefit_checktype_lkp.
	 *
	 * @param primaryKey the primary key of this benefit_checktype_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the benefit_id of this benefit_checktype_lkp.
	 *
	 * @return the benefit_id of this benefit_checktype_lkp
	 */
	public long getBenefit_id();

	/**
	 * Sets the benefit_id of this benefit_checktype_lkp.
	 *
	 * @param benefit_id the benefit_id of this benefit_checktype_lkp
	 */
	public void setBenefit_id(long benefit_id);

	/**
	 * Returns the benefit_checktype of this benefit_checktype_lkp.
	 *
	 * @return the benefit_checktype of this benefit_checktype_lkp
	 */
	@AutoEscape
	public String getBenefit_checktype();

	/**
	 * Sets the benefit_checktype of this benefit_checktype_lkp.
	 *
	 * @param benefit_checktype the benefit_checktype of this benefit_checktype_lkp
	 */
	public void setBenefit_checktype(String benefit_checktype);

	/**
	 * Returns the active of this benefit_checktype_lkp.
	 *
	 * @return the active of this benefit_checktype_lkp
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this benefit_checktype_lkp is active.
	 *
	 * @return <code>true</code> if this benefit_checktype_lkp is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this benefit_checktype_lkp is active.
	 *
	 * @param active the active of this benefit_checktype_lkp
	 */
	public void setActive(boolean active);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(benefit_checktype_lkp benefit_checktype_lkp);

	public int hashCode();

	public CacheModel<benefit_checktype_lkp> toCacheModel();

	public benefit_checktype_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}