/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the boundary_modification_type_lkp service. Represents a row in the &quot;whp_boundary_modification_type_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.boundary_modification_type_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.boundary_modification_type_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see boundary_modification_type_lkp
 * @see com.iucn.whp.dbservice.model.impl.boundary_modification_type_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.boundary_modification_type_lkpModelImpl
 * @generated
 */
public interface boundary_modification_type_lkpModel extends BaseModel<boundary_modification_type_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a boundary_modification_type_lkp model instance should use the {@link boundary_modification_type_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this boundary_modification_type_lkp.
	 *
	 * @return the primary key of this boundary_modification_type_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this boundary_modification_type_lkp.
	 *
	 * @param primaryKey the primary key of this boundary_modification_type_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the bm_id of this boundary_modification_type_lkp.
	 *
	 * @return the bm_id of this boundary_modification_type_lkp
	 */
	public int getBm_id();

	/**
	 * Sets the bm_id of this boundary_modification_type_lkp.
	 *
	 * @param bm_id the bm_id of this boundary_modification_type_lkp
	 */
	public void setBm_id(int bm_id);

	/**
	 * Returns the bm_type of this boundary_modification_type_lkp.
	 *
	 * @return the bm_type of this boundary_modification_type_lkp
	 */
	@AutoEscape
	public String getBm_type();

	/**
	 * Sets the bm_type of this boundary_modification_type_lkp.
	 *
	 * @param bm_type the bm_type of this boundary_modification_type_lkp
	 */
	public void setBm_type(String bm_type);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		boundary_modification_type_lkp boundary_modification_type_lkp);

	public int hashCode();

	public CacheModel<boundary_modification_type_lkp> toCacheModel();

	public boundary_modification_type_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}