/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the country_lkp service. Represents a row in the &quot;whp_country_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.country_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.country_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see country_lkp
 * @see com.iucn.whp.dbservice.model.impl.country_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.country_lkpModelImpl
 * @generated
 */
public interface country_lkpModel extends BaseModel<country_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a country_lkp model instance should use the {@link country_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this country_lkp.
	 *
	 * @return the primary key of this country_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this country_lkp.
	 *
	 * @param primaryKey the primary key of this country_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the countryid of this country_lkp.
	 *
	 * @return the countryid of this country_lkp
	 */
	public int getCountryid();

	/**
	 * Sets the countryid of this country_lkp.
	 *
	 * @param countryid the countryid of this country_lkp
	 */
	public void setCountryid(int countryid);

	/**
	 * Returns the name of this country_lkp.
	 *
	 * @return the name of this country_lkp
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this country_lkp.
	 *
	 * @param name the name of this country_lkp
	 */
	public void setName(String name);

	/**
	 * Returns the a2 of this country_lkp.
	 *
	 * @return the a2 of this country_lkp
	 */
	@AutoEscape
	public String getA2();

	/**
	 * Sets the a2 of this country_lkp.
	 *
	 * @param a2 the a2 of this country_lkp
	 */
	public void setA2(String a2);

	/**
	 * Returns the a3 of this country_lkp.
	 *
	 * @return the a3 of this country_lkp
	 */
	@AutoEscape
	public String getA3();

	/**
	 * Sets the a3 of this country_lkp.
	 *
	 * @param a3 the a3 of this country_lkp
	 */
	public void setA3(String a3);

	/**
	 * Returns the number of this country_lkp.
	 *
	 * @return the number of this country_lkp
	 */
	@AutoEscape
	public String getNumber();

	/**
	 * Sets the number of this country_lkp.
	 *
	 * @param number the number of this country_lkp
	 */
	public void setNumber(String number);

	/**
	 * Returns the idd of this country_lkp.
	 *
	 * @return the idd of this country_lkp
	 */
	@AutoEscape
	public String getIdd();

	/**
	 * Sets the idd of this country_lkp.
	 *
	 * @param idd the idd of this country_lkp
	 */
	public void setIdd(String idd);

	/**
	 * Returns the currency of this country_lkp.
	 *
	 * @return the currency of this country_lkp
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this country_lkp.
	 *
	 * @param currency the currency of this country_lkp
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the ziprequired of this country_lkp.
	 *
	 * @return the ziprequired of this country_lkp
	 */
	public boolean getZiprequired();

	/**
	 * Returns <code>true</code> if this country_lkp is ziprequired.
	 *
	 * @return <code>true</code> if this country_lkp is ziprequired; <code>false</code> otherwise
	 */
	public boolean isZiprequired();

	/**
	 * Sets whether this country_lkp is ziprequired.
	 *
	 * @param ziprequired the ziprequired of this country_lkp
	 */
	public void setZiprequired(boolean ziprequired);

	/**
	 * Returns the active of this country_lkp.
	 *
	 * @return the active of this country_lkp
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this country_lkp is active.
	 *
	 * @return <code>true</code> if this country_lkp is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this country_lkp is active.
	 *
	 * @param active the active of this country_lkp
	 */
	public void setActive(boolean active);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(country_lkp country_lkp);

	public int hashCode();

	public CacheModel<country_lkp> toCacheModel();

	public country_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}