/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the current_state_trend service. Represents a row in the &quot;whp_current_state_trend&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.current_state_trendModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.current_state_trendImpl}.
 * </p>
 *
 * @author alok.sen
 * @see current_state_trend
 * @see com.iucn.whp.dbservice.model.impl.current_state_trendImpl
 * @see com.iucn.whp.dbservice.model.impl.current_state_trendModelImpl
 * @generated
 */
public interface current_state_trendModel extends BaseModel<current_state_trend> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a current_state_trend model instance should use the {@link current_state_trend} interface instead.
	 */

	/**
	 * Returns the primary key of this current_state_trend.
	 *
	 * @return the primary key of this current_state_trend
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this current_state_trend.
	 *
	 * @param primaryKey the primary key of this current_state_trend
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the state_trend_id of this current_state_trend.
	 *
	 * @return the state_trend_id of this current_state_trend
	 */
	public long getState_trend_id();

	/**
	 * Sets the state_trend_id of this current_state_trend.
	 *
	 * @param state_trend_id the state_trend_id of this current_state_trend
	 */
	public void setState_trend_id(long state_trend_id);

	/**
	 * Returns the vn of this current_state_trend.
	 *
	 * @return the vn of this current_state_trend
	 */
	public long getVn();

	/**
	 * Sets the vn of this current_state_trend.
	 *
	 * @param vn the vn of this current_state_trend
	 */
	public void setVn(long vn);

	/**
	 * Returns the assessment_version_id of this current_state_trend.
	 *
	 * @return the assessment_version_id of this current_state_trend
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this current_state_trend.
	 *
	 * @param assessment_version_id the assessment_version_id of this current_state_trend
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the justification of this current_state_trend.
	 *
	 * @return the justification of this current_state_trend
	 */
	@AutoEscape
	public String getJustification();

	/**
	 * Sets the justification of this current_state_trend.
	 *
	 * @param justification the justification of this current_state_trend
	 */
	public void setJustification(String justification);

	/**
	 * Returns the trend_id of this current_state_trend.
	 *
	 * @return the trend_id of this current_state_trend
	 */
	public long getTrend_id();

	/**
	 * Sets the trend_id of this current_state_trend.
	 *
	 * @param trend_id the trend_id of this current_state_trend
	 */
	public void setTrend_id(long trend_id);

	/**
	 * Returns the state_id of this current_state_trend.
	 *
	 * @return the state_id of this current_state_trend
	 */
	public long getState_id();

	/**
	 * Sets the state_id of this current_state_trend.
	 *
	 * @param state_id the state_id of this current_state_trend
	 */
	public void setState_id(long state_id);

	/**
	 * Returns the is_biodiv_whval of this current_state_trend.
	 *
	 * @return the is_biodiv_whval of this current_state_trend
	 */
	public boolean getIs_biodiv_whval();

	/**
	 * Returns <code>true</code> if this current_state_trend is is_biodiv_whval.
	 *
	 * @return <code>true</code> if this current_state_trend is is_biodiv_whval; <code>false</code> otherwise
	 */
	public boolean isIs_biodiv_whval();

	/**
	 * Sets whether this current_state_trend is is_biodiv_whval.
	 *
	 * @param is_biodiv_whval the is_biodiv_whval of this current_state_trend
	 */
	public void setIs_biodiv_whval(boolean is_biodiv_whval);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(current_state_trend current_state_trend);

	public int hashCode();

	public CacheModel<current_state_trend> toCacheModel();

	public current_state_trend toEscapedModel();

	public String toString();

	public String toXmlString();
}