/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the danger_list_status_lkp service. Represents a row in the &quot;whp_danger_list_status_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.danger_list_status_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.danger_list_status_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see danger_list_status_lkp
 * @see com.iucn.whp.dbservice.model.impl.danger_list_status_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.danger_list_status_lkpModelImpl
 * @generated
 */
public interface danger_list_status_lkpModel extends BaseModel<danger_list_status_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a danger_list_status_lkp model instance should use the {@link danger_list_status_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this danger_list_status_lkp.
	 *
	 * @return the primary key of this danger_list_status_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this danger_list_status_lkp.
	 *
	 * @param primaryKey the primary key of this danger_list_status_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the dlstatus_id of this danger_list_status_lkp.
	 *
	 * @return the dlstatus_id of this danger_list_status_lkp
	 */
	public int getDlstatus_id();

	/**
	 * Sets the dlstatus_id of this danger_list_status_lkp.
	 *
	 * @param dlstatus_id the dlstatus_id of this danger_list_status_lkp
	 */
	public void setDlstatus_id(int dlstatus_id);

	/**
	 * Returns the dl_status of this danger_list_status_lkp.
	 *
	 * @return the dl_status of this danger_list_status_lkp
	 */
	@AutoEscape
	public String getDl_status();

	/**
	 * Sets the dl_status of this danger_list_status_lkp.
	 *
	 * @param dl_status the dl_status of this danger_list_status_lkp
	 */
	public void setDl_status(String dl_status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(danger_list_status_lkp danger_list_status_lkp);

	public int hashCode();

	public CacheModel<danger_list_status_lkp> toCacheModel();

	public danger_list_status_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}