/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the effective_prot_mgmt_iothreats service. Represents a row in the &quot;whp_effective_prot_mgmt_iothreats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.effective_prot_mgmt_iothreatsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.effective_prot_mgmt_iothreatsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see effective_prot_mgmt_iothreats
 * @see com.iucn.whp.dbservice.model.impl.effective_prot_mgmt_iothreatsImpl
 * @see com.iucn.whp.dbservice.model.impl.effective_prot_mgmt_iothreatsModelImpl
 * @generated
 */
public interface effective_prot_mgmt_iothreatsModel extends BaseModel<effective_prot_mgmt_iothreats> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a effective_prot_mgmt_iothreats model instance should use the {@link effective_prot_mgmt_iothreats} interface instead.
	 */

	/**
	 * Returns the primary key of this effective_prot_mgmt_iothreats.
	 *
	 * @return the primary key of this effective_prot_mgmt_iothreats
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this effective_prot_mgmt_iothreats.
	 *
	 * @param primaryKey the primary key of this effective_prot_mgmt_iothreats
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this effective_prot_mgmt_iothreats.
	 *
	 * @return the ID of this effective_prot_mgmt_iothreats
	 */
	public long getId();

	/**
	 * Sets the ID of this effective_prot_mgmt_iothreats.
	 *
	 * @param id the ID of this effective_prot_mgmt_iothreats
	 */
	public void setId(long id);

	/**
	 * Returns the assessment_version_id of this effective_prot_mgmt_iothreats.
	 *
	 * @return the assessment_version_id of this effective_prot_mgmt_iothreats
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this effective_prot_mgmt_iothreats.
	 *
	 * @param assessment_version_id the assessment_version_id of this effective_prot_mgmt_iothreats
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the justification of this effective_prot_mgmt_iothreats.
	 *
	 * @return the justification of this effective_prot_mgmt_iothreats
	 */
	@AutoEscape
	public String getJustification();

	/**
	 * Sets the justification of this effective_prot_mgmt_iothreats.
	 *
	 * @param justification the justification of this effective_prot_mgmt_iothreats
	 */
	public void setJustification(String justification);

	/**
	 * Returns the rating of this effective_prot_mgmt_iothreats.
	 *
	 * @return the rating of this effective_prot_mgmt_iothreats
	 */
	public long getRating();

	/**
	 * Sets the rating of this effective_prot_mgmt_iothreats.
	 *
	 * @param rating the rating of this effective_prot_mgmt_iothreats
	 */
	public void setRating(long rating);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		effective_prot_mgmt_iothreats effective_prot_mgmt_iothreats);

	public int hashCode();

	public CacheModel<effective_prot_mgmt_iothreats> toCacheModel();

	public effective_prot_mgmt_iothreats toEscapedModel();

	public String toString();

	public String toXmlString();
}