/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the flagship_species_lkp service. Represents a row in the &quot;whp_flagship_species_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.flagship_species_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.flagship_species_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see flagship_species_lkp
 * @see com.iucn.whp.dbservice.model.impl.flagship_species_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.flagship_species_lkpModelImpl
 * @generated
 */
public interface flagship_species_lkpModel extends BaseModel<flagship_species_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flagship_species_lkp model instance should use the {@link flagship_species_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this flagship_species_lkp.
	 *
	 * @return the primary key of this flagship_species_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this flagship_species_lkp.
	 *
	 * @param primaryKey the primary key of this flagship_species_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the flagship_species_id of this flagship_species_lkp.
	 *
	 * @return the flagship_species_id of this flagship_species_lkp
	 */
	public int getFlagship_species_id();

	/**
	 * Sets the flagship_species_id of this flagship_species_lkp.
	 *
	 * @param flagship_species_id the flagship_species_id of this flagship_species_lkp
	 */
	public void setFlagship_species_id(int flagship_species_id);

	/**
	 * Returns the flagship_species_name of this flagship_species_lkp.
	 *
	 * @return the flagship_species_name of this flagship_species_lkp
	 */
	@AutoEscape
	public String getFlagship_species_name();

	/**
	 * Sets the flagship_species_name of this flagship_species_lkp.
	 *
	 * @param flagship_species_name the flagship_species_name of this flagship_species_lkp
	 */
	public void setFlagship_species_name(String flagship_species_name);

	/**
	 * Returns the redlist_url of this flagship_species_lkp.
	 *
	 * @return the redlist_url of this flagship_species_lkp
	 */
	@AutoEscape
	public String getRedlist_url();

	/**
	 * Sets the redlist_url of this flagship_species_lkp.
	 *
	 * @param redlist_url the redlist_url of this flagship_species_lkp
	 */
	public void setRedlist_url(String redlist_url);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(flagship_species_lkp flagship_species_lkp);

	public int hashCode();

	public CacheModel<flagship_species_lkp> toCacheModel();

	public flagship_species_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}