/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the inscription_type_lkp service. Represents a row in the &quot;whp_inscription_type_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.inscription_type_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.inscription_type_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see inscription_type_lkp
 * @see com.iucn.whp.dbservice.model.impl.inscription_type_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.inscription_type_lkpModelImpl
 * @generated
 */
public interface inscription_type_lkpModel extends BaseModel<inscription_type_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a inscription_type_lkp model instance should use the {@link inscription_type_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this inscription_type_lkp.
	 *
	 * @return the primary key of this inscription_type_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this inscription_type_lkp.
	 *
	 * @param primaryKey the primary key of this inscription_type_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the incription_type_id of this inscription_type_lkp.
	 *
	 * @return the incription_type_id of this inscription_type_lkp
	 */
	public int getIncription_type_id();

	/**
	 * Sets the incription_type_id of this inscription_type_lkp.
	 *
	 * @param incription_type_id the incription_type_id of this inscription_type_lkp
	 */
	public void setIncription_type_id(int incription_type_id);

	/**
	 * Returns the type of this inscription_type_lkp.
	 *
	 * @return the type of this inscription_type_lkp
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this inscription_type_lkp.
	 *
	 * @param type the type of this inscription_type_lkp
	 */
	public void setType(String type);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(inscription_type_lkp inscription_type_lkp);

	public int hashCode();

	public CacheModel<inscription_type_lkp> toCacheModel();

	public inscription_type_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}