/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the inscription_criteria_lkp service. Represents a row in the &quot;whp_inscription_criteria_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.inscription_criteria_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.inscription_criteria_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see inscription_criteria_lkp
 * @see com.iucn.whp.dbservice.model.impl.inscription_criteria_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.inscription_criteria_lkpModelImpl
 * @generated
 */
public interface inscription_criteria_lkpModel extends BaseModel<inscription_criteria_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a inscription_criteria_lkp model instance should use the {@link inscription_criteria_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this inscription_criteria_lkp.
	 *
	 * @return the primary key of this inscription_criteria_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this inscription_criteria_lkp.
	 *
	 * @param primaryKey the primary key of this inscription_criteria_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the criteria_id of this inscription_criteria_lkp.
	 *
	 * @return the criteria_id of this inscription_criteria_lkp
	 */
	public int getCriteria_id();

	/**
	 * Sets the criteria_id of this inscription_criteria_lkp.
	 *
	 * @param criteria_id the criteria_id of this inscription_criteria_lkp
	 */
	public void setCriteria_id(int criteria_id);

	/**
	 * Returns the criteria of this inscription_criteria_lkp.
	 *
	 * @return the criteria of this inscription_criteria_lkp
	 */
	@AutoEscape
	public String getCriteria();

	/**
	 * Sets the criteria of this inscription_criteria_lkp.
	 *
	 * @param criteria the criteria of this inscription_criteria_lkp
	 */
	public void setCriteria(String criteria);

	/**
	 * Returns the criteria_type of this inscription_criteria_lkp.
	 *
	 * @return the criteria_type of this inscription_criteria_lkp
	 */
	@AutoEscape
	public String getCriteria_type();

	/**
	 * Sets the criteria_type of this inscription_criteria_lkp.
	 *
	 * @param criteria_type the criteria_type of this inscription_criteria_lkp
	 */
	public void setCriteria_type(String criteria_type);

	/**
	 * Returns the criteria_desc of this inscription_criteria_lkp.
	 *
	 * @return the criteria_desc of this inscription_criteria_lkp
	 */
	@AutoEscape
	public String getCriteria_desc();

	/**
	 * Sets the criteria_desc of this inscription_criteria_lkp.
	 *
	 * @param criteria_desc the criteria_desc of this inscription_criteria_lkp
	 */
	public void setCriteria_desc(String criteria_desc);

	/**
	 * Returns the criteria_title of this inscription_criteria_lkp.
	 *
	 * @return the criteria_title of this inscription_criteria_lkp
	 */
	@AutoEscape
	public String getCriteria_title();

	/**
	 * Sets the criteria_title of this inscription_criteria_lkp.
	 *
	 * @param criteria_title the criteria_title of this inscription_criteria_lkp
	 */
	public void setCriteria_title(String criteria_title);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(inscription_criteria_lkp inscription_criteria_lkp);

	public int hashCode();

	public CacheModel<inscription_criteria_lkp> toCacheModel();

	public inscription_criteria_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}