/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the iucn_region service. Represents a row in the &quot;whp_iucn_region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.iucn_regionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.iucn_regionImpl}.
 * </p>
 *
 * @author alok.sen
 * @see iucn_region
 * @see com.iucn.whp.dbservice.model.impl.iucn_regionImpl
 * @see com.iucn.whp.dbservice.model.impl.iucn_regionModelImpl
 * @generated
 */
public interface iucn_regionModel extends BaseModel<iucn_region> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a iucn_region model instance should use the {@link iucn_region} interface instead.
	 */

	/**
	 * Returns the primary key of this iucn_region.
	 *
	 * @return the primary key of this iucn_region
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this iucn_region.
	 *
	 * @param primaryKey the primary key of this iucn_region
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the iucn_region_id of this iucn_region.
	 *
	 * @return the iucn_region_id of this iucn_region
	 */
	public int getIucn_region_id();

	/**
	 * Sets the iucn_region_id of this iucn_region.
	 *
	 * @param iucn_region_id the iucn_region_id of this iucn_region
	 */
	public void setIucn_region_id(int iucn_region_id);

	/**
	 * Returns the name of this iucn_region.
	 *
	 * @return the name of this iucn_region
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this iucn_region.
	 *
	 * @param name the name of this iucn_region
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(iucn_region iucn_region);

	public int hashCode();

	public CacheModel<iucn_region> toCacheModel();

	public iucn_region toEscapedModel();

	public String toString();

	public String toXmlString();
}