/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the key_conservation_issues service. Represents a row in the &quot;whp_key_conservation_issues&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.key_conservation_issuesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.key_conservation_issuesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see key_conservation_issues
 * @see com.iucn.whp.dbservice.model.impl.key_conservation_issuesImpl
 * @see com.iucn.whp.dbservice.model.impl.key_conservation_issuesModelImpl
 * @generated
 */
public interface key_conservation_issuesModel extends BaseModel<key_conservation_issues> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a key_conservation_issues model instance should use the {@link key_conservation_issues} interface instead.
	 */

	/**
	 * Returns the primary key of this key_conservation_issues.
	 *
	 * @return the primary key of this key_conservation_issues
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this key_conservation_issues.
	 *
	 * @param primaryKey the primary key of this key_conservation_issues
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the key_conservation_issues_id of this key_conservation_issues.
	 *
	 * @return the key_conservation_issues_id of this key_conservation_issues
	 */
	public long getKey_conservation_issues_id();

	/**
	 * Sets the key_conservation_issues_id of this key_conservation_issues.
	 *
	 * @param key_conservation_issues_id the key_conservation_issues_id of this key_conservation_issues
	 */
	public void setKey_conservation_issues_id(long key_conservation_issues_id);

	/**
	 * Returns the assessment_version_id of this key_conservation_issues.
	 *
	 * @return the assessment_version_id of this key_conservation_issues
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this key_conservation_issues.
	 *
	 * @param assessment_version_id the assessment_version_id of this key_conservation_issues
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the cn of this key_conservation_issues.
	 *
	 * @return the cn of this key_conservation_issues
	 */
	@AutoEscape
	public String getCn();

	/**
	 * Sets the cn of this key_conservation_issues.
	 *
	 * @param cn the cn of this key_conservation_issues
	 */
	public void setCn(String cn);

	/**
	 * Returns the key_conservation_issues of this key_conservation_issues.
	 *
	 * @return the key_conservation_issues of this key_conservation_issues
	 */
	@AutoEscape
	public String getKey_conservation_issues();

	/**
	 * Sets the key_conservation_issues of this key_conservation_issues.
	 *
	 * @param key_conservation_issues the key_conservation_issues of this key_conservation_issues
	 */
	public void setKey_conservation_issues(String key_conservation_issues);

	/**
	 * Returns the description of this key_conservation_issues.
	 *
	 * @return the description of this key_conservation_issues
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this key_conservation_issues.
	 *
	 * @param description the description of this key_conservation_issues
	 */
	public void setDescription(String description);

	/**
	 * Returns the scale of this key_conservation_issues.
	 *
	 * @return the scale of this key_conservation_issues
	 */
	public long getScale();

	/**
	 * Sets the scale of this key_conservation_issues.
	 *
	 * @param scale the scale of this key_conservation_issues
	 */
	public void setScale(long scale);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(key_conservation_issues key_conservation_issues);

	public int hashCode();

	public CacheModel<key_conservation_issues> toCacheModel();

	public key_conservation_issues toEscapedModel();

	public String toString();

	public String toXmlString();
}