/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the mission_lkp service. Represents a row in the &quot;whp_mission_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.mission_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.mission_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see mission_lkp
 * @see com.iucn.whp.dbservice.model.impl.mission_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.mission_lkpModelImpl
 * @generated
 */
public interface mission_lkpModel extends BaseModel<mission_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mission_lkp model instance should use the {@link mission_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this mission_lkp.
	 *
	 * @return the primary key of this mission_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this mission_lkp.
	 *
	 * @param primaryKey the primary key of this mission_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the mission_id of this mission_lkp.
	 *
	 * @return the mission_id of this mission_lkp
	 */
	public int getMission_id();

	/**
	 * Sets the mission_id of this mission_lkp.
	 *
	 * @param mission_id the mission_id of this mission_lkp
	 */
	public void setMission_id(int mission_id);

	/**
	 * Returns the mission_type of this mission_lkp.
	 *
	 * @return the mission_type of this mission_lkp
	 */
	@AutoEscape
	public String getMission_type();

	/**
	 * Sets the mission_type of this mission_lkp.
	 *
	 * @param mission_type the mission_type of this mission_lkp
	 */
	public void setMission_type(String mission_type);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(mission_lkp mission_lkp);

	public int hashCode();

	public CacheModel<mission_lkp> toCacheModel();

	public mission_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}