/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the negative_factors_level_impact service. Represents a row in the &quot;whp_negative_factors_level_impact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.negative_factors_level_impactModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.negative_factors_level_impactImpl}.
 * </p>
 *
 * @author alok.sen
 * @see negative_factors_level_impact
 * @see com.iucn.whp.dbservice.model.impl.negative_factors_level_impactImpl
 * @see com.iucn.whp.dbservice.model.impl.negative_factors_level_impactModelImpl
 * @generated
 */
public interface negative_factors_level_impactModel extends BaseModel<negative_factors_level_impact> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a negative_factors_level_impact model instance should use the {@link negative_factors_level_impact} interface instead.
	 */

	/**
	 * Returns the primary key of this negative_factors_level_impact.
	 *
	 * @return the primary key of this negative_factors_level_impact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this negative_factors_level_impact.
	 *
	 * @param primaryKey the primary key of this negative_factors_level_impact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the level_id of this negative_factors_level_impact.
	 *
	 * @return the level_id of this negative_factors_level_impact
	 */
	public long getLevel_id();

	/**
	 * Sets the level_id of this negative_factors_level_impact.
	 *
	 * @param level_id the level_id of this negative_factors_level_impact
	 */
	public void setLevel_id(long level_id);

	/**
	 * Returns the level_impact of this negative_factors_level_impact.
	 *
	 * @return the level_impact of this negative_factors_level_impact
	 */
	@AutoEscape
	public String getLevel_impact();

	/**
	 * Sets the level_impact of this negative_factors_level_impact.
	 *
	 * @param level_impact the level_impact of this negative_factors_level_impact
	 */
	public void setLevel_impact(String level_impact);

	/**
	 * Returns the description of this negative_factors_level_impact.
	 *
	 * @return the description of this negative_factors_level_impact
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this negative_factors_level_impact.
	 *
	 * @param description the description of this negative_factors_level_impact
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		negative_factors_level_impact negative_factors_level_impact);

	public int hashCode();

	public CacheModel<negative_factors_level_impact> toCacheModel();

	public negative_factors_level_impact toEscapedModel();

	public String toString();

	public String toXmlString();
}