/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the other_designation_lkp service. Represents a row in the &quot;whp_other_designation_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.other_designation_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.other_designation_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see other_designation_lkp
 * @see com.iucn.whp.dbservice.model.impl.other_designation_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.other_designation_lkpModelImpl
 * @generated
 */
public interface other_designation_lkpModel extends BaseModel<other_designation_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a other_designation_lkp model instance should use the {@link other_designation_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this other_designation_lkp.
	 *
	 * @return the primary key of this other_designation_lkp
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this other_designation_lkp.
	 *
	 * @param primaryKey the primary key of this other_designation_lkp
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the other_designations_id of this other_designation_lkp.
	 *
	 * @return the other_designations_id of this other_designation_lkp
	 */
	public int getOther_designations_id();

	/**
	 * Sets the other_designations_id of this other_designation_lkp.
	 *
	 * @param other_designations_id the other_designations_id of this other_designation_lkp
	 */
	public void setOther_designations_id(int other_designations_id);

	/**
	 * Returns the designation of this other_designation_lkp.
	 *
	 * @return the designation of this other_designation_lkp
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this other_designation_lkp.
	 *
	 * @param designation the designation of this other_designation_lkp
	 */
	public void setDesignation(String designation);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(other_designation_lkp other_designation_lkp);

	public int hashCode();

	public CacheModel<other_designation_lkp> toCacheModel();

	public other_designation_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}