/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the potential_project_needs service. Represents a row in the &quot;whp_potential_project_needs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.potential_project_needsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.potential_project_needsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see potential_project_needs
 * @see com.iucn.whp.dbservice.model.impl.potential_project_needsImpl
 * @see com.iucn.whp.dbservice.model.impl.potential_project_needsModelImpl
 * @generated
 */
public interface potential_project_needsModel extends BaseModel<potential_project_needs> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a potential_project_needs model instance should use the {@link potential_project_needs} interface instead.
	 */

	/**
	 * Returns the primary key of this potential_project_needs.
	 *
	 * @return the primary key of this potential_project_needs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this potential_project_needs.
	 *
	 * @param primaryKey the primary key of this potential_project_needs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ppn_id of this potential_project_needs.
	 *
	 * @return the ppn_id of this potential_project_needs
	 */
	public long getPpn_id();

	/**
	 * Sets the ppn_id of this potential_project_needs.
	 *
	 * @param ppn_id the ppn_id of this potential_project_needs
	 */
	public void setPpn_id(long ppn_id);

	/**
	 * Returns the assessment_version_id of this potential_project_needs.
	 *
	 * @return the assessment_version_id of this potential_project_needs
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this potential_project_needs.
	 *
	 * @param assessment_version_id the assessment_version_id of this potential_project_needs
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the organization_individual of this potential_project_needs.
	 *
	 * @return the organization_individual of this potential_project_needs
	 */
	@AutoEscape
	public String getOrganization_individual();

	/**
	 * Sets the organization_individual of this potential_project_needs.
	 *
	 * @param organization_individual the organization_individual of this potential_project_needs
	 */
	public void setOrganization_individual(String organization_individual);

	/**
	 * Returns the description of this potential_project_needs.
	 *
	 * @return the description of this potential_project_needs
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this potential_project_needs.
	 *
	 * @param description the description of this potential_project_needs
	 */
	public void setDescription(String description);

	/**
	 * Returns the contact_details of this potential_project_needs.
	 *
	 * @return the contact_details of this potential_project_needs
	 */
	@AutoEscape
	public String getContact_details();

	/**
	 * Sets the contact_details of this potential_project_needs.
	 *
	 * @param contact_details the contact_details of this potential_project_needs
	 */
	public void setContact_details(String contact_details);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(potential_project_needs potential_project_needs);

	public int hashCode();

	public CacheModel<potential_project_needs> toCacheModel();

	public potential_project_needs toEscapedModel();

	public String toString();

	public String toXmlString();
}