/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the prot_mgmt_overall service. Represents a row in the &quot;whp_prot_mgmt_overall&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.prot_mgmt_overallModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.prot_mgmt_overallImpl}.
 * </p>
 *
 * @author alok.sen
 * @see prot_mgmt_overall
 * @see com.iucn.whp.dbservice.model.impl.prot_mgmt_overallImpl
 * @see com.iucn.whp.dbservice.model.impl.prot_mgmt_overallModelImpl
 * @generated
 */
public interface prot_mgmt_overallModel extends BaseModel<prot_mgmt_overall> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a prot_mgmt_overall model instance should use the {@link prot_mgmt_overall} interface instead.
	 */

	/**
	 * Returns the primary key of this prot_mgmt_overall.
	 *
	 * @return the primary key of this prot_mgmt_overall
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this prot_mgmt_overall.
	 *
	 * @param primaryKey the primary key of this prot_mgmt_overall
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pmo_id of this prot_mgmt_overall.
	 *
	 * @return the pmo_id of this prot_mgmt_overall
	 */
	public long getPmo_id();

	/**
	 * Sets the pmo_id of this prot_mgmt_overall.
	 *
	 * @param pmo_id the pmo_id of this prot_mgmt_overall
	 */
	public void setPmo_id(long pmo_id);

	/**
	 * Returns the assessment_version_id of this prot_mgmt_overall.
	 *
	 * @return the assessment_version_id of this prot_mgmt_overall
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this prot_mgmt_overall.
	 *
	 * @param assessment_version_id the assessment_version_id of this prot_mgmt_overall
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the justification of this prot_mgmt_overall.
	 *
	 * @return the justification of this prot_mgmt_overall
	 */
	@AutoEscape
	public String getJustification();

	/**
	 * Sets the justification of this prot_mgmt_overall.
	 *
	 * @param justification the justification of this prot_mgmt_overall
	 */
	public void setJustification(String justification);

	/**
	 * Returns the rating of this prot_mgmt_overall.
	 *
	 * @return the rating of this prot_mgmt_overall
	 */
	public long getRating();

	/**
	 * Sets the rating of this prot_mgmt_overall.
	 *
	 * @param rating the rating of this prot_mgmt_overall
	 */
	public void setRating(long rating);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(prot_mgmt_overall prot_mgmt_overall);

	public int hashCode();

	public CacheModel<prot_mgmt_overall> toCacheModel();

	public prot_mgmt_overall toEscapedModel();

	public String toString();

	public String toXmlString();
}