/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the protection_management service. Represents a row in the &quot;whp_protection_management&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.protection_managementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.protection_managementImpl}.
 * </p>
 *
 * @author alok.sen
 * @see protection_management
 * @see com.iucn.whp.dbservice.model.impl.protection_managementImpl
 * @see com.iucn.whp.dbservice.model.impl.protection_managementModelImpl
 * @generated
 */
public interface protection_managementModel extends BaseModel<protection_management> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a protection_management model instance should use the {@link protection_management} interface instead.
	 */

	/**
	 * Returns the primary key of this protection_management.
	 *
	 * @return the primary key of this protection_management
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this protection_management.
	 *
	 * @param primaryKey the primary key of this protection_management
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pm_id of this protection_management.
	 *
	 * @return the pm_id of this protection_management
	 */
	public long getPm_id();

	/**
	 * Sets the pm_id of this protection_management.
	 *
	 * @param pm_id the pm_id of this protection_management
	 */
	public void setPm_id(long pm_id);

	/**
	 * Returns the assessment_version_id of this protection_management.
	 *
	 * @return the assessment_version_id of this protection_management
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this protection_management.
	 *
	 * @param assessment_version_id the assessment_version_id of this protection_management
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the topic_id of this protection_management.
	 *
	 * @return the topic_id of this protection_management
	 */
	public long getTopic_id();

	/**
	 * Sets the topic_id of this protection_management.
	 *
	 * @param topic_id the topic_id of this protection_management
	 */
	public void setTopic_id(long topic_id);

	/**
	 * Returns the justification of this protection_management.
	 *
	 * @return the justification of this protection_management
	 */
	@AutoEscape
	public String getJustification();

	/**
	 * Sets the justification of this protection_management.
	 *
	 * @param justification the justification of this protection_management
	 */
	public void setJustification(String justification);

	/**
	 * Returns the rating of this protection_management.
	 *
	 * @return the rating of this protection_management
	 */
	public long getRating();

	/**
	 * Sets the rating of this protection_management.
	 *
	 * @param rating the rating of this protection_management
	 */
	public void setRating(long rating);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(protection_management protection_management);

	public int hashCode();

	public CacheModel<protection_management> toCacheModel();

	public protection_management toEscapedModel();

	public String toString();

	public String toXmlString();
}