/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the references service. Represents a row in the &quot;whp_references&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.referencesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.referencesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see references
 * @see com.iucn.whp.dbservice.model.impl.referencesImpl
 * @see com.iucn.whp.dbservice.model.impl.referencesModelImpl
 * @generated
 */
public interface referencesModel extends BaseModel<references> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a references model instance should use the {@link references} interface instead.
	 */

	/**
	 * Returns the primary key of this references.
	 *
	 * @return the primary key of this references
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this references.
	 *
	 * @param primaryKey the primary key of this references
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reference_id of this references.
	 *
	 * @return the reference_id of this references
	 */
	public long getReference_id();

	/**
	 * Sets the reference_id of this references.
	 *
	 * @param reference_id the reference_id of this references
	 */
	public void setReference_id(long reference_id);

	/**
	 * Returns the assessment_version_id of this references.
	 *
	 * @return the assessment_version_id of this references
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this references.
	 *
	 * @param assessment_version_id the assessment_version_id of this references
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the rn of this references.
	 *
	 * @return the rn of this references
	 */
	public long getRn();

	/**
	 * Sets the rn of this references.
	 *
	 * @param rn the rn of this references
	 */
	public void setRn(long rn);

	/**
	 * Returns the references of this references.
	 *
	 * @return the references of this references
	 */
	@AutoEscape
	public String getReferences();

	/**
	 * Sets the references of this references.
	 *
	 * @param references the references of this references
	 */
	public void setReferences(String references);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(references references);

	public int hashCode();

	public CacheModel<references> toCacheModel();

	public references toEscapedModel();

	public String toString();

	public String toXmlString();
}