/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the reinforced_monitoring service. Represents a row in the &quot;whp_reinforced_monitoring&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.reinforced_monitoringModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.reinforced_monitoringImpl}.
 * </p>
 *
 * @author alok.sen
 * @see reinforced_monitoring
 * @see com.iucn.whp.dbservice.model.impl.reinforced_monitoringImpl
 * @see com.iucn.whp.dbservice.model.impl.reinforced_monitoringModelImpl
 * @generated
 */
public interface reinforced_monitoringModel extends BaseModel<reinforced_monitoring> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reinforced_monitoring model instance should use the {@link reinforced_monitoring} interface instead.
	 */

	/**
	 * Returns the primary key of this reinforced_monitoring.
	 *
	 * @return the primary key of this reinforced_monitoring
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reinforced_monitoring.
	 *
	 * @param primaryKey the primary key of this reinforced_monitoring
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_reinforced_monitoring_id of this reinforced_monitoring.
	 *
	 * @return the whp_sites_reinforced_monitoring_id of this reinforced_monitoring
	 */
	public long getWhp_sites_reinforced_monitoring_id();

	/**
	 * Sets the whp_sites_reinforced_monitoring_id of this reinforced_monitoring.
	 *
	 * @param whp_sites_reinforced_monitoring_id the whp_sites_reinforced_monitoring_id of this reinforced_monitoring
	 */
	public void setWhp_sites_reinforced_monitoring_id(
		long whp_sites_reinforced_monitoring_id);

	/**
	 * Returns the site_id of this reinforced_monitoring.
	 *
	 * @return the site_id of this reinforced_monitoring
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this reinforced_monitoring.
	 *
	 * @param site_id the site_id of this reinforced_monitoring
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the reinforced_date of this reinforced_monitoring.
	 *
	 * @return the reinforced_date of this reinforced_monitoring
	 */
	public Date getReinforced_date();

	/**
	 * Sets the reinforced_date of this reinforced_monitoring.
	 *
	 * @param reinforced_date the reinforced_date of this reinforced_monitoring
	 */
	public void setReinforced_date(Date reinforced_date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(reinforced_monitoring reinforced_monitoring);

	public int hashCode();

	public CacheModel<reinforced_monitoring> toCacheModel();

	public reinforced_monitoring toEscapedModel();

	public String toString();

	public String toXmlString();
}