/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the sites_thematic service. Represents a row in the &quot;whp_sites_thematic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.sites_thematicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.sites_thematicImpl}.
 * </p>
 *
 * @author alok.sen
 * @see sites_thematic
 * @see com.iucn.whp.dbservice.model.impl.sites_thematicImpl
 * @see com.iucn.whp.dbservice.model.impl.sites_thematicModelImpl
 * @generated
 */
public interface sites_thematicModel extends BaseModel<sites_thematic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sites_thematic model instance should use the {@link sites_thematic} interface instead.
	 */

	/**
	 * Returns the primary key of this sites_thematic.
	 *
	 * @return the primary key of this sites_thematic
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sites_thematic.
	 *
	 * @param primaryKey the primary key of this sites_thematic
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sitethematicid of this sites_thematic.
	 *
	 * @return the sitethematicid of this sites_thematic
	 */
	public long getSitethematicid();

	/**
	 * Sets the sitethematicid of this sites_thematic.
	 *
	 * @param sitethematicid the sitethematicid of this sites_thematic
	 */
	public void setSitethematicid(long sitethematicid);

	/**
	 * Returns the site_id of this sites_thematic.
	 *
	 * @return the site_id of this sites_thematic
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this sites_thematic.
	 *
	 * @param site_id the site_id of this sites_thematic
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the thematicid of this sites_thematic.
	 *
	 * @return the thematicid of this sites_thematic
	 */
	public long getThematicid();

	/**
	 * Sets the thematicid of this sites_thematic.
	 *
	 * @param thematicid the thematicid of this sites_thematic
	 */
	public void setThematicid(long thematicid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(sites_thematic sites_thematic);

	public int hashCode();

	public CacheModel<sites_thematic> toCacheModel();

	public sites_thematic toEscapedModel();

	public String toString();

	public String toXmlString();
}