/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the site_assessment_versions service. Represents a row in the &quot;whp_site_assessment_versions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.site_assessment_versionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.site_assessment_versionsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see site_assessment_versions
 * @see com.iucn.whp.dbservice.model.impl.site_assessment_versionsImpl
 * @see com.iucn.whp.dbservice.model.impl.site_assessment_versionsModelImpl
 * @generated
 */
public interface site_assessment_versionsModel extends BaseModel<site_assessment_versions> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a site_assessment_versions model instance should use the {@link site_assessment_versions} interface instead.
	 */

	/**
	 * Returns the primary key of this site_assessment_versions.
	 *
	 * @return the primary key of this site_assessment_versions
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this site_assessment_versions.
	 *
	 * @param primaryKey the primary key of this site_assessment_versions
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the assessment_version_id of this site_assessment_versions.
	 *
	 * @return the assessment_version_id of this site_assessment_versions
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this site_assessment_versions.
	 *
	 * @param assessment_version_id the assessment_version_id of this site_assessment_versions
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the stage_id of this site_assessment_versions.
	 *
	 * @return the stage_id of this site_assessment_versions
	 */
	public long getStage_id();

	/**
	 * Sets the stage_id of this site_assessment_versions.
	 *
	 * @param stage_id the stage_id of this site_assessment_versions
	 */
	public void setStage_id(long stage_id);

	/**
	 * Returns the assessment_id of this site_assessment_versions.
	 *
	 * @return the assessment_id of this site_assessment_versions
	 */
	public long getAssessment_id();

	/**
	 * Sets the assessment_id of this site_assessment_versions.
	 *
	 * @param assessment_id the assessment_id of this site_assessment_versions
	 */
	public void setAssessment_id(long assessment_id);

	/**
	 * Returns the start_date of this site_assessment_versions.
	 *
	 * @return the start_date of this site_assessment_versions
	 */
	public Date getStart_date();

	/**
	 * Sets the start_date of this site_assessment_versions.
	 *
	 * @param start_date the start_date of this site_assessment_versions
	 */
	public void setStart_date(Date start_date);

	/**
	 * Returns the end_date of this site_assessment_versions.
	 *
	 * @return the end_date of this site_assessment_versions
	 */
	public Date getEnd_date();

	/**
	 * Sets the end_date of this site_assessment_versions.
	 *
	 * @param end_date the end_date of this site_assessment_versions
	 */
	public void setEnd_date(Date end_date);

	/**
	 * Returns the userid of this site_assessment_versions.
	 *
	 * @return the userid of this site_assessment_versions
	 */
	public long getUserid();

	/**
	 * Sets the userid of this site_assessment_versions.
	 *
	 * @param userid the userid of this site_assessment_versions
	 */
	public void setUserid(long userid);

	/**
	 * Returns the initiation_date of this site_assessment_versions.
	 *
	 * @return the initiation_date of this site_assessment_versions
	 */
	public Date getInitiation_date();

	/**
	 * Sets the initiation_date of this site_assessment_versions.
	 *
	 * @param initiation_date the initiation_date of this site_assessment_versions
	 */
	public void setInitiation_date(Date initiation_date);

	/**
	 * Returns the language of this site_assessment_versions.
	 *
	 * @return the language of this site_assessment_versions
	 */
	public long getLanguage();

	/**
	 * Sets the language of this site_assessment_versions.
	 *
	 * @param language the language of this site_assessment_versions
	 */
	public void setLanguage(long language);

	/**
	 * Returns the version_code of this site_assessment_versions.
	 *
	 * @return the version_code of this site_assessment_versions
	 */
	public double getVersion_code();

	/**
	 * Sets the version_code of this site_assessment_versions.
	 *
	 * @param version_code the version_code of this site_assessment_versions
	 */
	public void setVersion_code(double version_code);

	/**
	 * Returns the is_translated of this site_assessment_versions.
	 *
	 * @return the is_translated of this site_assessment_versions
	 */
	public boolean getIs_translated();

	/**
	 * Returns <code>true</code> if this site_assessment_versions is is_translated.
	 *
	 * @return <code>true</code> if this site_assessment_versions is is_translated; <code>false</code> otherwise
	 */
	public boolean isIs_translated();

	/**
	 * Sets whether this site_assessment_versions is is_translated.
	 *
	 * @param is_translated the is_translated of this site_assessment_versions
	 */
	public void setIs_translated(boolean is_translated);

	/**
	 * Returns the parent_assessment_versionid of this site_assessment_versions.
	 *
	 * @return the parent_assessment_versionid of this site_assessment_versions
	 */
	public long getParent_assessment_versionid();

	/**
	 * Sets the parent_assessment_versionid of this site_assessment_versions.
	 *
	 * @param parent_assessment_versionid the parent_assessment_versionid of this site_assessment_versions
	 */
	public void setParent_assessment_versionid(long parent_assessment_versionid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(site_assessment_versions site_assessment_versions);

	public int hashCode();

	public CacheModel<site_assessment_versions> toCacheModel();

	public site_assessment_versions toEscapedModel();

	public String toString();

	public String toXmlString();
}