/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the state_trend_biodivvals service. Represents a row in the &quot;whp_state_trend_biodivvals&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.state_trend_biodivvalsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.state_trend_biodivvalsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see state_trend_biodivvals
 * @see com.iucn.whp.dbservice.model.impl.state_trend_biodivvalsImpl
 * @see com.iucn.whp.dbservice.model.impl.state_trend_biodivvalsModelImpl
 * @generated
 */
public interface state_trend_biodivvalsModel extends BaseModel<state_trend_biodivvals> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a state_trend_biodivvals model instance should use the {@link state_trend_biodivvals} interface instead.
	 */

	/**
	 * Returns the primary key of this state_trend_biodivvals.
	 *
	 * @return the primary key of this state_trend_biodivvals
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this state_trend_biodivvals.
	 *
	 * @param primaryKey the primary key of this state_trend_biodivvals
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the state_trend_biodivvals_id of this state_trend_biodivvals.
	 *
	 * @return the state_trend_biodivvals_id of this state_trend_biodivvals
	 */
	public long getState_trend_biodivvals_id();

	/**
	 * Sets the state_trend_biodivvals_id of this state_trend_biodivvals.
	 *
	 * @param state_trend_biodivvals_id the state_trend_biodivvals_id of this state_trend_biodivvals
	 */
	public void setState_trend_biodivvals_id(long state_trend_biodivvals_id);

	/**
	 * Returns the assessment_version_id of this state_trend_biodivvals.
	 *
	 * @return the assessment_version_id of this state_trend_biodivvals
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this state_trend_biodivvals.
	 *
	 * @param assessment_version_id the assessment_version_id of this state_trend_biodivvals
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the justification of this state_trend_biodivvals.
	 *
	 * @return the justification of this state_trend_biodivvals
	 */
	@AutoEscape
	public String getJustification();

	/**
	 * Sets the justification of this state_trend_biodivvals.
	 *
	 * @param justification the justification of this state_trend_biodivvals
	 */
	public void setJustification(String justification);

	/**
	 * Returns the state_id of this state_trend_biodivvals.
	 *
	 * @return the state_id of this state_trend_biodivvals
	 */
	public long getState_id();

	/**
	 * Sets the state_id of this state_trend_biodivvals.
	 *
	 * @param state_id the state_id of this state_trend_biodivvals
	 */
	public void setState_id(long state_id);

	/**
	 * Returns the trend_id of this state_trend_biodivvals.
	 *
	 * @return the trend_id of this state_trend_biodivvals
	 */
	public long getTrend_id();

	/**
	 * Sets the trend_id of this state_trend_biodivvals.
	 *
	 * @param trend_id the trend_id of this state_trend_biodivvals
	 */
	public void setTrend_id(long trend_id);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(state_trend_biodivvals state_trend_biodivvals);

	public int hashCode();

	public CacheModel<state_trend_biodivvals> toCacheModel();

	public state_trend_biodivvals toEscapedModel();

	public String toString();

	public String toXmlString();
}