/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the state_lkp service. Represents a row in the &quot;whp_state_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.state_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.state_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see state_lkp
 * @see com.iucn.whp.dbservice.model.impl.state_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.state_lkpModelImpl
 * @generated
 */
public interface state_lkpModel extends BaseModel<state_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a state_lkp model instance should use the {@link state_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this state_lkp.
	 *
	 * @return the primary key of this state_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this state_lkp.
	 *
	 * @param primaryKey the primary key of this state_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the state_id of this state_lkp.
	 *
	 * @return the state_id of this state_lkp
	 */
	public long getState_id();

	/**
	 * Sets the state_id of this state_lkp.
	 *
	 * @param state_id the state_id of this state_lkp
	 */
	public void setState_id(long state_id);

	/**
	 * Returns the state of this state_lkp.
	 *
	 * @return the state of this state_lkp
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this state_lkp.
	 *
	 * @param state the state of this state_lkp
	 */
	public void setState(String state);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(state_lkp state_lkp);

	public int hashCode();

	public CacheModel<state_lkp> toCacheModel();

	public state_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}