/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the thematic_lkp service. Represents a row in the &quot;whp_thematic_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.thematic_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.thematic_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see thematic_lkp
 * @see com.iucn.whp.dbservice.model.impl.thematic_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.thematic_lkpModelImpl
 * @generated
 */
public interface thematic_lkpModel extends BaseModel<thematic_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a thematic_lkp model instance should use the {@link thematic_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this thematic_lkp.
	 *
	 * @return the primary key of this thematic_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this thematic_lkp.
	 *
	 * @param primaryKey the primary key of this thematic_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the thematicid of this thematic_lkp.
	 *
	 * @return the thematicid of this thematic_lkp
	 */
	public long getThematicid();

	/**
	 * Sets the thematicid of this thematic_lkp.
	 *
	 * @param thematicid the thematicid of this thematic_lkp
	 */
	public void setThematicid(long thematicid);

	/**
	 * Returns the thematic of this thematic_lkp.
	 *
	 * @return the thematic of this thematic_lkp
	 */
	@AutoEscape
	public String getThematic();

	/**
	 * Sets the thematic of this thematic_lkp.
	 *
	 * @param thematic the thematic of this thematic_lkp
	 */
	public void setThematic(String thematic);

	/**
	 * Returns the description of this thematic_lkp.
	 *
	 * @return the description of this thematic_lkp
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this thematic_lkp.
	 *
	 * @param description the description of this thematic_lkp
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(thematic_lkp thematic_lkp);

	public int hashCode();

	public CacheModel<thematic_lkp> toCacheModel();

	public thematic_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}