/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the threat_rating_lkp service. Represents a row in the &quot;whp_threat_rating_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.threat_rating_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.threat_rating_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see threat_rating_lkp
 * @see com.iucn.whp.dbservice.model.impl.threat_rating_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.threat_rating_lkpModelImpl
 * @generated
 */
public interface threat_rating_lkpModel extends BaseModel<threat_rating_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a threat_rating_lkp model instance should use the {@link threat_rating_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this threat_rating_lkp.
	 *
	 * @return the primary key of this threat_rating_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this threat_rating_lkp.
	 *
	 * @param primaryKey the primary key of this threat_rating_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this threat_rating_lkp.
	 *
	 * @return the ID of this threat_rating_lkp
	 */
	public long getId();

	/**
	 * Sets the ID of this threat_rating_lkp.
	 *
	 * @param id the ID of this threat_rating_lkp
	 */
	public void setId(long id);

	/**
	 * Returns the rating of this threat_rating_lkp.
	 *
	 * @return the rating of this threat_rating_lkp
	 */
	@AutoEscape
	public String getRating();

	/**
	 * Sets the rating of this threat_rating_lkp.
	 *
	 * @param rating the rating of this threat_rating_lkp
	 */
	public void setRating(String rating);

	/**
	 * Returns the description of this threat_rating_lkp.
	 *
	 * @return the description of this threat_rating_lkp
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this threat_rating_lkp.
	 *
	 * @param description the description of this threat_rating_lkp
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(threat_rating_lkp threat_rating_lkp);

	public int hashCode();

	public CacheModel<threat_rating_lkp> toCacheModel();

	public threat_rating_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}