/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the threat_categories_lkp service. Represents a row in the &quot;whp_threat_categories_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.threat_categories_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.threat_categories_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see threat_categories_lkp
 * @see com.iucn.whp.dbservice.model.impl.threat_categories_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.threat_categories_lkpModelImpl
 * @generated
 */
public interface threat_categories_lkpModel extends BaseModel<threat_categories_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a threat_categories_lkp model instance should use the {@link threat_categories_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this threat_categories_lkp.
	 *
	 * @return the primary key of this threat_categories_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this threat_categories_lkp.
	 *
	 * @param primaryKey the primary key of this threat_categories_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the threat categoryid of this threat_categories_lkp.
	 *
	 * @return the threat categoryid of this threat_categories_lkp
	 */
	public long getThreatCategoryid();

	/**
	 * Sets the threat categoryid of this threat_categories_lkp.
	 *
	 * @param threatCategoryid the threat categoryid of this threat_categories_lkp
	 */
	public void setThreatCategoryid(long threatCategoryid);

	/**
	 * Returns the threat_category of this threat_categories_lkp.
	 *
	 * @return the threat_category of this threat_categories_lkp
	 */
	@AutoEscape
	public String getThreat_category();

	/**
	 * Sets the threat_category of this threat_categories_lkp.
	 *
	 * @param threat_category the threat_category of this threat_categories_lkp
	 */
	public void setThreat_category(String threat_category);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(threat_categories_lkp threat_categories_lkp);

	public int hashCode();

	public CacheModel<threat_categories_lkp> toCacheModel();

	public threat_categories_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}