/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the threat_summary_potential service. Represents a row in the &quot;whp_threat_summary_potential&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.threat_summary_potentialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.threat_summary_potentialImpl}.
 * </p>
 *
 * @author alok.sen
 * @see threat_summary_potential
 * @see com.iucn.whp.dbservice.model.impl.threat_summary_potentialImpl
 * @see com.iucn.whp.dbservice.model.impl.threat_summary_potentialModelImpl
 * @generated
 */
public interface threat_summary_potentialModel extends BaseModel<threat_summary_potential> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a threat_summary_potential model instance should use the {@link threat_summary_potential} interface instead.
	 */

	/**
	 * Returns the primary key of this threat_summary_potential.
	 *
	 * @return the primary key of this threat_summary_potential
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this threat_summary_potential.
	 *
	 * @param primaryKey the primary key of this threat_summary_potential
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the threat_sum_potential_id of this threat_summary_potential.
	 *
	 * @return the threat_sum_potential_id of this threat_summary_potential
	 */
	public long getThreat_sum_potential_id();

	/**
	 * Sets the threat_sum_potential_id of this threat_summary_potential.
	 *
	 * @param threat_sum_potential_id the threat_sum_potential_id of this threat_summary_potential
	 */
	public void setThreat_sum_potential_id(long threat_sum_potential_id);

	/**
	 * Returns the assessment_version_id of this threat_summary_potential.
	 *
	 * @return the assessment_version_id of this threat_summary_potential
	 */
	public long getAssessment_version_id();

	/**
	 * Sets the assessment_version_id of this threat_summary_potential.
	 *
	 * @param assessment_version_id the assessment_version_id of this threat_summary_potential
	 */
	public void setAssessment_version_id(long assessment_version_id);

	/**
	 * Returns the overall_potential of this threat_summary_potential.
	 *
	 * @return the overall_potential of this threat_summary_potential
	 */
	@AutoEscape
	public String getOverall_potential();

	/**
	 * Sets the overall_potential of this threat_summary_potential.
	 *
	 * @param overall_potential the overall_potential of this threat_summary_potential
	 */
	public void setOverall_potential(String overall_potential);

	/**
	 * Returns the threat_rating of this threat_summary_potential.
	 *
	 * @return the threat_rating of this threat_summary_potential
	 */
	public long getThreat_rating();

	/**
	 * Sets the threat_rating of this threat_summary_potential.
	 *
	 * @param threat_rating the threat_rating of this threat_summary_potential
	 */
	public void setThreat_rating(long threat_rating);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(threat_summary_potential threat_summary_potential);

	public int hashCode();

	public CacheModel<threat_summary_potential> toCacheModel();

	public threat_summary_potential toEscapedModel();

	public String toString();

	public String toXmlString();
}