/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the trend_lkp service. Represents a row in the &quot;whp_trend_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.trend_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.trend_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see trend_lkp
 * @see com.iucn.whp.dbservice.model.impl.trend_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.trend_lkpModelImpl
 * @generated
 */
public interface trend_lkpModel extends BaseModel<trend_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a trend_lkp model instance should use the {@link trend_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this trend_lkp.
	 *
	 * @return the primary key of this trend_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this trend_lkp.
	 *
	 * @param primaryKey the primary key of this trend_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the trend_id of this trend_lkp.
	 *
	 * @return the trend_id of this trend_lkp
	 */
	public long getTrend_id();

	/**
	 * Sets the trend_id of this trend_lkp.
	 *
	 * @param trend_id the trend_id of this trend_lkp
	 */
	public void setTrend_id(long trend_id);

	/**
	 * Returns the trend of this trend_lkp.
	 *
	 * @return the trend of this trend_lkp
	 */
	@AutoEscape
	public String getTrend();

	/**
	 * Sets the trend of this trend_lkp.
	 *
	 * @param trend the trend of this trend_lkp
	 */
	public void setTrend(String trend);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(trend_lkp trend_lkp);

	public int hashCode();

	public CacheModel<trend_lkp> toCacheModel();

	public trend_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}