/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the understanding_benefits_lkp service. Represents a row in the &quot;whp_understanding_benefits_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.understanding_benefits_lkpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.understanding_benefits_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see understanding_benefits_lkp
 * @see com.iucn.whp.dbservice.model.impl.understanding_benefits_lkpImpl
 * @see com.iucn.whp.dbservice.model.impl.understanding_benefits_lkpModelImpl
 * @generated
 */
public interface understanding_benefits_lkpModel extends BaseModel<understanding_benefits_lkp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a understanding_benefits_lkp model instance should use the {@link understanding_benefits_lkp} interface instead.
	 */

	/**
	 * Returns the primary key of this understanding_benefits_lkp.
	 *
	 * @return the primary key of this understanding_benefits_lkp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this understanding_benefits_lkp.
	 *
	 * @param primaryKey the primary key of this understanding_benefits_lkp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the benefits_id of this understanding_benefits_lkp.
	 *
	 * @return the benefits_id of this understanding_benefits_lkp
	 */
	public long getBenefits_id();

	/**
	 * Sets the benefits_id of this understanding_benefits_lkp.
	 *
	 * @param benefits_id the benefits_id of this understanding_benefits_lkp
	 */
	public void setBenefits_id(long benefits_id);

	/**
	 * Returns the selected_benefit of this understanding_benefits_lkp.
	 *
	 * @return the selected_benefit of this understanding_benefits_lkp
	 */
	@AutoEscape
	public String getSelected_benefit();

	/**
	 * Sets the selected_benefit of this understanding_benefits_lkp.
	 *
	 * @param selected_benefit the selected_benefit of this understanding_benefits_lkp
	 */
	public void setSelected_benefit(String selected_benefit);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(understanding_benefits_lkp understanding_benefits_lkp);

	public int hashCode();

	public CacheModel<understanding_benefits_lkp> toCacheModel();

	public understanding_benefits_lkp toEscapedModel();

	public String toString();

	public String toXmlString();
}