/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the unesco_region_country service. Represents a row in the &quot;whp_unesco_region_country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.unesco_region_countryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.unesco_region_countryImpl}.
 * </p>
 *
 * @author alok.sen
 * @see unesco_region_country
 * @see com.iucn.whp.dbservice.model.impl.unesco_region_countryImpl
 * @see com.iucn.whp.dbservice.model.impl.unesco_region_countryModelImpl
 * @generated
 */
public interface unesco_region_countryModel extends BaseModel<unesco_region_country> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a unesco_region_country model instance should use the {@link unesco_region_country} interface instead.
	 */

	/**
	 * Returns the primary key of this unesco_region_country.
	 *
	 * @return the primary key of this unesco_region_country
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this unesco_region_country.
	 *
	 * @param primaryKey the primary key of this unesco_region_country
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the whp_unesco_region_country_id of this unesco_region_country.
	 *
	 * @return the whp_unesco_region_country_id of this unesco_region_country
	 */
	public int getWhp_unesco_region_country_id();

	/**
	 * Sets the whp_unesco_region_country_id of this unesco_region_country.
	 *
	 * @param whp_unesco_region_country_id the whp_unesco_region_country_id of this unesco_region_country
	 */
	public void setWhp_unesco_region_country_id(
		int whp_unesco_region_country_id);

	/**
	 * Returns the countryid of this unesco_region_country.
	 *
	 * @return the countryid of this unesco_region_country
	 */
	public int getCountryid();

	/**
	 * Sets the countryid of this unesco_region_country.
	 *
	 * @param countryid the countryid of this unesco_region_country
	 */
	public void setCountryid(int countryid);

	/**
	 * Returns the unesco_region_id of this unesco_region_country.
	 *
	 * @return the unesco_region_id of this unesco_region_country
	 */
	public int getUnesco_region_id();

	/**
	 * Sets the unesco_region_id of this unesco_region_country.
	 *
	 * @param unesco_region_id the unesco_region_id of this unesco_region_country
	 */
	public void setUnesco_region_id(int unesco_region_id);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(unesco_region_country unesco_region_country);

	public int hashCode();

	public CacheModel<unesco_region_country> toCacheModel();

	public unesco_region_country toEscapedModel();

	public String toString();

	public String toXmlString();
}