/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the whp_sites_country service. Represents a row in the &quot;whp_whp_sites_country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_countryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_countryImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_country
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_countryImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_countryModelImpl
 * @generated
 */
public interface whp_sites_countryModel extends BaseModel<whp_sites_country> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_country model instance should use the {@link whp_sites_country} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_country.
	 *
	 * @return the primary key of this whp_sites_country
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_country.
	 *
	 * @param primaryKey the primary key of this whp_sites_country
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_country_id of this whp_sites_country.
	 *
	 * @return the whp_sites_country_id of this whp_sites_country
	 */
	public long getWhp_sites_country_id();

	/**
	 * Sets the whp_sites_country_id of this whp_sites_country.
	 *
	 * @param whp_sites_country_id the whp_sites_country_id of this whp_sites_country
	 */
	public void setWhp_sites_country_id(long whp_sites_country_id);

	/**
	 * Returns the site_id of this whp_sites_country.
	 *
	 * @return the site_id of this whp_sites_country
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_country.
	 *
	 * @param site_id the site_id of this whp_sites_country
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the countryid of this whp_sites_country.
	 *
	 * @return the countryid of this whp_sites_country
	 */
	public int getCountryid();

	/**
	 * Sets the countryid of this whp_sites_country.
	 *
	 * @param countryid the countryid of this whp_sites_country
	 */
	public void setCountryid(int countryid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_country whp_sites_country);

	public int hashCode();

	public CacheModel<whp_sites_country> toCacheModel();

	public whp_sites_country toEscapedModel();

	public String toString();

	public String toXmlString();
}