/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_site_danger_list service. Represents a row in the &quot;whp_whp_site_danger_list&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_site_danger_listModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_site_danger_listImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_site_danger_list
 * @see com.iucn.whp.dbservice.model.impl.whp_site_danger_listImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_site_danger_listModelImpl
 * @generated
 */
public interface whp_site_danger_listModel extends BaseModel<whp_site_danger_list> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_site_danger_list model instance should use the {@link whp_site_danger_list} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_site_danger_list.
	 *
	 * @return the primary key of this whp_site_danger_list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_site_danger_list.
	 *
	 * @param primaryKey the primary key of this whp_site_danger_list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_site_danger_list_id of this whp_site_danger_list.
	 *
	 * @return the whp_site_danger_list_id of this whp_site_danger_list
	 */
	public long getWhp_site_danger_list_id();

	/**
	 * Sets the whp_site_danger_list_id of this whp_site_danger_list.
	 *
	 * @param whp_site_danger_list_id the whp_site_danger_list_id of this whp_site_danger_list
	 */
	public void setWhp_site_danger_list_id(long whp_site_danger_list_id);

	/**
	 * Returns the site_id of this whp_site_danger_list.
	 *
	 * @return the site_id of this whp_site_danger_list
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_site_danger_list.
	 *
	 * @param site_id the site_id of this whp_site_danger_list
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the status_id of this whp_site_danger_list.
	 *
	 * @return the status_id of this whp_site_danger_list
	 */
	public int getStatus_id();

	/**
	 * Sets the status_id of this whp_site_danger_list.
	 *
	 * @param status_id the status_id of this whp_site_danger_list
	 */
	public void setStatus_id(int status_id);

	/**
	 * Returns the year of this whp_site_danger_list.
	 *
	 * @return the year of this whp_site_danger_list
	 */
	public Date getYear();

	/**
	 * Sets the year of this whp_site_danger_list.
	 *
	 * @param year the year of this whp_site_danger_list
	 */
	public void setYear(Date year);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_site_danger_list whp_site_danger_list);

	public int hashCode();

	public CacheModel<whp_site_danger_list> toCacheModel();

	public whp_site_danger_list toEscapedModel();

	public String toString();

	public String toXmlString();
}