/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites_soouv service. Represents a row in the &quot;whp_whp_sites_soouv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_soouvModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_soouvImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_soouv
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_soouvImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_soouvModelImpl
 * @generated
 */
public interface whp_sites_soouvModel extends BaseModel<whp_sites_soouv> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_soouv model instance should use the {@link whp_sites_soouv} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_soouv.
	 *
	 * @return the primary key of this whp_sites_soouv
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_soouv.
	 *
	 * @param primaryKey the primary key of this whp_sites_soouv
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_soouv_id of this whp_sites_soouv.
	 *
	 * @return the whp_sites_soouv_id of this whp_sites_soouv
	 */
	public long getWhp_sites_soouv_id();

	/**
	 * Sets the whp_sites_soouv_id of this whp_sites_soouv.
	 *
	 * @param whp_sites_soouv_id the whp_sites_soouv_id of this whp_sites_soouv
	 */
	public void setWhp_sites_soouv_id(long whp_sites_soouv_id);

	/**
	 * Returns the site_id of this whp_sites_soouv.
	 *
	 * @return the site_id of this whp_sites_soouv
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_soouv.
	 *
	 * @param site_id the site_id of this whp_sites_soouv
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the description_en of this whp_sites_soouv.
	 *
	 * @return the description_en of this whp_sites_soouv
	 */
	@AutoEscape
	public String getDescription_en();

	/**
	 * Sets the description_en of this whp_sites_soouv.
	 *
	 * @param description_en the description_en of this whp_sites_soouv
	 */
	public void setDescription_en(String description_en);

	/**
	 * Returns the description_fr of this whp_sites_soouv.
	 *
	 * @return the description_fr of this whp_sites_soouv
	 */
	@AutoEscape
	public String getDescription_fr();

	/**
	 * Sets the description_fr of this whp_sites_soouv.
	 *
	 * @param description_fr the description_fr of this whp_sites_soouv
	 */
	public void setDescription_fr(String description_fr);

	/**
	 * Returns the soouv_date of this whp_sites_soouv.
	 *
	 * @return the soouv_date of this whp_sites_soouv
	 */
	public Date getSoouv_date();

	/**
	 * Sets the soouv_date of this whp_sites_soouv.
	 *
	 * @param soouv_date the soouv_date of this whp_sites_soouv
	 */
	public void setSoouv_date(Date soouv_date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_soouv whp_sites_soouv);

	public int hashCode();

	public CacheModel<whp_sites_soouv> toCacheModel();

	public whp_sites_soouv toEscapedModel();

	public String toString();

	public String toXmlString();
}