/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites_budget service. Represents a row in the &quot;whp_whp_sites_budget&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_budgetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_budgetImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_budget
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_budgetImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_budgetModelImpl
 * @generated
 */
public interface whp_sites_budgetModel extends BaseModel<whp_sites_budget> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_budget model instance should use the {@link whp_sites_budget} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_budget.
	 *
	 * @return the primary key of this whp_sites_budget
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_budget.
	 *
	 * @param primaryKey the primary key of this whp_sites_budget
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_budget_id of this whp_sites_budget.
	 *
	 * @return the whp_sites_budget_id of this whp_sites_budget
	 */
	public long getWhp_sites_budget_id();

	/**
	 * Sets the whp_sites_budget_id of this whp_sites_budget.
	 *
	 * @param whp_sites_budget_id the whp_sites_budget_id of this whp_sites_budget
	 */
	public void setWhp_sites_budget_id(long whp_sites_budget_id);

	/**
	 * Returns the site_id of this whp_sites_budget.
	 *
	 * @return the site_id of this whp_sites_budget
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_budget.
	 *
	 * @param site_id the site_id of this whp_sites_budget
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the currency_local of this whp_sites_budget.
	 *
	 * @return the currency_local of this whp_sites_budget
	 */
	public double getCurrency_local();

	/**
	 * Sets the currency_local of this whp_sites_budget.
	 *
	 * @param currency_local the currency_local of this whp_sites_budget
	 */
	public void setCurrency_local(double currency_local);

	/**
	 * Returns the currency of this whp_sites_budget.
	 *
	 * @return the currency of this whp_sites_budget
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this whp_sites_budget.
	 *
	 * @param currency the currency of this whp_sites_budget
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the currency_usd of this whp_sites_budget.
	 *
	 * @return the currency_usd of this whp_sites_budget
	 */
	public double getCurrency_usd();

	/**
	 * Sets the currency_usd of this whp_sites_budget.
	 *
	 * @param currency_usd the currency_usd of this whp_sites_budget
	 */
	public void setCurrency_usd(double currency_usd);

	/**
	 * Returns the date of this whp_sites_budget.
	 *
	 * @return the date of this whp_sites_budget
	 */
	public Date getDate();

	/**
	 * Sets the date of this whp_sites_budget.
	 *
	 * @param date the date of this whp_sites_budget
	 */
	public void setDate(Date date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_budget whp_sites_budget);

	public int hashCode();

	public CacheModel<whp_sites_budget> toCacheModel();

	public whp_sites_budget toEscapedModel();

	public String toString();

	public String toXmlString();
}