/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites_dsocr service. Represents a row in the &quot;whp_whp_sites_dsocr&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_dsocrModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_dsocrImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_dsocr
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_dsocrImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_dsocrModelImpl
 * @generated
 */
public interface whp_sites_dsocrModel extends BaseModel<whp_sites_dsocr> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_dsocr model instance should use the {@link whp_sites_dsocr} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_dsocr.
	 *
	 * @return the primary key of this whp_sites_dsocr
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_dsocr.
	 *
	 * @param primaryKey the primary key of this whp_sites_dsocr
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_dsocr_id of this whp_sites_dsocr.
	 *
	 * @return the whp_sites_dsocr_id of this whp_sites_dsocr
	 */
	public long getWhp_sites_dsocr_id();

	/**
	 * Sets the whp_sites_dsocr_id of this whp_sites_dsocr.
	 *
	 * @param whp_sites_dsocr_id the whp_sites_dsocr_id of this whp_sites_dsocr
	 */
	public void setWhp_sites_dsocr_id(long whp_sites_dsocr_id);

	/**
	 * Returns the site_id of this whp_sites_dsocr.
	 *
	 * @return the site_id of this whp_sites_dsocr
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_dsocr.
	 *
	 * @param site_id the site_id of this whp_sites_dsocr
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the state_description of this whp_sites_dsocr.
	 *
	 * @return the state_description of this whp_sites_dsocr
	 */
	@AutoEscape
	public String getState_description();

	/**
	 * Sets the state_description of this whp_sites_dsocr.
	 *
	 * @param state_description the state_description of this whp_sites_dsocr
	 */
	public void setState_description(String state_description);

	/**
	 * Returns the dsocr_date of this whp_sites_dsocr.
	 *
	 * @return the dsocr_date of this whp_sites_dsocr
	 */
	public Date getDsocr_date();

	/**
	 * Sets the dsocr_date of this whp_sites_dsocr.
	 *
	 * @param dsocr_date the dsocr_date of this whp_sites_dsocr
	 */
	public void setDsocr_date(Date dsocr_date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_dsocr whp_sites_dsocr);

	public int hashCode();

	public CacheModel<whp_sites_dsocr> toCacheModel();

	public whp_sites_dsocr toEscapedModel();

	public String toString();

	public String toXmlString();
}