/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites_visitors service. Represents a row in the &quot;whp_whp_sites_visitors&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_visitorsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_visitorsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_visitors
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_visitorsImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_visitorsModelImpl
 * @generated
 */
public interface whp_sites_visitorsModel extends BaseModel<whp_sites_visitors> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_visitors model instance should use the {@link whp_sites_visitors} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_visitors.
	 *
	 * @return the primary key of this whp_sites_visitors
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_visitors.
	 *
	 * @param primaryKey the primary key of this whp_sites_visitors
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_visitors_id of this whp_sites_visitors.
	 *
	 * @return the whp_sites_visitors_id of this whp_sites_visitors
	 */
	public long getWhp_sites_visitors_id();

	/**
	 * Sets the whp_sites_visitors_id of this whp_sites_visitors.
	 *
	 * @param whp_sites_visitors_id the whp_sites_visitors_id of this whp_sites_visitors
	 */
	public void setWhp_sites_visitors_id(long whp_sites_visitors_id);

	/**
	 * Returns the site_id of this whp_sites_visitors.
	 *
	 * @return the site_id of this whp_sites_visitors
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_visitors.
	 *
	 * @param site_id the site_id of this whp_sites_visitors
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the visitor_count of this whp_sites_visitors.
	 *
	 * @return the visitor_count of this whp_sites_visitors
	 */
	public long getVisitor_count();

	/**
	 * Sets the visitor_count of this whp_sites_visitors.
	 *
	 * @param visitor_count the visitor_count of this whp_sites_visitors
	 */
	public void setVisitor_count(long visitor_count);

	/**
	 * Returns the record_date of this whp_sites_visitors.
	 *
	 * @return the record_date of this whp_sites_visitors
	 */
	public Date getRecord_date();

	/**
	 * Sets the record_date of this whp_sites_visitors.
	 *
	 * @param record_date the record_date of this whp_sites_visitors
	 */
	public void setRecord_date(Date record_date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_visitors whp_sites_visitors);

	public int hashCode();

	public CacheModel<whp_sites_visitors> toCacheModel();

	public whp_sites_visitors toEscapedModel();

	public String toString();

	public String toXmlString();
}