/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites_inscription_date service. Represents a row in the &quot;whp_whp_sites_inscription_date&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_inscription_dateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_inscription_dateImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_inscription_date
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_inscription_dateImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_inscription_dateModelImpl
 * @generated
 */
public interface whp_sites_inscription_dateModel extends BaseModel<whp_sites_inscription_date> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_inscription_date model instance should use the {@link whp_sites_inscription_date} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_inscription_date.
	 *
	 * @return the primary key of this whp_sites_inscription_date
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_inscription_date.
	 *
	 * @param primaryKey the primary key of this whp_sites_inscription_date
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_inscription_date_id of this whp_sites_inscription_date.
	 *
	 * @return the whp_sites_inscription_date_id of this whp_sites_inscription_date
	 */
	public long getWhp_sites_inscription_date_id();

	/**
	 * Sets the whp_sites_inscription_date_id of this whp_sites_inscription_date.
	 *
	 * @param whp_sites_inscription_date_id the whp_sites_inscription_date_id of this whp_sites_inscription_date
	 */
	public void setWhp_sites_inscription_date_id(
		long whp_sites_inscription_date_id);

	/**
	 * Returns the site_id of this whp_sites_inscription_date.
	 *
	 * @return the site_id of this whp_sites_inscription_date
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_inscription_date.
	 *
	 * @param site_id the site_id of this whp_sites_inscription_date
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the inscription_type_id of this whp_sites_inscription_date.
	 *
	 * @return the inscription_type_id of this whp_sites_inscription_date
	 */
	public int getInscription_type_id();

	/**
	 * Sets the inscription_type_id of this whp_sites_inscription_date.
	 *
	 * @param inscription_type_id the inscription_type_id of this whp_sites_inscription_date
	 */
	public void setInscription_type_id(int inscription_type_id);

	/**
	 * Returns the reference_no of this whp_sites_inscription_date.
	 *
	 * @return the reference_no of this whp_sites_inscription_date
	 */
	@AutoEscape
	public String getReference_no();

	/**
	 * Sets the reference_no of this whp_sites_inscription_date.
	 *
	 * @param reference_no the reference_no of this whp_sites_inscription_date
	 */
	public void setReference_no(String reference_no);

	/**
	 * Returns the inscription_date of this whp_sites_inscription_date.
	 *
	 * @return the inscription_date of this whp_sites_inscription_date
	 */
	public Date getInscription_date();

	/**
	 * Sets the inscription_date of this whp_sites_inscription_date.
	 *
	 * @param inscription_date the inscription_date of this whp_sites_inscription_date
	 */
	public void setInscription_date(Date inscription_date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_inscription_date whp_sites_inscription_date);

	public int hashCode();

	public CacheModel<whp_sites_inscription_date> toCacheModel();

	public whp_sites_inscription_date toEscapedModel();

	public String toString();

	public String toXmlString();
}