/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites_iucn_recommendation service. Represents a row in the &quot;whp_whp_sites_iucn_recommendation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_iucn_recommendationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_iucn_recommendationImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_iucn_recommendation
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_iucn_recommendationImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_iucn_recommendationModelImpl
 * @generated
 */
public interface whp_sites_iucn_recommendationModel extends BaseModel<whp_sites_iucn_recommendation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_iucn_recommendation model instance should use the {@link whp_sites_iucn_recommendation} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_iucn_recommendation.
	 *
	 * @return the primary key of this whp_sites_iucn_recommendation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_iucn_recommendation.
	 *
	 * @param primaryKey the primary key of this whp_sites_iucn_recommendation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_iucn_recommendation_id of this whp_sites_iucn_recommendation.
	 *
	 * @return the whp_sites_iucn_recommendation_id of this whp_sites_iucn_recommendation
	 */
	public long getWhp_sites_iucn_recommendation_id();

	/**
	 * Sets the whp_sites_iucn_recommendation_id of this whp_sites_iucn_recommendation.
	 *
	 * @param whp_sites_iucn_recommendation_id the whp_sites_iucn_recommendation_id of this whp_sites_iucn_recommendation
	 */
	public void setWhp_sites_iucn_recommendation_id(
		long whp_sites_iucn_recommendation_id);

	/**
	 * Returns the site_id of this whp_sites_iucn_recommendation.
	 *
	 * @return the site_id of this whp_sites_iucn_recommendation
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_iucn_recommendation.
	 *
	 * @param site_id the site_id of this whp_sites_iucn_recommendation
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the recommendation_type of this whp_sites_iucn_recommendation.
	 *
	 * @return the recommendation_type of this whp_sites_iucn_recommendation
	 */
	public int getRecommendation_type();

	/**
	 * Sets the recommendation_type of this whp_sites_iucn_recommendation.
	 *
	 * @param recommendation_type the recommendation_type of this whp_sites_iucn_recommendation
	 */
	public void setRecommendation_type(int recommendation_type);

	/**
	 * Returns the rec_date of this whp_sites_iucn_recommendation.
	 *
	 * @return the rec_date of this whp_sites_iucn_recommendation
	 */
	public Date getRec_date();

	/**
	 * Sets the rec_date of this whp_sites_iucn_recommendation.
	 *
	 * @param rec_date the rec_date of this whp_sites_iucn_recommendation
	 */
	public void setRec_date(Date rec_date);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(
		whp_sites_iucn_recommendation whp_sites_iucn_recommendation);

	public int hashCode();

	public CacheModel<whp_sites_iucn_recommendation> toCacheModel();

	public whp_sites_iucn_recommendation toEscapedModel();

	public String toString();

	public String toXmlString();
}