/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the whp_sites_flagship_species service. Represents a row in the &quot;whp_whp_sites_flagship_species&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sites_flagship_speciesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sites_flagship_speciesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_flagship_species
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_flagship_speciesImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sites_flagship_speciesModelImpl
 * @generated
 */
public interface whp_sites_flagship_speciesModel extends BaseModel<whp_sites_flagship_species> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites_flagship_species model instance should use the {@link whp_sites_flagship_species} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites_flagship_species.
	 *
	 * @return the primary key of this whp_sites_flagship_species
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites_flagship_species.
	 *
	 * @param primaryKey the primary key of this whp_sites_flagship_species
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the whp_sites_flagship_species_id of this whp_sites_flagship_species.
	 *
	 * @return the whp_sites_flagship_species_id of this whp_sites_flagship_species
	 */
	public long getWhp_sites_flagship_species_id();

	/**
	 * Sets the whp_sites_flagship_species_id of this whp_sites_flagship_species.
	 *
	 * @param whp_sites_flagship_species_id the whp_sites_flagship_species_id of this whp_sites_flagship_species
	 */
	public void setWhp_sites_flagship_species_id(
		long whp_sites_flagship_species_id);

	/**
	 * Returns the site_id of this whp_sites_flagship_species.
	 *
	 * @return the site_id of this whp_sites_flagship_species
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites_flagship_species.
	 *
	 * @param site_id the site_id of this whp_sites_flagship_species
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the flagship_species_id of this whp_sites_flagship_species.
	 *
	 * @return the flagship_species_id of this whp_sites_flagship_species
	 */
	public int getFlagship_species_id();

	/**
	 * Sets the flagship_species_id of this whp_sites_flagship_species.
	 *
	 * @param flagship_species_id the flagship_species_id of this whp_sites_flagship_species
	 */
	public void setFlagship_species_id(int flagship_species_id);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites_flagship_species whp_sites_flagship_species);

	public int hashCode();

	public CacheModel<whp_sites_flagship_species> toCacheModel();

	public whp_sites_flagship_species toEscapedModel();

	public String toString();

	public String toXmlString();
}