/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the whp_sites service. Represents a row in the &quot;whp_whp_sites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.iucn.whp.dbservice.model.impl.whp_sitesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.iucn.whp.dbservice.model.impl.whp_sitesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites
 * @see com.iucn.whp.dbservice.model.impl.whp_sitesImpl
 * @see com.iucn.whp.dbservice.model.impl.whp_sitesModelImpl
 * @generated
 */
public interface whp_sitesModel extends BaseModel<whp_sites> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a whp_sites model instance should use the {@link whp_sites} interface instead.
	 */

	/**
	 * Returns the primary key of this whp_sites.
	 *
	 * @return the primary key of this whp_sites
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this whp_sites.
	 *
	 * @param primaryKey the primary key of this whp_sites
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the site_id of this whp_sites.
	 *
	 * @return the site_id of this whp_sites
	 */
	public long getSite_id();

	/**
	 * Sets the site_id of this whp_sites.
	 *
	 * @param site_id the site_id of this whp_sites
	 */
	public void setSite_id(long site_id);

	/**
	 * Returns the group ID of this whp_sites.
	 *
	 * @return the group ID of this whp_sites
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this whp_sites.
	 *
	 * @param groupId the group ID of this whp_sites
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this whp_sites.
	 *
	 * @return the company ID of this whp_sites
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this whp_sites.
	 *
	 * @param companyId the company ID of this whp_sites
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the wdpa_id of this whp_sites.
	 *
	 * @return the wdpa_id of this whp_sites
	 */
	public long getWdpa_id();

	/**
	 * Sets the wdpa_id of this whp_sites.
	 *
	 * @param wdpa_id the wdpa_id of this whp_sites
	 */
	public void setWdpa_id(long wdpa_id);

	/**
	 * Returns the unesco_id of this whp_sites.
	 *
	 * @return the unesco_id of this whp_sites
	 */
	public long getUnesco_id();

	/**
	 * Sets the unesco_id of this whp_sites.
	 *
	 * @param unesco_id the unesco_id of this whp_sites
	 */
	public void setUnesco_id(long unesco_id);

	/**
	 * Returns the name_en of this whp_sites.
	 *
	 * @return the name_en of this whp_sites
	 */
	@AutoEscape
	public String getName_en();

	/**
	 * Sets the name_en of this whp_sites.
	 *
	 * @param name_en the name_en of this whp_sites
	 */
	public void setName_en(String name_en);

	/**
	 * Returns the name_fr of this whp_sites.
	 *
	 * @return the name_fr of this whp_sites
	 */
	@AutoEscape
	public String getName_fr();

	/**
	 * Sets the name_fr of this whp_sites.
	 *
	 * @param name_fr the name_fr of this whp_sites
	 */
	public void setName_fr(String name_fr);

	/**
	 * Returns the transboundary of this whp_sites.
	 *
	 * @return the transboundary of this whp_sites
	 */
	public boolean getTransboundary();

	/**
	 * Returns <code>true</code> if this whp_sites is transboundary.
	 *
	 * @return <code>true</code> if this whp_sites is transboundary; <code>false</code> otherwise
	 */
	public boolean isTransboundary();

	/**
	 * Sets whether this whp_sites is transboundary.
	 *
	 * @param transboundary the transboundary of this whp_sites
	 */
	public void setTransboundary(boolean transboundary);

	/**
	 * Returns the inscription_date of this whp_sites.
	 *
	 * @return the inscription_date of this whp_sites
	 */
	public Date getInscription_date();

	/**
	 * Sets the inscription_date of this whp_sites.
	 *
	 * @param inscription_date the inscription_date of this whp_sites
	 */
	public void setInscription_date(Date inscription_date);

	/**
	 * Returns the mixed_site of this whp_sites.
	 *
	 * @return the mixed_site of this whp_sites
	 */
	public boolean getMixed_site();

	/**
	 * Returns <code>true</code> if this whp_sites is mixed_site.
	 *
	 * @return <code>true</code> if this whp_sites is mixed_site; <code>false</code> otherwise
	 */
	public boolean isMixed_site();

	/**
	 * Sets whether this whp_sites is mixed_site.
	 *
	 * @param mixed_site the mixed_site of this whp_sites
	 */
	public void setMixed_site(boolean mixed_site);

	/**
	 * Returns the cultural_landscape of this whp_sites.
	 *
	 * @return the cultural_landscape of this whp_sites
	 */
	public boolean getCultural_landscape();

	/**
	 * Returns <code>true</code> if this whp_sites is cultural_landscape.
	 *
	 * @return <code>true</code> if this whp_sites is cultural_landscape; <code>false</code> otherwise
	 */
	public boolean isCultural_landscape();

	/**
	 * Sets whether this whp_sites is cultural_landscape.
	 *
	 * @param cultural_landscape the cultural_landscape of this whp_sites
	 */
	public void setCultural_landscape(boolean cultural_landscape);

	/**
	 * Returns the danger_list of this whp_sites.
	 *
	 * @return the danger_list of this whp_sites
	 */
	public boolean getDanger_list();

	/**
	 * Returns <code>true</code> if this whp_sites is danger_list.
	 *
	 * @return <code>true</code> if this whp_sites is danger_list; <code>false</code> otherwise
	 */
	public boolean isDanger_list();

	/**
	 * Sets whether this whp_sites is danger_list.
	 *
	 * @param danger_list the danger_list of this whp_sites
	 */
	public void setDanger_list(boolean danger_list);

	/**
	 * Returns the area of this whp_sites.
	 *
	 * @return the area of this whp_sites
	 */
	public double getArea();

	/**
	 * Sets the area of this whp_sites.
	 *
	 * @param area the area of this whp_sites
	 */
	public void setArea(double area);

	/**
	 * Returns the buffer_zone of this whp_sites.
	 *
	 * @return the buffer_zone of this whp_sites
	 */
	public boolean getBuffer_zone();

	/**
	 * Returns <code>true</code> if this whp_sites is buffer_zone.
	 *
	 * @return <code>true</code> if this whp_sites is buffer_zone; <code>false</code> otherwise
	 */
	public boolean isBuffer_zone();

	/**
	 * Sets whether this whp_sites is buffer_zone.
	 *
	 * @param buffer_zone the buffer_zone of this whp_sites
	 */
	public void setBuffer_zone(boolean buffer_zone);

	/**
	 * Returns the buffer_zone_area of this whp_sites.
	 *
	 * @return the buffer_zone_area of this whp_sites
	 */
	public double getBuffer_zone_area();

	/**
	 * Sets the buffer_zone_area of this whp_sites.
	 *
	 * @param buffer_zone_area the buffer_zone_area of this whp_sites
	 */
	public void setBuffer_zone_area(double buffer_zone_area);

	/**
	 * Returns the boundary_modification of this whp_sites.
	 *
	 * @return the boundary_modification of this whp_sites
	 */
	public boolean getBoundary_modification();

	/**
	 * Returns <code>true</code> if this whp_sites is boundary_modification.
	 *
	 * @return <code>true</code> if this whp_sites is boundary_modification; <code>false</code> otherwise
	 */
	public boolean isBoundary_modification();

	/**
	 * Sets whether this whp_sites is boundary_modification.
	 *
	 * @param boundary_modification the boundary_modification of this whp_sites
	 */
	public void setBoundary_modification(boolean boundary_modification);

	/**
	 * Returns the serial of this whp_sites.
	 *
	 * @return the serial of this whp_sites
	 */
	public boolean getSerial();

	/**
	 * Returns <code>true</code> if this whp_sites is serial.
	 *
	 * @return <code>true</code> if this whp_sites is serial; <code>false</code> otherwise
	 */
	public boolean isSerial();

	/**
	 * Sets whether this whp_sites is serial.
	 *
	 * @param serial the serial of this whp_sites
	 */
	public void setSerial(boolean serial);

	/**
	 * Returns the missions of this whp_sites.
	 *
	 * @return the missions of this whp_sites
	 */
	public boolean getMissions();

	/**
	 * Returns <code>true</code> if this whp_sites is missions.
	 *
	 * @return <code>true</code> if this whp_sites is missions; <code>false</code> otherwise
	 */
	public boolean isMissions();

	/**
	 * Sets whether this whp_sites is missions.
	 *
	 * @param missions the missions of this whp_sites
	 */
	public void setMissions(boolean missions);

	/**
	 * Returns the soc_reports of this whp_sites.
	 *
	 * @return the soc_reports of this whp_sites
	 */
	public boolean getSoc_reports();

	/**
	 * Returns <code>true</code> if this whp_sites is soc_reports.
	 *
	 * @return <code>true</code> if this whp_sites is soc_reports; <code>false</code> otherwise
	 */
	public boolean isSoc_reports();

	/**
	 * Sets whether this whp_sites is soc_reports.
	 *
	 * @param soc_reports the soc_reports of this whp_sites
	 */
	public void setSoc_reports(boolean soc_reports);

	/**
	 * Returns the soouv of this whp_sites.
	 *
	 * @return the soouv of this whp_sites
	 */
	public boolean getSoouv();

	/**
	 * Returns <code>true</code> if this whp_sites is soouv.
	 *
	 * @return <code>true</code> if this whp_sites is soouv; <code>false</code> otherwise
	 */
	public boolean isSoouv();

	/**
	 * Sets whether this whp_sites is soouv.
	 *
	 * @param soouv the soouv of this whp_sites
	 */
	public void setSoouv(boolean soouv);

	/**
	 * Returns the dsocr of this whp_sites.
	 *
	 * @return the dsocr of this whp_sites
	 */
	public boolean getDsocr();

	/**
	 * Returns <code>true</code> if this whp_sites is dsocr.
	 *
	 * @return <code>true</code> if this whp_sites is dsocr; <code>false</code> otherwise
	 */
	public boolean isDsocr();

	/**
	 * Sets whether this whp_sites is dsocr.
	 *
	 * @param dsocr the dsocr of this whp_sites
	 */
	public void setDsocr(boolean dsocr);

	/**
	 * Returns the management_plan of this whp_sites.
	 *
	 * @return the management_plan of this whp_sites
	 */
	public boolean getManagement_plan();

	/**
	 * Returns <code>true</code> if this whp_sites is management_plan.
	 *
	 * @return <code>true</code> if this whp_sites is management_plan; <code>false</code> otherwise
	 */
	public boolean isManagement_plan();

	/**
	 * Sets whether this whp_sites is management_plan.
	 *
	 * @param management_plan the management_plan of this whp_sites
	 */
	public void setManagement_plan(boolean management_plan);

	/**
	 * Returns the mee of this whp_sites.
	 *
	 * @return the mee of this whp_sites
	 */
	public boolean getMee();

	/**
	 * Returns <code>true</code> if this whp_sites is mee.
	 *
	 * @return <code>true</code> if this whp_sites is mee; <code>false</code> otherwise
	 */
	public boolean isMee();

	/**
	 * Sets whether this whp_sites is mee.
	 *
	 * @param mee the mee of this whp_sites
	 */
	public void setMee(boolean mee);

	/**
	 * Returns the staff of this whp_sites.
	 *
	 * @return the staff of this whp_sites
	 */
	public long getStaff();

	/**
	 * Sets the staff of this whp_sites.
	 *
	 * @param staff the staff of this whp_sites
	 */
	public void setStaff(long staff);

	/**
	 * Returns the staff_update_date of this whp_sites.
	 *
	 * @return the staff_update_date of this whp_sites
	 */
	public Date getStaff_update_date();

	/**
	 * Sets the staff_update_date of this whp_sites.
	 *
	 * @param staff_update_date the staff_update_date of this whp_sites
	 */
	public void setStaff_update_date(Date staff_update_date);

	/**
	 * Returns the indigenous_communities of this whp_sites.
	 *
	 * @return the indigenous_communities of this whp_sites
	 */
	public boolean getIndigenous_communities();

	/**
	 * Returns <code>true</code> if this whp_sites is indigenous_communities.
	 *
	 * @return <code>true</code> if this whp_sites is indigenous_communities; <code>false</code> otherwise
	 */
	public boolean isIndigenous_communities();

	/**
	 * Sets whether this whp_sites is indigenous_communities.
	 *
	 * @param indigenous_communities the indigenous_communities of this whp_sites
	 */
	public void setIndigenous_communities(boolean indigenous_communities);

	/**
	 * Returns the population of this whp_sites.
	 *
	 * @return the population of this whp_sites
	 */
	public long getPopulation();

	/**
	 * Sets the population of this whp_sites.
	 *
	 * @param population the population of this whp_sites
	 */
	public void setPopulation(long population);

	/**
	 * Returns the last_updated of this whp_sites.
	 *
	 * @return the last_updated of this whp_sites
	 */
	public Date getLast_updated();

	/**
	 * Sets the last_updated of this whp_sites.
	 *
	 * @param last_updated the last_updated of this whp_sites
	 */
	public void setLast_updated(Date last_updated);

	/**
	 * Returns the creation_date of this whp_sites.
	 *
	 * @return the creation_date of this whp_sites
	 */
	public Date getCreation_date();

	/**
	 * Sets the creation_date of this whp_sites.
	 *
	 * @param creation_date the creation_date of this whp_sites
	 */
	public void setCreation_date(Date creation_date);

	/**
	 * Returns the created_by of this whp_sites.
	 *
	 * @return the created_by of this whp_sites
	 */
	public long getCreated_by();

	/**
	 * Sets the created_by of this whp_sites.
	 *
	 * @param created_by the created_by of this whp_sites
	 */
	public void setCreated_by(long created_by);

	/**
	 * Returns the updated_by of this whp_sites.
	 *
	 * @return the updated_by of this whp_sites
	 */
	public long getUpdated_by();

	/**
	 * Sets the updated_by of this whp_sites.
	 *
	 * @param updated_by the updated_by of this whp_sites
	 */
	public void setUpdated_by(long updated_by);

	/**
	 * Returns the active of this whp_sites.
	 *
	 * @return the active of this whp_sites
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this whp_sites is active.
	 *
	 * @return <code>true</code> if this whp_sites is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this whp_sites is active.
	 *
	 * @param active the active of this whp_sites
	 */
	public void setActive(boolean active);

	/**
	 * Returns the thumbnailid of this whp_sites.
	 *
	 * @return the thumbnailid of this whp_sites
	 */
	public long getThumbnailid();

	/**
	 * Sets the thumbnailid of this whp_sites.
	 *
	 * @param thumbnailid the thumbnailid of this whp_sites
	 */
	public void setThumbnailid(long thumbnailid);

	/**
	 * Returns the thumbnailid_small of this whp_sites.
	 *
	 * @return the thumbnailid_small of this whp_sites
	 */
	public long getThumbnailid_small();

	/**
	 * Sets the thumbnailid_small of this whp_sites.
	 *
	 * @param thumbnailid_small the thumbnailid_small of this whp_sites
	 */
	public void setThumbnailid_small(long thumbnailid_small);

	/**
	 * Returns the description of this whp_sites.
	 *
	 * @return the description of this whp_sites
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this whp_sites.
	 *
	 * @param description the description of this whp_sites
	 */
	public void setDescription(String description);

	/**
	 * Returns the information_updating of this whp_sites.
	 *
	 * @return the information_updating of this whp_sites
	 */
	public boolean getInformation_updating();

	/**
	 * Returns <code>true</code> if this whp_sites is information_updating.
	 *
	 * @return <code>true</code> if this whp_sites is information_updating; <code>false</code> otherwise
	 */
	public boolean isInformation_updating();

	/**
	 * Sets whether this whp_sites is information_updating.
	 *
	 * @param information_updating the information_updating of this whp_sites
	 */
	public void setInformation_updating(boolean information_updating);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(whp_sites whp_sites);

	public int hashCode();

	public CacheModel<whp_sites> toCacheModel();

	public whp_sites toEscapedModel();

	public String toString();

	public String toXmlString();
}