/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.assessment_lang_version;
import com.iucn.whp.dbservice.model.assessment_lang_versionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the assessment_lang_version service. Represents a row in the &quot;whp_assessment_lang_version&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.assessment_lang_versionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link assessment_lang_versionImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_lang_versionImpl
 * @see com.iucn.whp.dbservice.model.assessment_lang_version
 * @see com.iucn.whp.dbservice.model.assessment_lang_versionModel
 * @generated
 */
public class assessment_lang_versionModelImpl extends BaseModelImpl<assessment_lang_version>
	implements assessment_lang_versionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assessment_lang_version model instance should use the {@link com.iucn.whp.dbservice.model.assessment_lang_version} interface instead.
	 */
	public static final String TABLE_NAME = "whp_assessment_lang_version";
	public static final Object[][] TABLE_COLUMNS = {
			{ "lang_ver_id", Types.BIGINT },
			{ "assessmentid", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "languageid", Types.BIGINT },
			{ "published", Types.BOOLEAN },
			{ "published_date", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_assessment_lang_version (lang_ver_id LONG not null primary key,assessmentid LONG,assessment_version_id LONG,languageid LONG,published BOOLEAN,published_date DATE null)";
	public static final String TABLE_SQL_DROP = "drop table whp_assessment_lang_version";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.assessment_lang_version"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.assessment_lang_version"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.assessment_lang_version"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static long ASSESSMENTID_COLUMN_BITMASK = 2L;
	public static long LANGUAGEID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.assessment_lang_version"));

	public assessment_lang_versionModelImpl() {
	}

	public long getPrimaryKey() {
		return _lang_ver_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setLang_ver_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_lang_ver_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return assessment_lang_version.class;
	}

	public String getModelClassName() {
		return assessment_lang_version.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("lang_ver_id", getLang_ver_id());
		attributes.put("assessmentid", getAssessmentid());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("languageid", getLanguageid());
		attributes.put("published", getPublished());
		attributes.put("published_date", getPublished_date());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long lang_ver_id = (Long)attributes.get("lang_ver_id");

		if (lang_ver_id != null) {
			setLang_ver_id(lang_ver_id);
		}

		Long assessmentid = (Long)attributes.get("assessmentid");

		if (assessmentid != null) {
			setAssessmentid(assessmentid);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		Long languageid = (Long)attributes.get("languageid");

		if (languageid != null) {
			setLanguageid(languageid);
		}

		Boolean published = (Boolean)attributes.get("published");

		if (published != null) {
			setPublished(published);
		}

		Date published_date = (Date)attributes.get("published_date");

		if (published_date != null) {
			setPublished_date(published_date);
		}
	}

	public long getLang_ver_id() {
		return _lang_ver_id;
	}

	public void setLang_ver_id(long lang_ver_id) {
		_lang_ver_id = lang_ver_id;
	}

	public long getAssessmentid() {
		return _assessmentid;
	}

	public void setAssessmentid(long assessmentid) {
		_columnBitmask |= ASSESSMENTID_COLUMN_BITMASK;

		if (!_setOriginalAssessmentid) {
			_setOriginalAssessmentid = true;

			_originalAssessmentid = _assessmentid;
		}

		_assessmentid = assessmentid;
	}

	public long getOriginalAssessmentid() {
		return _originalAssessmentid;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public long getLanguageid() {
		return _languageid;
	}

	public void setLanguageid(long languageid) {
		_columnBitmask |= LANGUAGEID_COLUMN_BITMASK;

		if (!_setOriginalLanguageid) {
			_setOriginalLanguageid = true;

			_originalLanguageid = _languageid;
		}

		_languageid = languageid;
	}

	public long getOriginalLanguageid() {
		return _originalLanguageid;
	}

	public boolean getPublished() {
		return _published;
	}

	public boolean isPublished() {
		return _published;
	}

	public void setPublished(boolean published) {
		_published = published;
	}

	public Date getPublished_date() {
		return _published_date;
	}

	public void setPublished_date(Date published_date) {
		_published_date = published_date;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			assessment_lang_version.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public assessment_lang_version toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (assessment_lang_version)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		assessment_lang_versionImpl assessment_lang_versionImpl = new assessment_lang_versionImpl();

		assessment_lang_versionImpl.setLang_ver_id(getLang_ver_id());
		assessment_lang_versionImpl.setAssessmentid(getAssessmentid());
		assessment_lang_versionImpl.setAssessment_version_id(getAssessment_version_id());
		assessment_lang_versionImpl.setLanguageid(getLanguageid());
		assessment_lang_versionImpl.setPublished(getPublished());
		assessment_lang_versionImpl.setPublished_date(getPublished_date());

		assessment_lang_versionImpl.resetOriginalValues();

		return assessment_lang_versionImpl;
	}

	public int compareTo(assessment_lang_version assessment_lang_version) {
		long primaryKey = assessment_lang_version.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		assessment_lang_version assessment_lang_version = null;

		try {
			assessment_lang_version = (assessment_lang_version)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = assessment_lang_version.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		assessment_lang_versionModelImpl assessment_lang_versionModelImpl = this;

		assessment_lang_versionModelImpl._originalAssessmentid = assessment_lang_versionModelImpl._assessmentid;

		assessment_lang_versionModelImpl._setOriginalAssessmentid = false;

		assessment_lang_versionModelImpl._originalAssessment_version_id = assessment_lang_versionModelImpl._assessment_version_id;

		assessment_lang_versionModelImpl._setOriginalAssessment_version_id = false;

		assessment_lang_versionModelImpl._originalLanguageid = assessment_lang_versionModelImpl._languageid;

		assessment_lang_versionModelImpl._setOriginalLanguageid = false;

		assessment_lang_versionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<assessment_lang_version> toCacheModel() {
		assessment_lang_versionCacheModel assessment_lang_versionCacheModel = new assessment_lang_versionCacheModel();

		assessment_lang_versionCacheModel.lang_ver_id = getLang_ver_id();

		assessment_lang_versionCacheModel.assessmentid = getAssessmentid();

		assessment_lang_versionCacheModel.assessment_version_id = getAssessment_version_id();

		assessment_lang_versionCacheModel.languageid = getLanguageid();

		assessment_lang_versionCacheModel.published = getPublished();

		Date published_date = getPublished_date();

		if (published_date != null) {
			assessment_lang_versionCacheModel.published_date = published_date.getTime();
		}
		else {
			assessment_lang_versionCacheModel.published_date = Long.MIN_VALUE;
		}

		return assessment_lang_versionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{lang_ver_id=");
		sb.append(getLang_ver_id());
		sb.append(", assessmentid=");
		sb.append(getAssessmentid());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", languageid=");
		sb.append(getLanguageid());
		sb.append(", published=");
		sb.append(getPublished());
		sb.append(", published_date=");
		sb.append(getPublished_date());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.assessment_lang_version");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>lang_ver_id</column-name><column-value><![CDATA[");
		sb.append(getLang_ver_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessmentid</column-name><column-value><![CDATA[");
		sb.append(getAssessmentid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageid</column-name><column-value><![CDATA[");
		sb.append(getLanguageid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>published</column-name><column-value><![CDATA[");
		sb.append(getPublished());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>published_date</column-name><column-value><![CDATA[");
		sb.append(getPublished_date());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = assessment_lang_version.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			assessment_lang_version.class
		};
	private long _lang_ver_id;
	private long _assessmentid;
	private long _originalAssessmentid;
	private boolean _setOriginalAssessmentid;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private long _languageid;
	private long _originalLanguageid;
	private boolean _setOriginalLanguageid;
	private boolean _published;
	private Date _published_date;
	private long _columnBitmask;
	private assessment_lang_version _escapedModelProxy;
}