/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.assessing_threats_potential;
import com.iucn.whp.dbservice.service.assessing_threats_potentialLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the assessing_threats_potential service. Represents a row in the &quot;whp_assessing_threats_potential&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link assessing_threats_potentialImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessing_threats_potentialImpl
 * @see com.iucn.whp.dbservice.model.assessing_threats_potential
 * @generated
 */
public abstract class assessing_threats_potentialBaseImpl
	extends assessing_threats_potentialModelImpl
	implements assessing_threats_potential {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assessing_threats_potential model instance should use the {@link assessing_threats_potential} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			assessing_threats_potentialLocalServiceUtil.addassessing_threats_potential(this);
		}
		else {
			assessing_threats_potentialLocalServiceUtil.updateassessing_threats_potential(this);
		}
	}
}