/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.assessing_threats_current;
import com.iucn.whp.dbservice.service.assessing_threats_currentLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the assessing_threats_current service. Represents a row in the &quot;whp_assessing_threats_current&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link assessing_threats_currentImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessing_threats_currentImpl
 * @see com.iucn.whp.dbservice.model.assessing_threats_current
 * @generated
 */
public abstract class assessing_threats_currentBaseImpl
	extends assessing_threats_currentModelImpl
	implements assessing_threats_current {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assessing_threats_current model instance should use the {@link assessing_threats_current} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			assessing_threats_currentLocalServiceUtil.addassessing_threats_current(this);
		}
		else {
			assessing_threats_currentLocalServiceUtil.updateassessing_threats_current(this);
		}
	}
}