/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.assessment_whvalues;
import com.iucn.whp.dbservice.model.assessment_whvaluesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the assessment_whvalues service. Represents a row in the &quot;whp_assessment_whvalues&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.assessment_whvaluesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link assessment_whvaluesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_whvaluesImpl
 * @see com.iucn.whp.dbservice.model.assessment_whvalues
 * @see com.iucn.whp.dbservice.model.assessment_whvaluesModel
 * @generated
 */
public class assessment_whvaluesModelImpl extends BaseModelImpl<assessment_whvalues>
	implements assessment_whvaluesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assessment_whvalues model instance should use the {@link com.iucn.whp.dbservice.model.assessment_whvalues} interface instead.
	 */
	public static final String TABLE_NAME = "whp_assessment_whvalues";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whvalues_id", Types.BIGINT },
			{ "vn", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "values_", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_assessment_whvalues (whvalues_id LONG not null primary key,vn LONG,assessment_version_id LONG,values_ VARCHAR(200) null,description STRING null)";
	public static final String TABLE_SQL_DROP = "drop table whp_assessment_whvalues";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.assessment_whvalues"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.assessment_whvalues"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.assessment_whvalues"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.assessment_whvalues"));

	public assessment_whvaluesModelImpl() {
	}

	public long getPrimaryKey() {
		return _whvalues_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setWhvalues_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_whvalues_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return assessment_whvalues.class;
	}

	public String getModelClassName() {
		return assessment_whvalues.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whvalues_id", getWhvalues_id());
		attributes.put("vn", getVn());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("values", getValues());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long whvalues_id = (Long)attributes.get("whvalues_id");

		if (whvalues_id != null) {
			setWhvalues_id(whvalues_id);
		}

		Long vn = (Long)attributes.get("vn");

		if (vn != null) {
			setVn(vn);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		String values = (String)attributes.get("values");

		if (values != null) {
			setValues(values);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getWhvalues_id() {
		return _whvalues_id;
	}

	public void setWhvalues_id(long whvalues_id) {
		_whvalues_id = whvalues_id;
	}

	public long getVn() {
		return _vn;
	}

	public void setVn(long vn) {
		_vn = vn;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public String getValues() {
		if (_values == null) {
			return StringPool.BLANK;
		}
		else {
			return _values;
		}
	}

	public void setValues(String values) {
		_values = values;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			assessment_whvalues.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public assessment_whvalues toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (assessment_whvalues)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		assessment_whvaluesImpl assessment_whvaluesImpl = new assessment_whvaluesImpl();

		assessment_whvaluesImpl.setWhvalues_id(getWhvalues_id());
		assessment_whvaluesImpl.setVn(getVn());
		assessment_whvaluesImpl.setAssessment_version_id(getAssessment_version_id());
		assessment_whvaluesImpl.setValues(getValues());
		assessment_whvaluesImpl.setDescription(getDescription());

		assessment_whvaluesImpl.resetOriginalValues();

		return assessment_whvaluesImpl;
	}

	public int compareTo(assessment_whvalues assessment_whvalues) {
		long primaryKey = assessment_whvalues.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		assessment_whvalues assessment_whvalues = null;

		try {
			assessment_whvalues = (assessment_whvalues)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = assessment_whvalues.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		assessment_whvaluesModelImpl assessment_whvaluesModelImpl = this;

		assessment_whvaluesModelImpl._originalAssessment_version_id = assessment_whvaluesModelImpl._assessment_version_id;

		assessment_whvaluesModelImpl._setOriginalAssessment_version_id = false;

		assessment_whvaluesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<assessment_whvalues> toCacheModel() {
		assessment_whvaluesCacheModel assessment_whvaluesCacheModel = new assessment_whvaluesCacheModel();

		assessment_whvaluesCacheModel.whvalues_id = getWhvalues_id();

		assessment_whvaluesCacheModel.vn = getVn();

		assessment_whvaluesCacheModel.assessment_version_id = getAssessment_version_id();

		assessment_whvaluesCacheModel.values = getValues();

		String values = assessment_whvaluesCacheModel.values;

		if ((values != null) && (values.length() == 0)) {
			assessment_whvaluesCacheModel.values = null;
		}

		assessment_whvaluesCacheModel.description = getDescription();

		String description = assessment_whvaluesCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			assessment_whvaluesCacheModel.description = null;
		}

		return assessment_whvaluesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{whvalues_id=");
		sb.append(getWhvalues_id());
		sb.append(", vn=");
		sb.append(getVn());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", values=");
		sb.append(getValues());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.assessment_whvalues");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whvalues_id</column-name><column-value><![CDATA[");
		sb.append(getWhvalues_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vn</column-name><column-value><![CDATA[");
		sb.append(getVn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>values</column-name><column-value><![CDATA[");
		sb.append(getValues());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = assessment_whvalues.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			assessment_whvalues.class
		};
	private long _whvalues_id;
	private long _vn;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private String _values;
	private String _description;
	private long _columnBitmask;
	private assessment_whvalues _escapedModelProxy;
}