/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.assessment_validation;
import com.iucn.whp.dbservice.model.assessment_validationModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the assessment_validation service. Represents a row in the &quot;whp_assessment_validation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.assessment_validationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link assessment_validationImpl}.
 * </p>
 *
 * @author alok.sen
 * @see assessment_validationImpl
 * @see com.iucn.whp.dbservice.model.assessment_validation
 * @see com.iucn.whp.dbservice.model.assessment_validationModel
 * @generated
 */
public class assessment_validationModelImpl extends BaseModelImpl<assessment_validation>
	implements assessment_validationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assessment_validation model instance should use the {@link com.iucn.whp.dbservice.model.assessment_validation} interface instead.
	 */
	public static final String TABLE_NAME = "whp_assessment_validation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "assessment_ver_val_id", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "assessment_step", Types.BIGINT },
			{ "validation_complete", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_assessment_validation (assessment_ver_val_id LONG not null primary key,assessment_version_id LONG,assessment_step LONG,validation_complete BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table whp_assessment_validation";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.assessment_validation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.assessment_validation"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.assessment_validation"),
			true);
	public static long ASSESSMENT_STEP_COLUMN_BITMASK = 1L;
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.assessment_validation"));

	public assessment_validationModelImpl() {
	}

	public long getPrimaryKey() {
		return _assessment_ver_val_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setAssessment_ver_val_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_assessment_ver_val_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return assessment_validation.class;
	}

	public String getModelClassName() {
		return assessment_validation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("assessment_ver_val_id", getAssessment_ver_val_id());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("assessment_step", getAssessment_step());
		attributes.put("validation_complete", getValidation_complete());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long assessment_ver_val_id = (Long)attributes.get(
				"assessment_ver_val_id");

		if (assessment_ver_val_id != null) {
			setAssessment_ver_val_id(assessment_ver_val_id);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		Long assessment_step = (Long)attributes.get("assessment_step");

		if (assessment_step != null) {
			setAssessment_step(assessment_step);
		}

		Boolean validation_complete = (Boolean)attributes.get(
				"validation_complete");

		if (validation_complete != null) {
			setValidation_complete(validation_complete);
		}
	}

	public long getAssessment_ver_val_id() {
		return _assessment_ver_val_id;
	}

	public void setAssessment_ver_val_id(long assessment_ver_val_id) {
		_assessment_ver_val_id = assessment_ver_val_id;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public long getAssessment_step() {
		return _assessment_step;
	}

	public void setAssessment_step(long assessment_step) {
		_columnBitmask |= ASSESSMENT_STEP_COLUMN_BITMASK;

		if (!_setOriginalAssessment_step) {
			_setOriginalAssessment_step = true;

			_originalAssessment_step = _assessment_step;
		}

		_assessment_step = assessment_step;
	}

	public long getOriginalAssessment_step() {
		return _originalAssessment_step;
	}

	public boolean getValidation_complete() {
		return _validation_complete;
	}

	public boolean isValidation_complete() {
		return _validation_complete;
	}

	public void setValidation_complete(boolean validation_complete) {
		_validation_complete = validation_complete;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			assessment_validation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public assessment_validation toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (assessment_validation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		assessment_validationImpl assessment_validationImpl = new assessment_validationImpl();

		assessment_validationImpl.setAssessment_ver_val_id(getAssessment_ver_val_id());
		assessment_validationImpl.setAssessment_version_id(getAssessment_version_id());
		assessment_validationImpl.setAssessment_step(getAssessment_step());
		assessment_validationImpl.setValidation_complete(getValidation_complete());

		assessment_validationImpl.resetOriginalValues();

		return assessment_validationImpl;
	}

	public int compareTo(assessment_validation assessment_validation) {
		long primaryKey = assessment_validation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		assessment_validation assessment_validation = null;

		try {
			assessment_validation = (assessment_validation)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = assessment_validation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		assessment_validationModelImpl assessment_validationModelImpl = this;

		assessment_validationModelImpl._originalAssessment_version_id = assessment_validationModelImpl._assessment_version_id;

		assessment_validationModelImpl._setOriginalAssessment_version_id = false;

		assessment_validationModelImpl._originalAssessment_step = assessment_validationModelImpl._assessment_step;

		assessment_validationModelImpl._setOriginalAssessment_step = false;

		assessment_validationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<assessment_validation> toCacheModel() {
		assessment_validationCacheModel assessment_validationCacheModel = new assessment_validationCacheModel();

		assessment_validationCacheModel.assessment_ver_val_id = getAssessment_ver_val_id();

		assessment_validationCacheModel.assessment_version_id = getAssessment_version_id();

		assessment_validationCacheModel.assessment_step = getAssessment_step();

		assessment_validationCacheModel.validation_complete = getValidation_complete();

		return assessment_validationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{assessment_ver_val_id=");
		sb.append(getAssessment_ver_val_id());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", assessment_step=");
		sb.append(getAssessment_step());
		sb.append(", validation_complete=");
		sb.append(getValidation_complete());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.assessment_validation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>assessment_ver_val_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_ver_val_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_step</column-name><column-value><![CDATA[");
		sb.append(getAssessment_step());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>validation_complete</column-name><column-value><![CDATA[");
		sb.append(getValidation_complete());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = assessment_validation.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			assessment_validation.class
		};
	private long _assessment_ver_val_id;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private long _assessment_step;
	private long _originalAssessment_step;
	private boolean _setOriginalAssessment_step;
	private boolean _validation_complete;
	private long _columnBitmask;
	private assessment_validation _escapedModelProxy;
}