/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.benefits_summary;
import com.iucn.whp.dbservice.model.benefits_summaryModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the benefits_summary service. Represents a row in the &quot;whp_benefits_summary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.benefits_summaryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link benefits_summaryImpl}.
 * </p>
 *
 * @author alok.sen
 * @see benefits_summaryImpl
 * @see com.iucn.whp.dbservice.model.benefits_summary
 * @see com.iucn.whp.dbservice.model.benefits_summaryModel
 * @generated
 */
public class benefits_summaryModelImpl extends BaseModelImpl<benefits_summary>
	implements benefits_summaryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a benefits_summary model instance should use the {@link com.iucn.whp.dbservice.model.benefits_summary} interface instead.
	 */
	public static final String TABLE_NAME = "whp_benefits_summary";
	public static final Object[][] TABLE_COLUMNS = {
			{ "benefits_summary_id", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "summary", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_benefits_summary (benefits_summary_id LONG not null primary key,assessment_version_id LONG,summary STRING null)";
	public static final String TABLE_SQL_DROP = "drop table whp_benefits_summary";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.benefits_summary"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.benefits_summary"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.benefits_summary"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.benefits_summary"));

	public benefits_summaryModelImpl() {
	}

	public long getPrimaryKey() {
		return _benefits_summary_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setBenefits_summary_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_benefits_summary_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return benefits_summary.class;
	}

	public String getModelClassName() {
		return benefits_summary.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("benefits_summary_id", getBenefits_summary_id());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("summary", getSummary());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long benefits_summary_id = (Long)attributes.get("benefits_summary_id");

		if (benefits_summary_id != null) {
			setBenefits_summary_id(benefits_summary_id);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		String summary = (String)attributes.get("summary");

		if (summary != null) {
			setSummary(summary);
		}
	}

	public long getBenefits_summary_id() {
		return _benefits_summary_id;
	}

	public void setBenefits_summary_id(long benefits_summary_id) {
		_benefits_summary_id = benefits_summary_id;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public String getSummary() {
		if (_summary == null) {
			return StringPool.BLANK;
		}
		else {
			return _summary;
		}
	}

	public void setSummary(String summary) {
		_summary = summary;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			benefits_summary.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public benefits_summary toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (benefits_summary)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		benefits_summaryImpl benefits_summaryImpl = new benefits_summaryImpl();

		benefits_summaryImpl.setBenefits_summary_id(getBenefits_summary_id());
		benefits_summaryImpl.setAssessment_version_id(getAssessment_version_id());
		benefits_summaryImpl.setSummary(getSummary());

		benefits_summaryImpl.resetOriginalValues();

		return benefits_summaryImpl;
	}

	public int compareTo(benefits_summary benefits_summary) {
		long primaryKey = benefits_summary.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		benefits_summary benefits_summary = null;

		try {
			benefits_summary = (benefits_summary)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = benefits_summary.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		benefits_summaryModelImpl benefits_summaryModelImpl = this;

		benefits_summaryModelImpl._originalAssessment_version_id = benefits_summaryModelImpl._assessment_version_id;

		benefits_summaryModelImpl._setOriginalAssessment_version_id = false;

		benefits_summaryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<benefits_summary> toCacheModel() {
		benefits_summaryCacheModel benefits_summaryCacheModel = new benefits_summaryCacheModel();

		benefits_summaryCacheModel.benefits_summary_id = getBenefits_summary_id();

		benefits_summaryCacheModel.assessment_version_id = getAssessment_version_id();

		benefits_summaryCacheModel.summary = getSummary();

		String summary = benefits_summaryCacheModel.summary;

		if ((summary != null) && (summary.length() == 0)) {
			benefits_summaryCacheModel.summary = null;
		}

		return benefits_summaryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{benefits_summary_id=");
		sb.append(getBenefits_summary_id());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", summary=");
		sb.append(getSummary());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.benefits_summary");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>benefits_summary_id</column-name><column-value><![CDATA[");
		sb.append(getBenefits_summary_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>summary</column-name><column-value><![CDATA[");
		sb.append(getSummary());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = benefits_summary.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			benefits_summary.class
		};
	private long _benefits_summary_id;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private String _summary;
	private long _columnBitmask;
	private benefits_summary _escapedModelProxy;
}