/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.boundary_modification_type_lkp;
import com.iucn.whp.dbservice.model.boundary_modification_type_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the boundary_modification_type_lkp service. Represents a row in the &quot;whp_boundary_modification_type_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.boundary_modification_type_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link boundary_modification_type_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see boundary_modification_type_lkpImpl
 * @see com.iucn.whp.dbservice.model.boundary_modification_type_lkp
 * @see com.iucn.whp.dbservice.model.boundary_modification_type_lkpModel
 * @generated
 */
public class boundary_modification_type_lkpModelImpl extends BaseModelImpl<boundary_modification_type_lkp>
	implements boundary_modification_type_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a boundary_modification_type_lkp model instance should use the {@link com.iucn.whp.dbservice.model.boundary_modification_type_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_boundary_modification_type_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "bm_id", Types.INTEGER },
			{ "bm_type", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_boundary_modification_type_lkp (bm_id INTEGER not null primary key,bm_type VARCHAR(50) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_boundary_modification_type_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.boundary_modification_type_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.boundary_modification_type_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.boundary_modification_type_lkp"));

	public boundary_modification_type_lkpModelImpl() {
	}

	public int getPrimaryKey() {
		return _bm_id;
	}

	public void setPrimaryKey(int primaryKey) {
		setBm_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_bm_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return boundary_modification_type_lkp.class;
	}

	public String getModelClassName() {
		return boundary_modification_type_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("bm_id", getBm_id());
		attributes.put("bm_type", getBm_type());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer bm_id = (Integer)attributes.get("bm_id");

		if (bm_id != null) {
			setBm_id(bm_id);
		}

		String bm_type = (String)attributes.get("bm_type");

		if (bm_type != null) {
			setBm_type(bm_type);
		}
	}

	public int getBm_id() {
		return _bm_id;
	}

	public void setBm_id(int bm_id) {
		_bm_id = bm_id;
	}

	public String getBm_type() {
		if (_bm_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _bm_type;
		}
	}

	public void setBm_type(String bm_type) {
		_bm_type = bm_type;
	}

	@Override
	public boundary_modification_type_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (boundary_modification_type_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		boundary_modification_type_lkpImpl boundary_modification_type_lkpImpl = new boundary_modification_type_lkpImpl();

		boundary_modification_type_lkpImpl.setBm_id(getBm_id());
		boundary_modification_type_lkpImpl.setBm_type(getBm_type());

		boundary_modification_type_lkpImpl.resetOriginalValues();

		return boundary_modification_type_lkpImpl;
	}

	public int compareTo(
		boundary_modification_type_lkp boundary_modification_type_lkp) {
		int primaryKey = boundary_modification_type_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		boundary_modification_type_lkp boundary_modification_type_lkp = null;

		try {
			boundary_modification_type_lkp = (boundary_modification_type_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = boundary_modification_type_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<boundary_modification_type_lkp> toCacheModel() {
		boundary_modification_type_lkpCacheModel boundary_modification_type_lkpCacheModel =
			new boundary_modification_type_lkpCacheModel();

		boundary_modification_type_lkpCacheModel.bm_id = getBm_id();

		boundary_modification_type_lkpCacheModel.bm_type = getBm_type();

		String bm_type = boundary_modification_type_lkpCacheModel.bm_type;

		if ((bm_type != null) && (bm_type.length() == 0)) {
			boundary_modification_type_lkpCacheModel.bm_type = null;
		}

		return boundary_modification_type_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{bm_id=");
		sb.append(getBm_id());
		sb.append(", bm_type=");
		sb.append(getBm_type());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.boundary_modification_type_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>bm_id</column-name><column-value><![CDATA[");
		sb.append(getBm_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bm_type</column-name><column-value><![CDATA[");
		sb.append(getBm_type());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = boundary_modification_type_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			boundary_modification_type_lkp.class
		};
	private int _bm_id;
	private String _bm_type;
	private boundary_modification_type_lkp _escapedModelProxy;
}