/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp;
import com.iucn.whp.dbservice.model.conservation_outlook_rating_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the conservation_outlook_rating_lkp service. Represents a row in the &quot;whp_conservation_outlook_rating_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.conservation_outlook_rating_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link conservation_outlook_rating_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see conservation_outlook_rating_lkpImpl
 * @see com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp
 * @see com.iucn.whp.dbservice.model.conservation_outlook_rating_lkpModel
 * @generated
 */
public class conservation_outlook_rating_lkpModelImpl extends BaseModelImpl<conservation_outlook_rating_lkp>
	implements conservation_outlook_rating_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a conservation_outlook_rating_lkp model instance should use the {@link com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_conservation_outlook_rating_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "co_rating_id", Types.BIGINT },
			{ "co_rating", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_conservation_outlook_rating_lkp (co_rating_id LONG not null primary key,co_rating VARCHAR(50) null,description VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_conservation_outlook_rating_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp"));

	public conservation_outlook_rating_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _co_rating_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setCo_rating_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_co_rating_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return conservation_outlook_rating_lkp.class;
	}

	public String getModelClassName() {
		return conservation_outlook_rating_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("co_rating_id", getCo_rating_id());
		attributes.put("co_rating", getCo_rating());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long co_rating_id = (Long)attributes.get("co_rating_id");

		if (co_rating_id != null) {
			setCo_rating_id(co_rating_id);
		}

		String co_rating = (String)attributes.get("co_rating");

		if (co_rating != null) {
			setCo_rating(co_rating);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getCo_rating_id() {
		return _co_rating_id;
	}

	public void setCo_rating_id(long co_rating_id) {
		_co_rating_id = co_rating_id;
	}

	public String getCo_rating() {
		if (_co_rating == null) {
			return StringPool.BLANK;
		}
		else {
			return _co_rating;
		}
	}

	public void setCo_rating(String co_rating) {
		_co_rating = co_rating;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			conservation_outlook_rating_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public conservation_outlook_rating_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (conservation_outlook_rating_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		conservation_outlook_rating_lkpImpl conservation_outlook_rating_lkpImpl = new conservation_outlook_rating_lkpImpl();

		conservation_outlook_rating_lkpImpl.setCo_rating_id(getCo_rating_id());
		conservation_outlook_rating_lkpImpl.setCo_rating(getCo_rating());
		conservation_outlook_rating_lkpImpl.setDescription(getDescription());

		conservation_outlook_rating_lkpImpl.resetOriginalValues();

		return conservation_outlook_rating_lkpImpl;
	}

	public int compareTo(
		conservation_outlook_rating_lkp conservation_outlook_rating_lkp) {
		long primaryKey = conservation_outlook_rating_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		conservation_outlook_rating_lkp conservation_outlook_rating_lkp = null;

		try {
			conservation_outlook_rating_lkp = (conservation_outlook_rating_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = conservation_outlook_rating_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<conservation_outlook_rating_lkp> toCacheModel() {
		conservation_outlook_rating_lkpCacheModel conservation_outlook_rating_lkpCacheModel =
			new conservation_outlook_rating_lkpCacheModel();

		conservation_outlook_rating_lkpCacheModel.co_rating_id = getCo_rating_id();

		conservation_outlook_rating_lkpCacheModel.co_rating = getCo_rating();

		String co_rating = conservation_outlook_rating_lkpCacheModel.co_rating;

		if ((co_rating != null) && (co_rating.length() == 0)) {
			conservation_outlook_rating_lkpCacheModel.co_rating = null;
		}

		conservation_outlook_rating_lkpCacheModel.description = getDescription();

		String description = conservation_outlook_rating_lkpCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			conservation_outlook_rating_lkpCacheModel.description = null;
		}

		return conservation_outlook_rating_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{co_rating_id=");
		sb.append(getCo_rating_id());
		sb.append(", co_rating=");
		sb.append(getCo_rating());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"com.iucn.whp.dbservice.model.conservation_outlook_rating_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>co_rating_id</column-name><column-value><![CDATA[");
		sb.append(getCo_rating_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>co_rating</column-name><column-value><![CDATA[");
		sb.append(getCo_rating());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = conservation_outlook_rating_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			conservation_outlook_rating_lkp.class
		};
	private long _co_rating_id;
	private String _co_rating;
	private String _description;
	private conservation_outlook_rating_lkp _escapedModelProxy;
}