/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.conservation_outlook;
import com.iucn.whp.dbservice.model.conservation_outlookModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the conservation_outlook service. Represents a row in the &quot;whp_conservation_outlook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.conservation_outlookModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link conservation_outlookImpl}.
 * </p>
 *
 * @author alok.sen
 * @see conservation_outlookImpl
 * @see com.iucn.whp.dbservice.model.conservation_outlook
 * @see com.iucn.whp.dbservice.model.conservation_outlookModel
 * @generated
 */
public class conservation_outlookModelImpl extends BaseModelImpl<conservation_outlook>
	implements conservation_outlookModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a conservation_outlook model instance should use the {@link com.iucn.whp.dbservice.model.conservation_outlook} interface instead.
	 */
	public static final String TABLE_NAME = "whp_conservation_outlook";
	public static final Object[][] TABLE_COLUMNS = {
			{ "conservation_outlook_id", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "justification", Types.VARCHAR },
			{ "rating", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_conservation_outlook (conservation_outlook_id LONG not null primary key,assessment_version_id LONG,justification STRING null,rating LONG)";
	public static final String TABLE_SQL_DROP = "drop table whp_conservation_outlook";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.conservation_outlook"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.conservation_outlook"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.conservation_outlook"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.conservation_outlook"));

	public conservation_outlookModelImpl() {
	}

	public long getPrimaryKey() {
		return _conservation_outlook_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setConservation_outlook_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_conservation_outlook_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return conservation_outlook.class;
	}

	public String getModelClassName() {
		return conservation_outlook.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("conservation_outlook_id", getConservation_outlook_id());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("justification", getJustification());
		attributes.put("rating", getRating());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long conservation_outlook_id = (Long)attributes.get(
				"conservation_outlook_id");

		if (conservation_outlook_id != null) {
			setConservation_outlook_id(conservation_outlook_id);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		String justification = (String)attributes.get("justification");

		if (justification != null) {
			setJustification(justification);
		}

		Long rating = (Long)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}
	}

	public long getConservation_outlook_id() {
		return _conservation_outlook_id;
	}

	public void setConservation_outlook_id(long conservation_outlook_id) {
		_conservation_outlook_id = conservation_outlook_id;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public String getJustification() {
		if (_justification == null) {
			return StringPool.BLANK;
		}
		else {
			return _justification;
		}
	}

	public void setJustification(String justification) {
		_justification = justification;
	}

	public long getRating() {
		return _rating;
	}

	public void setRating(long rating) {
		_rating = rating;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			conservation_outlook.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public conservation_outlook toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (conservation_outlook)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		conservation_outlookImpl conservation_outlookImpl = new conservation_outlookImpl();

		conservation_outlookImpl.setConservation_outlook_id(getConservation_outlook_id());
		conservation_outlookImpl.setAssessment_version_id(getAssessment_version_id());
		conservation_outlookImpl.setJustification(getJustification());
		conservation_outlookImpl.setRating(getRating());

		conservation_outlookImpl.resetOriginalValues();

		return conservation_outlookImpl;
	}

	public int compareTo(conservation_outlook conservation_outlook) {
		long primaryKey = conservation_outlook.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		conservation_outlook conservation_outlook = null;

		try {
			conservation_outlook = (conservation_outlook)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = conservation_outlook.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		conservation_outlookModelImpl conservation_outlookModelImpl = this;

		conservation_outlookModelImpl._originalAssessment_version_id = conservation_outlookModelImpl._assessment_version_id;

		conservation_outlookModelImpl._setOriginalAssessment_version_id = false;

		conservation_outlookModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<conservation_outlook> toCacheModel() {
		conservation_outlookCacheModel conservation_outlookCacheModel = new conservation_outlookCacheModel();

		conservation_outlookCacheModel.conservation_outlook_id = getConservation_outlook_id();

		conservation_outlookCacheModel.assessment_version_id = getAssessment_version_id();

		conservation_outlookCacheModel.justification = getJustification();

		String justification = conservation_outlookCacheModel.justification;

		if ((justification != null) && (justification.length() == 0)) {
			conservation_outlookCacheModel.justification = null;
		}

		conservation_outlookCacheModel.rating = getRating();

		return conservation_outlookCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{conservation_outlook_id=");
		sb.append(getConservation_outlook_id());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", justification=");
		sb.append(getJustification());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.conservation_outlook");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>conservation_outlook_id</column-name><column-value><![CDATA[");
		sb.append(getConservation_outlook_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>justification</column-name><column-value><![CDATA[");
		sb.append(getJustification());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = conservation_outlook.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			conservation_outlook.class
		};
	private long _conservation_outlook_id;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private String _justification;
	private long _rating;
	private long _columnBitmask;
	private conservation_outlook _escapedModelProxy;
}