/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.current_state_trend;
import com.iucn.whp.dbservice.model.current_state_trendModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the current_state_trend service. Represents a row in the &quot;whp_current_state_trend&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.current_state_trendModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link current_state_trendImpl}.
 * </p>
 *
 * @author alok.sen
 * @see current_state_trendImpl
 * @see com.iucn.whp.dbservice.model.current_state_trend
 * @see com.iucn.whp.dbservice.model.current_state_trendModel
 * @generated
 */
public class current_state_trendModelImpl extends BaseModelImpl<current_state_trend>
	implements current_state_trendModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a current_state_trend model instance should use the {@link com.iucn.whp.dbservice.model.current_state_trend} interface instead.
	 */
	public static final String TABLE_NAME = "whp_current_state_trend";
	public static final Object[][] TABLE_COLUMNS = {
			{ "state_trend_id", Types.BIGINT },
			{ "vn", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "justification", Types.VARCHAR },
			{ "trend_id", Types.BIGINT },
			{ "state_id", Types.BIGINT },
			{ "is_biodiv_whval", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_current_state_trend (state_trend_id LONG not null primary key,vn LONG,assessment_version_id LONG,justification STRING null,trend_id LONG,state_id LONG,is_biodiv_whval BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table whp_current_state_trend";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.current_state_trend"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.current_state_trend"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.current_state_trend"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.current_state_trend"));

	public current_state_trendModelImpl() {
	}

	public long getPrimaryKey() {
		return _state_trend_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setState_trend_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_state_trend_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return current_state_trend.class;
	}

	public String getModelClassName() {
		return current_state_trend.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("state_trend_id", getState_trend_id());
		attributes.put("vn", getVn());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("justification", getJustification());
		attributes.put("trend_id", getTrend_id());
		attributes.put("state_id", getState_id());
		attributes.put("is_biodiv_whval", getIs_biodiv_whval());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long state_trend_id = (Long)attributes.get("state_trend_id");

		if (state_trend_id != null) {
			setState_trend_id(state_trend_id);
		}

		Long vn = (Long)attributes.get("vn");

		if (vn != null) {
			setVn(vn);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		String justification = (String)attributes.get("justification");

		if (justification != null) {
			setJustification(justification);
		}

		Long trend_id = (Long)attributes.get("trend_id");

		if (trend_id != null) {
			setTrend_id(trend_id);
		}

		Long state_id = (Long)attributes.get("state_id");

		if (state_id != null) {
			setState_id(state_id);
		}

		Boolean is_biodiv_whval = (Boolean)attributes.get("is_biodiv_whval");

		if (is_biodiv_whval != null) {
			setIs_biodiv_whval(is_biodiv_whval);
		}
	}

	public long getState_trend_id() {
		return _state_trend_id;
	}

	public void setState_trend_id(long state_trend_id) {
		_state_trend_id = state_trend_id;
	}

	public long getVn() {
		return _vn;
	}

	public void setVn(long vn) {
		_vn = vn;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public String getJustification() {
		if (_justification == null) {
			return StringPool.BLANK;
		}
		else {
			return _justification;
		}
	}

	public void setJustification(String justification) {
		_justification = justification;
	}

	public long getTrend_id() {
		return _trend_id;
	}

	public void setTrend_id(long trend_id) {
		_trend_id = trend_id;
	}

	public long getState_id() {
		return _state_id;
	}

	public void setState_id(long state_id) {
		_state_id = state_id;
	}

	public boolean getIs_biodiv_whval() {
		return _is_biodiv_whval;
	}

	public boolean isIs_biodiv_whval() {
		return _is_biodiv_whval;
	}

	public void setIs_biodiv_whval(boolean is_biodiv_whval) {
		_is_biodiv_whval = is_biodiv_whval;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			current_state_trend.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public current_state_trend toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (current_state_trend)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		current_state_trendImpl current_state_trendImpl = new current_state_trendImpl();

		current_state_trendImpl.setState_trend_id(getState_trend_id());
		current_state_trendImpl.setVn(getVn());
		current_state_trendImpl.setAssessment_version_id(getAssessment_version_id());
		current_state_trendImpl.setJustification(getJustification());
		current_state_trendImpl.setTrend_id(getTrend_id());
		current_state_trendImpl.setState_id(getState_id());
		current_state_trendImpl.setIs_biodiv_whval(getIs_biodiv_whval());

		current_state_trendImpl.resetOriginalValues();

		return current_state_trendImpl;
	}

	public int compareTo(current_state_trend current_state_trend) {
		long primaryKey = current_state_trend.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		current_state_trend current_state_trend = null;

		try {
			current_state_trend = (current_state_trend)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = current_state_trend.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		current_state_trendModelImpl current_state_trendModelImpl = this;

		current_state_trendModelImpl._originalAssessment_version_id = current_state_trendModelImpl._assessment_version_id;

		current_state_trendModelImpl._setOriginalAssessment_version_id = false;

		current_state_trendModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<current_state_trend> toCacheModel() {
		current_state_trendCacheModel current_state_trendCacheModel = new current_state_trendCacheModel();

		current_state_trendCacheModel.state_trend_id = getState_trend_id();

		current_state_trendCacheModel.vn = getVn();

		current_state_trendCacheModel.assessment_version_id = getAssessment_version_id();

		current_state_trendCacheModel.justification = getJustification();

		String justification = current_state_trendCacheModel.justification;

		if ((justification != null) && (justification.length() == 0)) {
			current_state_trendCacheModel.justification = null;
		}

		current_state_trendCacheModel.trend_id = getTrend_id();

		current_state_trendCacheModel.state_id = getState_id();

		current_state_trendCacheModel.is_biodiv_whval = getIs_biodiv_whval();

		return current_state_trendCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{state_trend_id=");
		sb.append(getState_trend_id());
		sb.append(", vn=");
		sb.append(getVn());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", justification=");
		sb.append(getJustification());
		sb.append(", trend_id=");
		sb.append(getTrend_id());
		sb.append(", state_id=");
		sb.append(getState_id());
		sb.append(", is_biodiv_whval=");
		sb.append(getIs_biodiv_whval());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.current_state_trend");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>state_trend_id</column-name><column-value><![CDATA[");
		sb.append(getState_trend_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vn</column-name><column-value><![CDATA[");
		sb.append(getVn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>justification</column-name><column-value><![CDATA[");
		sb.append(getJustification());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trend_id</column-name><column-value><![CDATA[");
		sb.append(getTrend_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>state_id</column-name><column-value><![CDATA[");
		sb.append(getState_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>is_biodiv_whval</column-name><column-value><![CDATA[");
		sb.append(getIs_biodiv_whval());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = current_state_trend.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			current_state_trend.class
		};
	private long _state_trend_id;
	private long _vn;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private String _justification;
	private long _trend_id;
	private long _state_id;
	private boolean _is_biodiv_whval;
	private long _columnBitmask;
	private current_state_trend _escapedModelProxy;
}