/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.current_state_trend_values;
import com.iucn.whp.dbservice.model.current_state_trend_valuesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the current_state_trend_values service. Represents a row in the &quot;whp_current_state_trend_values&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.current_state_trend_valuesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link current_state_trend_valuesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see current_state_trend_valuesImpl
 * @see com.iucn.whp.dbservice.model.current_state_trend_values
 * @see com.iucn.whp.dbservice.model.current_state_trend_valuesModel
 * @generated
 */
public class current_state_trend_valuesModelImpl extends BaseModelImpl<current_state_trend_values>
	implements current_state_trend_valuesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a current_state_trend_values model instance should use the {@link com.iucn.whp.dbservice.model.current_state_trend_values} interface instead.
	 */
	public static final String TABLE_NAME = "whp_current_state_trend_values";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "vn", Types.BIGINT },
			{ "whvalues_id", Types.BIGINT },
			{ "state_trend_id", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_current_state_trend_values (id_ LONG not null primary key,vn LONG,whvalues_id LONG,state_trend_id LONG)";
	public static final String TABLE_SQL_DROP = "drop table whp_current_state_trend_values";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.current_state_trend_values"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.current_state_trend_values"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.current_state_trend_values"));

	public current_state_trend_valuesModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return current_state_trend_values.class;
	}

	public String getModelClassName() {
		return current_state_trend_values.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("vn", getVn());
		attributes.put("whvalues_id", getWhvalues_id());
		attributes.put("state_trend_id", getState_trend_id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long vn = (Long)attributes.get("vn");

		if (vn != null) {
			setVn(vn);
		}

		Long whvalues_id = (Long)attributes.get("whvalues_id");

		if (whvalues_id != null) {
			setWhvalues_id(whvalues_id);
		}

		Long state_trend_id = (Long)attributes.get("state_trend_id");

		if (state_trend_id != null) {
			setState_trend_id(state_trend_id);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getVn() {
		return _vn;
	}

	public void setVn(long vn) {
		_vn = vn;
	}

	public long getWhvalues_id() {
		return _whvalues_id;
	}

	public void setWhvalues_id(long whvalues_id) {
		_whvalues_id = whvalues_id;
	}

	public long getState_trend_id() {
		return _state_trend_id;
	}

	public void setState_trend_id(long state_trend_id) {
		_state_trend_id = state_trend_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			current_state_trend_values.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public current_state_trend_values toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (current_state_trend_values)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		current_state_trend_valuesImpl current_state_trend_valuesImpl = new current_state_trend_valuesImpl();

		current_state_trend_valuesImpl.setId(getId());
		current_state_trend_valuesImpl.setVn(getVn());
		current_state_trend_valuesImpl.setWhvalues_id(getWhvalues_id());
		current_state_trend_valuesImpl.setState_trend_id(getState_trend_id());

		current_state_trend_valuesImpl.resetOriginalValues();

		return current_state_trend_valuesImpl;
	}

	public int compareTo(current_state_trend_values current_state_trend_values) {
		long primaryKey = current_state_trend_values.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		current_state_trend_values current_state_trend_values = null;

		try {
			current_state_trend_values = (current_state_trend_values)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = current_state_trend_values.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<current_state_trend_values> toCacheModel() {
		current_state_trend_valuesCacheModel current_state_trend_valuesCacheModel =
			new current_state_trend_valuesCacheModel();

		current_state_trend_valuesCacheModel.id = getId();

		current_state_trend_valuesCacheModel.vn = getVn();

		current_state_trend_valuesCacheModel.whvalues_id = getWhvalues_id();

		current_state_trend_valuesCacheModel.state_trend_id = getState_trend_id();

		return current_state_trend_valuesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", vn=");
		sb.append(getVn());
		sb.append(", whvalues_id=");
		sb.append(getWhvalues_id());
		sb.append(", state_trend_id=");
		sb.append(getState_trend_id());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.current_state_trend_values");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vn</column-name><column-value><![CDATA[");
		sb.append(getVn());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>whvalues_id</column-name><column-value><![CDATA[");
		sb.append(getWhvalues_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>state_trend_id</column-name><column-value><![CDATA[");
		sb.append(getState_trend_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = current_state_trend_values.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			current_state_trend_values.class
		};
	private long _id;
	private long _vn;
	private long _whvalues_id;
	private long _state_trend_id;
	private current_state_trend_values _escapedModelProxy;
}