/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.danger_list_status_lkp;
import com.iucn.whp.dbservice.model.danger_list_status_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the danger_list_status_lkp service. Represents a row in the &quot;whp_danger_list_status_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.danger_list_status_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link danger_list_status_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see danger_list_status_lkpImpl
 * @see com.iucn.whp.dbservice.model.danger_list_status_lkp
 * @see com.iucn.whp.dbservice.model.danger_list_status_lkpModel
 * @generated
 */
public class danger_list_status_lkpModelImpl extends BaseModelImpl<danger_list_status_lkp>
	implements danger_list_status_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a danger_list_status_lkp model instance should use the {@link com.iucn.whp.dbservice.model.danger_list_status_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_danger_list_status_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dlstatus_id", Types.INTEGER },
			{ "dl_status", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_danger_list_status_lkp (dlstatus_id INTEGER not null primary key,dl_status VARCHAR(50) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_danger_list_status_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.danger_list_status_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.danger_list_status_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.danger_list_status_lkp"));

	public danger_list_status_lkpModelImpl() {
	}

	public int getPrimaryKey() {
		return _dlstatus_id;
	}

	public void setPrimaryKey(int primaryKey) {
		setDlstatus_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_dlstatus_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return danger_list_status_lkp.class;
	}

	public String getModelClassName() {
		return danger_list_status_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dlstatus_id", getDlstatus_id());
		attributes.put("dl_status", getDl_status());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer dlstatus_id = (Integer)attributes.get("dlstatus_id");

		if (dlstatus_id != null) {
			setDlstatus_id(dlstatus_id);
		}

		String dl_status = (String)attributes.get("dl_status");

		if (dl_status != null) {
			setDl_status(dl_status);
		}
	}

	public int getDlstatus_id() {
		return _dlstatus_id;
	}

	public void setDlstatus_id(int dlstatus_id) {
		_dlstatus_id = dlstatus_id;
	}

	public String getDl_status() {
		if (_dl_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _dl_status;
		}
	}

	public void setDl_status(String dl_status) {
		_dl_status = dl_status;
	}

	@Override
	public danger_list_status_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (danger_list_status_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		danger_list_status_lkpImpl danger_list_status_lkpImpl = new danger_list_status_lkpImpl();

		danger_list_status_lkpImpl.setDlstatus_id(getDlstatus_id());
		danger_list_status_lkpImpl.setDl_status(getDl_status());

		danger_list_status_lkpImpl.resetOriginalValues();

		return danger_list_status_lkpImpl;
	}

	public int compareTo(danger_list_status_lkp danger_list_status_lkp) {
		int primaryKey = danger_list_status_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		danger_list_status_lkp danger_list_status_lkp = null;

		try {
			danger_list_status_lkp = (danger_list_status_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = danger_list_status_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<danger_list_status_lkp> toCacheModel() {
		danger_list_status_lkpCacheModel danger_list_status_lkpCacheModel = new danger_list_status_lkpCacheModel();

		danger_list_status_lkpCacheModel.dlstatus_id = getDlstatus_id();

		danger_list_status_lkpCacheModel.dl_status = getDl_status();

		String dl_status = danger_list_status_lkpCacheModel.dl_status;

		if ((dl_status != null) && (dl_status.length() == 0)) {
			danger_list_status_lkpCacheModel.dl_status = null;
		}

		return danger_list_status_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{dlstatus_id=");
		sb.append(getDlstatus_id());
		sb.append(", dl_status=");
		sb.append(getDl_status());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.danger_list_status_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dlstatus_id</column-name><column-value><![CDATA[");
		sb.append(getDlstatus_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dl_status</column-name><column-value><![CDATA[");
		sb.append(getDl_status());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = danger_list_status_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			danger_list_status_lkp.class
		};
	private int _dlstatus_id;
	private String _dl_status;
	private danger_list_status_lkp _escapedModelProxy;
}