/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.docs_sitedata;
import com.iucn.whp.dbservice.service.docs_sitedataLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the docs_sitedata service. Represents a row in the &quot;whp_docs_sitedata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link docs_sitedataImpl}.
 * </p>
 *
 * @author alok.sen
 * @see docs_sitedataImpl
 * @see com.iucn.whp.dbservice.model.docs_sitedata
 * @generated
 */
public abstract class docs_sitedataBaseImpl extends docs_sitedataModelImpl
	implements docs_sitedata {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a docs_sitedata model instance should use the {@link docs_sitedata} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			docs_sitedataLocalServiceUtil.adddocs_sitedata(this);
		}
		else {
			docs_sitedataLocalServiceUtil.updatedocs_sitedata(this);
		}
	}
}