/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.flagship_species_lkp;
import com.iucn.whp.dbservice.model.flagship_species_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the flagship_species_lkp service. Represents a row in the &quot;whp_flagship_species_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.flagship_species_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link flagship_species_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see flagship_species_lkpImpl
 * @see com.iucn.whp.dbservice.model.flagship_species_lkp
 * @see com.iucn.whp.dbservice.model.flagship_species_lkpModel
 * @generated
 */
public class flagship_species_lkpModelImpl extends BaseModelImpl<flagship_species_lkp>
	implements flagship_species_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a flagship_species_lkp model instance should use the {@link com.iucn.whp.dbservice.model.flagship_species_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_flagship_species_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "flagship_species_id", Types.INTEGER },
			{ "flagship_species_name", Types.VARCHAR },
			{ "redlist_url", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_flagship_species_lkp (flagship_species_id INTEGER not null primary key,flagship_species_name VARCHAR(200) null,redlist_url VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_flagship_species_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.flagship_species_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.flagship_species_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.flagship_species_lkp"));

	public flagship_species_lkpModelImpl() {
	}

	public int getPrimaryKey() {
		return _flagship_species_id;
	}

	public void setPrimaryKey(int primaryKey) {
		setFlagship_species_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_flagship_species_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return flagship_species_lkp.class;
	}

	public String getModelClassName() {
		return flagship_species_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("flagship_species_id", getFlagship_species_id());
		attributes.put("flagship_species_name", getFlagship_species_name());
		attributes.put("redlist_url", getRedlist_url());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer flagship_species_id = (Integer)attributes.get(
				"flagship_species_id");

		if (flagship_species_id != null) {
			setFlagship_species_id(flagship_species_id);
		}

		String flagship_species_name = (String)attributes.get(
				"flagship_species_name");

		if (flagship_species_name != null) {
			setFlagship_species_name(flagship_species_name);
		}

		String redlist_url = (String)attributes.get("redlist_url");

		if (redlist_url != null) {
			setRedlist_url(redlist_url);
		}
	}

	public int getFlagship_species_id() {
		return _flagship_species_id;
	}

	public void setFlagship_species_id(int flagship_species_id) {
		_flagship_species_id = flagship_species_id;
	}

	public String getFlagship_species_name() {
		if (_flagship_species_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _flagship_species_name;
		}
	}

	public void setFlagship_species_name(String flagship_species_name) {
		_flagship_species_name = flagship_species_name;
	}

	public String getRedlist_url() {
		if (_redlist_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _redlist_url;
		}
	}

	public void setRedlist_url(String redlist_url) {
		_redlist_url = redlist_url;
	}

	@Override
	public flagship_species_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (flagship_species_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		flagship_species_lkpImpl flagship_species_lkpImpl = new flagship_species_lkpImpl();

		flagship_species_lkpImpl.setFlagship_species_id(getFlagship_species_id());
		flagship_species_lkpImpl.setFlagship_species_name(getFlagship_species_name());
		flagship_species_lkpImpl.setRedlist_url(getRedlist_url());

		flagship_species_lkpImpl.resetOriginalValues();

		return flagship_species_lkpImpl;
	}

	public int compareTo(flagship_species_lkp flagship_species_lkp) {
		int primaryKey = flagship_species_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		flagship_species_lkp flagship_species_lkp = null;

		try {
			flagship_species_lkp = (flagship_species_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = flagship_species_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<flagship_species_lkp> toCacheModel() {
		flagship_species_lkpCacheModel flagship_species_lkpCacheModel = new flagship_species_lkpCacheModel();

		flagship_species_lkpCacheModel.flagship_species_id = getFlagship_species_id();

		flagship_species_lkpCacheModel.flagship_species_name = getFlagship_species_name();

		String flagship_species_name = flagship_species_lkpCacheModel.flagship_species_name;

		if ((flagship_species_name != null) &&
				(flagship_species_name.length() == 0)) {
			flagship_species_lkpCacheModel.flagship_species_name = null;
		}

		flagship_species_lkpCacheModel.redlist_url = getRedlist_url();

		String redlist_url = flagship_species_lkpCacheModel.redlist_url;

		if ((redlist_url != null) && (redlist_url.length() == 0)) {
			flagship_species_lkpCacheModel.redlist_url = null;
		}

		return flagship_species_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{flagship_species_id=");
		sb.append(getFlagship_species_id());
		sb.append(", flagship_species_name=");
		sb.append(getFlagship_species_name());
		sb.append(", redlist_url=");
		sb.append(getRedlist_url());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.flagship_species_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>flagship_species_id</column-name><column-value><![CDATA[");
		sb.append(getFlagship_species_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flagship_species_name</column-name><column-value><![CDATA[");
		sb.append(getFlagship_species_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>redlist_url</column-name><column-value><![CDATA[");
		sb.append(getRedlist_url());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = flagship_species_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			flagship_species_lkp.class
		};
	private int _flagship_species_id;
	private String _flagship_species_name;
	private String _redlist_url;
	private flagship_species_lkp _escapedModelProxy;
}