/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.inscription_criteria_lkp;
import com.iucn.whp.dbservice.service.inscription_criteria_lkpLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the inscription_criteria_lkp service. Represents a row in the &quot;whp_inscription_criteria_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link inscription_criteria_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see inscription_criteria_lkpImpl
 * @see com.iucn.whp.dbservice.model.inscription_criteria_lkp
 * @generated
 */
public abstract class inscription_criteria_lkpBaseImpl
	extends inscription_criteria_lkpModelImpl
	implements inscription_criteria_lkp {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a inscription_criteria_lkp model instance should use the {@link inscription_criteria_lkp} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			inscription_criteria_lkpLocalServiceUtil.addinscription_criteria_lkp(this);
		}
		else {
			inscription_criteria_lkpLocalServiceUtil.updateinscription_criteria_lkp(this);
		}
	}
}