/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.iucn_region;
import com.iucn.whp.dbservice.model.iucn_regionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the iucn_region service. Represents a row in the &quot;whp_iucn_region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.iucn_regionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link iucn_regionImpl}.
 * </p>
 *
 * @author alok.sen
 * @see iucn_regionImpl
 * @see com.iucn.whp.dbservice.model.iucn_region
 * @see com.iucn.whp.dbservice.model.iucn_regionModel
 * @generated
 */
public class iucn_regionModelImpl extends BaseModelImpl<iucn_region>
	implements iucn_regionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a iucn_region model instance should use the {@link com.iucn.whp.dbservice.model.iucn_region} interface instead.
	 */
	public static final String TABLE_NAME = "whp_iucn_region";
	public static final Object[][] TABLE_COLUMNS = {
			{ "iucn_region_id", Types.INTEGER },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_iucn_region (iucn_region_id INTEGER not null primary key,name VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_iucn_region";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.iucn_region"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.iucn_region"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.iucn_region"));

	public iucn_regionModelImpl() {
	}

	public int getPrimaryKey() {
		return _iucn_region_id;
	}

	public void setPrimaryKey(int primaryKey) {
		setIucn_region_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_iucn_region_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return iucn_region.class;
	}

	public String getModelClassName() {
		return iucn_region.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("iucn_region_id", getIucn_region_id());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer iucn_region_id = (Integer)attributes.get("iucn_region_id");

		if (iucn_region_id != null) {
			setIucn_region_id(iucn_region_id);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	public int getIucn_region_id() {
		return _iucn_region_id;
	}

	public void setIucn_region_id(int iucn_region_id) {
		_iucn_region_id = iucn_region_id;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	@Override
	public iucn_region toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (iucn_region)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		iucn_regionImpl iucn_regionImpl = new iucn_regionImpl();

		iucn_regionImpl.setIucn_region_id(getIucn_region_id());
		iucn_regionImpl.setName(getName());

		iucn_regionImpl.resetOriginalValues();

		return iucn_regionImpl;
	}

	public int compareTo(iucn_region iucn_region) {
		int primaryKey = iucn_region.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		iucn_region iucn_region = null;

		try {
			iucn_region = (iucn_region)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = iucn_region.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<iucn_region> toCacheModel() {
		iucn_regionCacheModel iucn_regionCacheModel = new iucn_regionCacheModel();

		iucn_regionCacheModel.iucn_region_id = getIucn_region_id();

		iucn_regionCacheModel.name = getName();

		String name = iucn_regionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			iucn_regionCacheModel.name = null;
		}

		return iucn_regionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{iucn_region_id=");
		sb.append(getIucn_region_id());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.iucn_region");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>iucn_region_id</column-name><column-value><![CDATA[");
		sb.append(getIucn_region_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = iucn_region.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			iucn_region.class
		};
	private int _iucn_region_id;
	private String _name;
	private iucn_region _escapedModelProxy;
}