/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.iucn_region_country;
import com.iucn.whp.dbservice.model.iucn_region_countryModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the iucn_region_country service. Represents a row in the &quot;whp_iucn_region_country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.iucn_region_countryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link iucn_region_countryImpl}.
 * </p>
 *
 * @author alok.sen
 * @see iucn_region_countryImpl
 * @see com.iucn.whp.dbservice.model.iucn_region_country
 * @see com.iucn.whp.dbservice.model.iucn_region_countryModel
 * @generated
 */
public class iucn_region_countryModelImpl extends BaseModelImpl<iucn_region_country>
	implements iucn_region_countryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a iucn_region_country model instance should use the {@link com.iucn.whp.dbservice.model.iucn_region_country} interface instead.
	 */
	public static final String TABLE_NAME = "whp_iucn_region_country";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whp_iucn_region_country_id", Types.INTEGER },
			{ "countryid", Types.INTEGER },
			{ "iucn_region_id", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_iucn_region_country (whp_iucn_region_country_id INTEGER not null primary key,countryid INTEGER,iucn_region_id INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table whp_iucn_region_country";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.iucn_region_country"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.iucn_region_country"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.iucn_region_country"),
			true);
	public static long COUNTRYID_COLUMN_BITMASK = 1L;
	public static long IUCN_REGION_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.iucn_region_country"));

	public iucn_region_countryModelImpl() {
	}

	public int getPrimaryKey() {
		return _whp_iucn_region_country_id;
	}

	public void setPrimaryKey(int primaryKey) {
		setWhp_iucn_region_country_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_whp_iucn_region_country_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return iucn_region_country.class;
	}

	public String getModelClassName() {
		return iucn_region_country.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whp_iucn_region_country_id",
			getWhp_iucn_region_country_id());
		attributes.put("countryid", getCountryid());
		attributes.put("iucn_region_id", getIucn_region_id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer whp_iucn_region_country_id = (Integer)attributes.get(
				"whp_iucn_region_country_id");

		if (whp_iucn_region_country_id != null) {
			setWhp_iucn_region_country_id(whp_iucn_region_country_id);
		}

		Integer countryid = (Integer)attributes.get("countryid");

		if (countryid != null) {
			setCountryid(countryid);
		}

		Integer iucn_region_id = (Integer)attributes.get("iucn_region_id");

		if (iucn_region_id != null) {
			setIucn_region_id(iucn_region_id);
		}
	}

	public int getWhp_iucn_region_country_id() {
		return _whp_iucn_region_country_id;
	}

	public void setWhp_iucn_region_country_id(int whp_iucn_region_country_id) {
		_whp_iucn_region_country_id = whp_iucn_region_country_id;
	}

	public int getCountryid() {
		return _countryid;
	}

	public void setCountryid(int countryid) {
		_columnBitmask |= COUNTRYID_COLUMN_BITMASK;

		if (!_setOriginalCountryid) {
			_setOriginalCountryid = true;

			_originalCountryid = _countryid;
		}

		_countryid = countryid;
	}

	public int getOriginalCountryid() {
		return _originalCountryid;
	}

	public int getIucn_region_id() {
		return _iucn_region_id;
	}

	public void setIucn_region_id(int iucn_region_id) {
		_columnBitmask |= IUCN_REGION_ID_COLUMN_BITMASK;

		if (!_setOriginalIucn_region_id) {
			_setOriginalIucn_region_id = true;

			_originalIucn_region_id = _iucn_region_id;
		}

		_iucn_region_id = iucn_region_id;
	}

	public int getOriginalIucn_region_id() {
		return _originalIucn_region_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public iucn_region_country toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (iucn_region_country)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		iucn_region_countryImpl iucn_region_countryImpl = new iucn_region_countryImpl();

		iucn_region_countryImpl.setWhp_iucn_region_country_id(getWhp_iucn_region_country_id());
		iucn_region_countryImpl.setCountryid(getCountryid());
		iucn_region_countryImpl.setIucn_region_id(getIucn_region_id());

		iucn_region_countryImpl.resetOriginalValues();

		return iucn_region_countryImpl;
	}

	public int compareTo(iucn_region_country iucn_region_country) {
		int primaryKey = iucn_region_country.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		iucn_region_country iucn_region_country = null;

		try {
			iucn_region_country = (iucn_region_country)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = iucn_region_country.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		iucn_region_countryModelImpl iucn_region_countryModelImpl = this;

		iucn_region_countryModelImpl._originalCountryid = iucn_region_countryModelImpl._countryid;

		iucn_region_countryModelImpl._setOriginalCountryid = false;

		iucn_region_countryModelImpl._originalIucn_region_id = iucn_region_countryModelImpl._iucn_region_id;

		iucn_region_countryModelImpl._setOriginalIucn_region_id = false;

		iucn_region_countryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<iucn_region_country> toCacheModel() {
		iucn_region_countryCacheModel iucn_region_countryCacheModel = new iucn_region_countryCacheModel();

		iucn_region_countryCacheModel.whp_iucn_region_country_id = getWhp_iucn_region_country_id();

		iucn_region_countryCacheModel.countryid = getCountryid();

		iucn_region_countryCacheModel.iucn_region_id = getIucn_region_id();

		return iucn_region_countryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{whp_iucn_region_country_id=");
		sb.append(getWhp_iucn_region_country_id());
		sb.append(", countryid=");
		sb.append(getCountryid());
		sb.append(", iucn_region_id=");
		sb.append(getIucn_region_id());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.iucn_region_country");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whp_iucn_region_country_id</column-name><column-value><![CDATA[");
		sb.append(getWhp_iucn_region_country_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryid</column-name><column-value><![CDATA[");
		sb.append(getCountryid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>iucn_region_id</column-name><column-value><![CDATA[");
		sb.append(getIucn_region_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = iucn_region_country.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			iucn_region_country.class
		};
	private int _whp_iucn_region_country_id;
	private int _countryid;
	private int _originalCountryid;
	private boolean _setOriginalCountryid;
	private int _iucn_region_id;
	private int _originalIucn_region_id;
	private boolean _setOriginalIucn_region_id;
	private long _columnBitmask;
	private iucn_region_country _escapedModelProxy;
}