/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.iucn_region_country;
import com.iucn.whp.dbservice.service.iucn_region_countryLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the iucn_region_country service. Represents a row in the &quot;whp_iucn_region_country&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link iucn_region_countryImpl}.
 * </p>
 *
 * @author alok.sen
 * @see iucn_region_countryImpl
 * @see com.iucn.whp.dbservice.model.iucn_region_country
 * @generated
 */
public abstract class iucn_region_countryBaseImpl
	extends iucn_region_countryModelImpl implements iucn_region_country {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a iucn_region_country model instance should use the {@link iucn_region_country} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			iucn_region_countryLocalServiceUtil.addiucn_region_country(this);
		}
		else {
			iucn_region_countryLocalServiceUtil.updateiucn_region_country(this);
		}
	}
}