/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.key_conservation_scale_lkp;
import com.iucn.whp.dbservice.model.key_conservation_scale_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the key_conservation_scale_lkp service. Represents a row in the &quot;whp_key_conservation_scale_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.key_conservation_scale_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link key_conservation_scale_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see key_conservation_scale_lkpImpl
 * @see com.iucn.whp.dbservice.model.key_conservation_scale_lkp
 * @see com.iucn.whp.dbservice.model.key_conservation_scale_lkpModel
 * @generated
 */
public class key_conservation_scale_lkpModelImpl extends BaseModelImpl<key_conservation_scale_lkp>
	implements key_conservation_scale_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a key_conservation_scale_lkp model instance should use the {@link com.iucn.whp.dbservice.model.key_conservation_scale_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_key_conservation_scale_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scale_id", Types.BIGINT },
			{ "scale", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_key_conservation_scale_lkp (scale_id LONG not null primary key,scale VARCHAR(20) null,description VARCHAR(200) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_key_conservation_scale_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.key_conservation_scale_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.key_conservation_scale_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.key_conservation_scale_lkp"));

	public key_conservation_scale_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _scale_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setScale_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_scale_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return key_conservation_scale_lkp.class;
	}

	public String getModelClassName() {
		return key_conservation_scale_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scale_id", getScale_id());
		attributes.put("scale", getScale());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scale_id = (Long)attributes.get("scale_id");

		if (scale_id != null) {
			setScale_id(scale_id);
		}

		String scale = (String)attributes.get("scale");

		if (scale != null) {
			setScale(scale);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getScale_id() {
		return _scale_id;
	}

	public void setScale_id(long scale_id) {
		_scale_id = scale_id;
	}

	public String getScale() {
		if (_scale == null) {
			return StringPool.BLANK;
		}
		else {
			return _scale;
		}
	}

	public void setScale(String scale) {
		_scale = scale;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			key_conservation_scale_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public key_conservation_scale_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (key_conservation_scale_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		key_conservation_scale_lkpImpl key_conservation_scale_lkpImpl = new key_conservation_scale_lkpImpl();

		key_conservation_scale_lkpImpl.setScale_id(getScale_id());
		key_conservation_scale_lkpImpl.setScale(getScale());
		key_conservation_scale_lkpImpl.setDescription(getDescription());

		key_conservation_scale_lkpImpl.resetOriginalValues();

		return key_conservation_scale_lkpImpl;
	}

	public int compareTo(key_conservation_scale_lkp key_conservation_scale_lkp) {
		long primaryKey = key_conservation_scale_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		key_conservation_scale_lkp key_conservation_scale_lkp = null;

		try {
			key_conservation_scale_lkp = (key_conservation_scale_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = key_conservation_scale_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<key_conservation_scale_lkp> toCacheModel() {
		key_conservation_scale_lkpCacheModel key_conservation_scale_lkpCacheModel =
			new key_conservation_scale_lkpCacheModel();

		key_conservation_scale_lkpCacheModel.scale_id = getScale_id();

		key_conservation_scale_lkpCacheModel.scale = getScale();

		String scale = key_conservation_scale_lkpCacheModel.scale;

		if ((scale != null) && (scale.length() == 0)) {
			key_conservation_scale_lkpCacheModel.scale = null;
		}

		key_conservation_scale_lkpCacheModel.description = getDescription();

		String description = key_conservation_scale_lkpCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			key_conservation_scale_lkpCacheModel.description = null;
		}

		return key_conservation_scale_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{scale_id=");
		sb.append(getScale_id());
		sb.append(", scale=");
		sb.append(getScale());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.key_conservation_scale_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scale_id</column-name><column-value><![CDATA[");
		sb.append(getScale_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scale</column-name><column-value><![CDATA[");
		sb.append(getScale());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = key_conservation_scale_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			key_conservation_scale_lkp.class
		};
	private long _scale_id;
	private String _scale;
	private String _description;
	private key_conservation_scale_lkp _escapedModelProxy;
}