/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.negative_factors_trend;
import com.iucn.whp.dbservice.service.negative_factors_trendLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the negative_factors_trend service. Represents a row in the &quot;whp_negative_factors_trend&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link negative_factors_trendImpl}.
 * </p>
 *
 * @author alok.sen
 * @see negative_factors_trendImpl
 * @see com.iucn.whp.dbservice.model.negative_factors_trend
 * @generated
 */
public abstract class negative_factors_trendBaseImpl
	extends negative_factors_trendModelImpl implements negative_factors_trend {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a negative_factors_trend model instance should use the {@link negative_factors_trend} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			negative_factors_trendLocalServiceUtil.addnegative_factors_trend(this);
		}
		else {
			negative_factors_trendLocalServiceUtil.updatenegative_factors_trend(this);
		}
	}
}