/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.potential_project_needs;
import com.iucn.whp.dbservice.service.potential_project_needsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the potential_project_needs service. Represents a row in the &quot;whp_potential_project_needs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link potential_project_needsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see potential_project_needsImpl
 * @see com.iucn.whp.dbservice.model.potential_project_needs
 * @generated
 */
public abstract class potential_project_needsBaseImpl
	extends potential_project_needsModelImpl implements potential_project_needs {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a potential_project_needs model instance should use the {@link potential_project_needs} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			potential_project_needsLocalServiceUtil.addpotential_project_needs(this);
		}
		else {
			potential_project_needsLocalServiceUtil.updatepotential_project_needs(this);
		}
	}
}