/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.protection_management_ratings_lkp;
import com.iucn.whp.dbservice.model.protection_management_ratings_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the protection_management_ratings_lkp service. Represents a row in the &quot;whp_protection_management_ratings_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.protection_management_ratings_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link protection_management_ratings_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see protection_management_ratings_lkpImpl
 * @see com.iucn.whp.dbservice.model.protection_management_ratings_lkp
 * @see com.iucn.whp.dbservice.model.protection_management_ratings_lkpModel
 * @generated
 */
public class protection_management_ratings_lkpModelImpl extends BaseModelImpl<protection_management_ratings_lkp>
	implements protection_management_ratings_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a protection_management_ratings_lkp model instance should use the {@link com.iucn.whp.dbservice.model.protection_management_ratings_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_protection_management_ratings_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "pm_rating", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_protection_management_ratings_lkp (id_ LONG not null primary key,pm_rating VARCHAR(50) null,description VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_protection_management_ratings_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.protection_management_ratings_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.protection_management_ratings_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.protection_management_ratings_lkp"));

	public protection_management_ratings_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return protection_management_ratings_lkp.class;
	}

	public String getModelClassName() {
		return protection_management_ratings_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("pm_rating", getPm_rating());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String pm_rating = (String)attributes.get("pm_rating");

		if (pm_rating != null) {
			setPm_rating(pm_rating);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getPm_rating() {
		if (_pm_rating == null) {
			return StringPool.BLANK;
		}
		else {
			return _pm_rating;
		}
	}

	public void setPm_rating(String pm_rating) {
		_pm_rating = pm_rating;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			protection_management_ratings_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public protection_management_ratings_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (protection_management_ratings_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		protection_management_ratings_lkpImpl protection_management_ratings_lkpImpl =
			new protection_management_ratings_lkpImpl();

		protection_management_ratings_lkpImpl.setId(getId());
		protection_management_ratings_lkpImpl.setPm_rating(getPm_rating());
		protection_management_ratings_lkpImpl.setDescription(getDescription());

		protection_management_ratings_lkpImpl.resetOriginalValues();

		return protection_management_ratings_lkpImpl;
	}

	public int compareTo(
		protection_management_ratings_lkp protection_management_ratings_lkp) {
		long primaryKey = protection_management_ratings_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		protection_management_ratings_lkp protection_management_ratings_lkp = null;

		try {
			protection_management_ratings_lkp = (protection_management_ratings_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = protection_management_ratings_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<protection_management_ratings_lkp> toCacheModel() {
		protection_management_ratings_lkpCacheModel protection_management_ratings_lkpCacheModel =
			new protection_management_ratings_lkpCacheModel();

		protection_management_ratings_lkpCacheModel.id = getId();

		protection_management_ratings_lkpCacheModel.pm_rating = getPm_rating();

		String pm_rating = protection_management_ratings_lkpCacheModel.pm_rating;

		if ((pm_rating != null) && (pm_rating.length() == 0)) {
			protection_management_ratings_lkpCacheModel.pm_rating = null;
		}

		protection_management_ratings_lkpCacheModel.description = getDescription();

		String description = protection_management_ratings_lkpCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			protection_management_ratings_lkpCacheModel.description = null;
		}

		return protection_management_ratings_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", pm_rating=");
		sb.append(getPm_rating());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"com.iucn.whp.dbservice.model.protection_management_ratings_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pm_rating</column-name><column-value><![CDATA[");
		sb.append(getPm_rating());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = protection_management_ratings_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			protection_management_ratings_lkp.class
		};
	private long _id;
	private String _pm_rating;
	private String _description;
	private protection_management_ratings_lkp _escapedModelProxy;
}