/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.prot_mgmt_best_practices;
import com.iucn.whp.dbservice.model.prot_mgmt_best_practicesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the prot_mgmt_best_practices service. Represents a row in the &quot;whp_prot_mgmt_best_practices&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.prot_mgmt_best_practicesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link prot_mgmt_best_practicesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see prot_mgmt_best_practicesImpl
 * @see com.iucn.whp.dbservice.model.prot_mgmt_best_practices
 * @see com.iucn.whp.dbservice.model.prot_mgmt_best_practicesModel
 * @generated
 */
public class prot_mgmt_best_practicesModelImpl extends BaseModelImpl<prot_mgmt_best_practices>
	implements prot_mgmt_best_practicesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prot_mgmt_best_practices model instance should use the {@link com.iucn.whp.dbservice.model.prot_mgmt_best_practices} interface instead.
	 */
	public static final String TABLE_NAME = "whp_prot_mgmt_best_practices";
	public static final Object[][] TABLE_COLUMNS = {
			{ "best_practice_id", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_prot_mgmt_best_practices (best_practice_id LONG not null primary key,assessment_version_id LONG,description STRING null)";
	public static final String TABLE_SQL_DROP = "drop table whp_prot_mgmt_best_practices";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.prot_mgmt_best_practices"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.prot_mgmt_best_practices"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.prot_mgmt_best_practices"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.prot_mgmt_best_practices"));

	public prot_mgmt_best_practicesModelImpl() {
	}

	public long getPrimaryKey() {
		return _best_practice_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setBest_practice_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_best_practice_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return prot_mgmt_best_practices.class;
	}

	public String getModelClassName() {
		return prot_mgmt_best_practices.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("best_practice_id", getBest_practice_id());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long best_practice_id = (Long)attributes.get("best_practice_id");

		if (best_practice_id != null) {
			setBest_practice_id(best_practice_id);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getBest_practice_id() {
		return _best_practice_id;
	}

	public void setBest_practice_id(long best_practice_id) {
		_best_practice_id = best_practice_id;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			prot_mgmt_best_practices.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public prot_mgmt_best_practices toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (prot_mgmt_best_practices)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		prot_mgmt_best_practicesImpl prot_mgmt_best_practicesImpl = new prot_mgmt_best_practicesImpl();

		prot_mgmt_best_practicesImpl.setBest_practice_id(getBest_practice_id());
		prot_mgmt_best_practicesImpl.setAssessment_version_id(getAssessment_version_id());
		prot_mgmt_best_practicesImpl.setDescription(getDescription());

		prot_mgmt_best_practicesImpl.resetOriginalValues();

		return prot_mgmt_best_practicesImpl;
	}

	public int compareTo(prot_mgmt_best_practices prot_mgmt_best_practices) {
		long primaryKey = prot_mgmt_best_practices.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		prot_mgmt_best_practices prot_mgmt_best_practices = null;

		try {
			prot_mgmt_best_practices = (prot_mgmt_best_practices)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = prot_mgmt_best_practices.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		prot_mgmt_best_practicesModelImpl prot_mgmt_best_practicesModelImpl = this;

		prot_mgmt_best_practicesModelImpl._originalAssessment_version_id = prot_mgmt_best_practicesModelImpl._assessment_version_id;

		prot_mgmt_best_practicesModelImpl._setOriginalAssessment_version_id = false;

		prot_mgmt_best_practicesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<prot_mgmt_best_practices> toCacheModel() {
		prot_mgmt_best_practicesCacheModel prot_mgmt_best_practicesCacheModel = new prot_mgmt_best_practicesCacheModel();

		prot_mgmt_best_practicesCacheModel.best_practice_id = getBest_practice_id();

		prot_mgmt_best_practicesCacheModel.assessment_version_id = getAssessment_version_id();

		prot_mgmt_best_practicesCacheModel.description = getDescription();

		String description = prot_mgmt_best_practicesCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			prot_mgmt_best_practicesCacheModel.description = null;
		}

		return prot_mgmt_best_practicesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{best_practice_id=");
		sb.append(getBest_practice_id());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.prot_mgmt_best_practices");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>best_practice_id</column-name><column-value><![CDATA[");
		sb.append(getBest_practice_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = prot_mgmt_best_practices.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			prot_mgmt_best_practices.class
		};
	private long _best_practice_id;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private String _description;
	private long _columnBitmask;
	private prot_mgmt_best_practices _escapedModelProxy;
}