/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.prot_mgmt_overall;
import com.iucn.whp.dbservice.model.prot_mgmt_overallModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the prot_mgmt_overall service. Represents a row in the &quot;whp_prot_mgmt_overall&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.prot_mgmt_overallModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link prot_mgmt_overallImpl}.
 * </p>
 *
 * @author alok.sen
 * @see prot_mgmt_overallImpl
 * @see com.iucn.whp.dbservice.model.prot_mgmt_overall
 * @see com.iucn.whp.dbservice.model.prot_mgmt_overallModel
 * @generated
 */
public class prot_mgmt_overallModelImpl extends BaseModelImpl<prot_mgmt_overall>
	implements prot_mgmt_overallModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prot_mgmt_overall model instance should use the {@link com.iucn.whp.dbservice.model.prot_mgmt_overall} interface instead.
	 */
	public static final String TABLE_NAME = "whp_prot_mgmt_overall";
	public static final Object[][] TABLE_COLUMNS = {
			{ "pmo_id", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "justification", Types.VARCHAR },
			{ "rating", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_prot_mgmt_overall (pmo_id LONG not null primary key,assessment_version_id LONG,justification STRING null,rating LONG)";
	public static final String TABLE_SQL_DROP = "drop table whp_prot_mgmt_overall";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.prot_mgmt_overall"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.prot_mgmt_overall"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.prot_mgmt_overall"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.prot_mgmt_overall"));

	public prot_mgmt_overallModelImpl() {
	}

	public long getPrimaryKey() {
		return _pmo_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setPmo_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_pmo_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return prot_mgmt_overall.class;
	}

	public String getModelClassName() {
		return prot_mgmt_overall.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("pmo_id", getPmo_id());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("justification", getJustification());
		attributes.put("rating", getRating());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long pmo_id = (Long)attributes.get("pmo_id");

		if (pmo_id != null) {
			setPmo_id(pmo_id);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		String justification = (String)attributes.get("justification");

		if (justification != null) {
			setJustification(justification);
		}

		Long rating = (Long)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}
	}

	public long getPmo_id() {
		return _pmo_id;
	}

	public void setPmo_id(long pmo_id) {
		_pmo_id = pmo_id;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public String getJustification() {
		if (_justification == null) {
			return StringPool.BLANK;
		}
		else {
			return _justification;
		}
	}

	public void setJustification(String justification) {
		_justification = justification;
	}

	public long getRating() {
		return _rating;
	}

	public void setRating(long rating) {
		_rating = rating;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			prot_mgmt_overall.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public prot_mgmt_overall toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (prot_mgmt_overall)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		prot_mgmt_overallImpl prot_mgmt_overallImpl = new prot_mgmt_overallImpl();

		prot_mgmt_overallImpl.setPmo_id(getPmo_id());
		prot_mgmt_overallImpl.setAssessment_version_id(getAssessment_version_id());
		prot_mgmt_overallImpl.setJustification(getJustification());
		prot_mgmt_overallImpl.setRating(getRating());

		prot_mgmt_overallImpl.resetOriginalValues();

		return prot_mgmt_overallImpl;
	}

	public int compareTo(prot_mgmt_overall prot_mgmt_overall) {
		long primaryKey = prot_mgmt_overall.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		prot_mgmt_overall prot_mgmt_overall = null;

		try {
			prot_mgmt_overall = (prot_mgmt_overall)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = prot_mgmt_overall.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		prot_mgmt_overallModelImpl prot_mgmt_overallModelImpl = this;

		prot_mgmt_overallModelImpl._originalAssessment_version_id = prot_mgmt_overallModelImpl._assessment_version_id;

		prot_mgmt_overallModelImpl._setOriginalAssessment_version_id = false;

		prot_mgmt_overallModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<prot_mgmt_overall> toCacheModel() {
		prot_mgmt_overallCacheModel prot_mgmt_overallCacheModel = new prot_mgmt_overallCacheModel();

		prot_mgmt_overallCacheModel.pmo_id = getPmo_id();

		prot_mgmt_overallCacheModel.assessment_version_id = getAssessment_version_id();

		prot_mgmt_overallCacheModel.justification = getJustification();

		String justification = prot_mgmt_overallCacheModel.justification;

		if ((justification != null) && (justification.length() == 0)) {
			prot_mgmt_overallCacheModel.justification = null;
		}

		prot_mgmt_overallCacheModel.rating = getRating();

		return prot_mgmt_overallCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{pmo_id=");
		sb.append(getPmo_id());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", justification=");
		sb.append(getJustification());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.prot_mgmt_overall");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>pmo_id</column-name><column-value><![CDATA[");
		sb.append(getPmo_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>justification</column-name><column-value><![CDATA[");
		sb.append(getJustification());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = prot_mgmt_overall.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			prot_mgmt_overall.class
		};
	private long _pmo_id;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private String _justification;
	private long _rating;
	private long _columnBitmask;
	private prot_mgmt_overall _escapedModelProxy;
}