/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp;
import com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the protection_mgmt_checklist_lkp service. Represents a row in the &quot;whp_protection_mgmt_checklist_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link protection_mgmt_checklist_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see protection_mgmt_checklist_lkpImpl
 * @see com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp
 * @see com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkpModel
 * @generated
 */
public class protection_mgmt_checklist_lkpModelImpl extends BaseModelImpl<protection_mgmt_checklist_lkp>
	implements protection_mgmt_checklist_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a protection_mgmt_checklist_lkp model instance should use the {@link com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_protection_mgmt_checklist_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "topic_id", Types.BIGINT },
			{ "topic", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_protection_mgmt_checklist_lkp (topic_id LONG not null primary key,topic VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_protection_mgmt_checklist_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp"));

	public protection_mgmt_checklist_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _topic_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setTopic_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_topic_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return protection_mgmt_checklist_lkp.class;
	}

	public String getModelClassName() {
		return protection_mgmt_checklist_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("topic_id", getTopic_id());
		attributes.put("topic", getTopic());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long topic_id = (Long)attributes.get("topic_id");

		if (topic_id != null) {
			setTopic_id(topic_id);
		}

		String topic = (String)attributes.get("topic");

		if (topic != null) {
			setTopic(topic);
		}
	}

	public long getTopic_id() {
		return _topic_id;
	}

	public void setTopic_id(long topic_id) {
		_topic_id = topic_id;
	}

	public String getTopic() {
		if (_topic == null) {
			return StringPool.BLANK;
		}
		else {
			return _topic;
		}
	}

	public void setTopic(String topic) {
		_topic = topic;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			protection_mgmt_checklist_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public protection_mgmt_checklist_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (protection_mgmt_checklist_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		protection_mgmt_checklist_lkpImpl protection_mgmt_checklist_lkpImpl = new protection_mgmt_checklist_lkpImpl();

		protection_mgmt_checklist_lkpImpl.setTopic_id(getTopic_id());
		protection_mgmt_checklist_lkpImpl.setTopic(getTopic());

		protection_mgmt_checklist_lkpImpl.resetOriginalValues();

		return protection_mgmt_checklist_lkpImpl;
	}

	public int compareTo(
		protection_mgmt_checklist_lkp protection_mgmt_checklist_lkp) {
		long primaryKey = protection_mgmt_checklist_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		protection_mgmt_checklist_lkp protection_mgmt_checklist_lkp = null;

		try {
			protection_mgmt_checklist_lkp = (protection_mgmt_checklist_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = protection_mgmt_checklist_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<protection_mgmt_checklist_lkp> toCacheModel() {
		protection_mgmt_checklist_lkpCacheModel protection_mgmt_checklist_lkpCacheModel =
			new protection_mgmt_checklist_lkpCacheModel();

		protection_mgmt_checklist_lkpCacheModel.topic_id = getTopic_id();

		protection_mgmt_checklist_lkpCacheModel.topic = getTopic();

		String topic = protection_mgmt_checklist_lkpCacheModel.topic;

		if ((topic != null) && (topic.length() == 0)) {
			protection_mgmt_checklist_lkpCacheModel.topic = null;
		}

		return protection_mgmt_checklist_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{topic_id=");
		sb.append(getTopic_id());
		sb.append(", topic=");
		sb.append(getTopic());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.protection_mgmt_checklist_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>topic_id</column-name><column-value><![CDATA[");
		sb.append(getTopic_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>topic</column-name><column-value><![CDATA[");
		sb.append(getTopic());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = protection_mgmt_checklist_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			protection_mgmt_checklist_lkp.class
		};
	private long _topic_id;
	private String _topic;
	private protection_mgmt_checklist_lkp _escapedModelProxy;
}