/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.prot_mgmt_best_practices;
import com.iucn.whp.dbservice.service.prot_mgmt_best_practicesLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the prot_mgmt_best_practices service. Represents a row in the &quot;whp_prot_mgmt_best_practices&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link prot_mgmt_best_practicesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see prot_mgmt_best_practicesImpl
 * @see com.iucn.whp.dbservice.model.prot_mgmt_best_practices
 * @generated
 */
public abstract class prot_mgmt_best_practicesBaseImpl
	extends prot_mgmt_best_practicesModelImpl
	implements prot_mgmt_best_practices {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prot_mgmt_best_practices model instance should use the {@link prot_mgmt_best_practices} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			prot_mgmt_best_practicesLocalServiceUtil.addprot_mgmt_best_practices(this);
		}
		else {
			prot_mgmt_best_practicesLocalServiceUtil.updateprot_mgmt_best_practices(this);
		}
	}
}