/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.protection_management;
import com.iucn.whp.dbservice.model.protection_managementModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the protection_management service. Represents a row in the &quot;whp_protection_management&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.protection_managementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link protection_managementImpl}.
 * </p>
 *
 * @author alok.sen
 * @see protection_managementImpl
 * @see com.iucn.whp.dbservice.model.protection_management
 * @see com.iucn.whp.dbservice.model.protection_managementModel
 * @generated
 */
public class protection_managementModelImpl extends BaseModelImpl<protection_management>
	implements protection_managementModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a protection_management model instance should use the {@link com.iucn.whp.dbservice.model.protection_management} interface instead.
	 */
	public static final String TABLE_NAME = "whp_protection_management";
	public static final Object[][] TABLE_COLUMNS = {
			{ "pm_id", Types.BIGINT },
			{ "assessment_version_id", Types.BIGINT },
			{ "topic_id", Types.BIGINT },
			{ "justification", Types.VARCHAR },
			{ "rating", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_protection_management (pm_id LONG not null primary key,assessment_version_id LONG,topic_id LONG,justification STRING null,rating LONG)";
	public static final String TABLE_SQL_DROP = "drop table whp_protection_management";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.protection_management"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.protection_management"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.protection_management"),
			true);
	public static long ASSESSMENT_VERSION_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.protection_management"));

	public protection_managementModelImpl() {
	}

	public long getPrimaryKey() {
		return _pm_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setPm_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_pm_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return protection_management.class;
	}

	public String getModelClassName() {
		return protection_management.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("pm_id", getPm_id());
		attributes.put("assessment_version_id", getAssessment_version_id());
		attributes.put("topic_id", getTopic_id());
		attributes.put("justification", getJustification());
		attributes.put("rating", getRating());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long pm_id = (Long)attributes.get("pm_id");

		if (pm_id != null) {
			setPm_id(pm_id);
		}

		Long assessment_version_id = (Long)attributes.get(
				"assessment_version_id");

		if (assessment_version_id != null) {
			setAssessment_version_id(assessment_version_id);
		}

		Long topic_id = (Long)attributes.get("topic_id");

		if (topic_id != null) {
			setTopic_id(topic_id);
		}

		String justification = (String)attributes.get("justification");

		if (justification != null) {
			setJustification(justification);
		}

		Long rating = (Long)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}
	}

	public long getPm_id() {
		return _pm_id;
	}

	public void setPm_id(long pm_id) {
		_pm_id = pm_id;
	}

	public long getAssessment_version_id() {
		return _assessment_version_id;
	}

	public void setAssessment_version_id(long assessment_version_id) {
		_columnBitmask |= ASSESSMENT_VERSION_ID_COLUMN_BITMASK;

		if (!_setOriginalAssessment_version_id) {
			_setOriginalAssessment_version_id = true;

			_originalAssessment_version_id = _assessment_version_id;
		}

		_assessment_version_id = assessment_version_id;
	}

	public long getOriginalAssessment_version_id() {
		return _originalAssessment_version_id;
	}

	public long getTopic_id() {
		return _topic_id;
	}

	public void setTopic_id(long topic_id) {
		_topic_id = topic_id;
	}

	public String getJustification() {
		if (_justification == null) {
			return StringPool.BLANK;
		}
		else {
			return _justification;
		}
	}

	public void setJustification(String justification) {
		_justification = justification;
	}

	public long getRating() {
		return _rating;
	}

	public void setRating(long rating) {
		_rating = rating;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			protection_management.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public protection_management toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (protection_management)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		protection_managementImpl protection_managementImpl = new protection_managementImpl();

		protection_managementImpl.setPm_id(getPm_id());
		protection_managementImpl.setAssessment_version_id(getAssessment_version_id());
		protection_managementImpl.setTopic_id(getTopic_id());
		protection_managementImpl.setJustification(getJustification());
		protection_managementImpl.setRating(getRating());

		protection_managementImpl.resetOriginalValues();

		return protection_managementImpl;
	}

	public int compareTo(protection_management protection_management) {
		long primaryKey = protection_management.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		protection_management protection_management = null;

		try {
			protection_management = (protection_management)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = protection_management.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		protection_managementModelImpl protection_managementModelImpl = this;

		protection_managementModelImpl._originalAssessment_version_id = protection_managementModelImpl._assessment_version_id;

		protection_managementModelImpl._setOriginalAssessment_version_id = false;

		protection_managementModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<protection_management> toCacheModel() {
		protection_managementCacheModel protection_managementCacheModel = new protection_managementCacheModel();

		protection_managementCacheModel.pm_id = getPm_id();

		protection_managementCacheModel.assessment_version_id = getAssessment_version_id();

		protection_managementCacheModel.topic_id = getTopic_id();

		protection_managementCacheModel.justification = getJustification();

		String justification = protection_managementCacheModel.justification;

		if ((justification != null) && (justification.length() == 0)) {
			protection_managementCacheModel.justification = null;
		}

		protection_managementCacheModel.rating = getRating();

		return protection_managementCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{pm_id=");
		sb.append(getPm_id());
		sb.append(", assessment_version_id=");
		sb.append(getAssessment_version_id());
		sb.append(", topic_id=");
		sb.append(getTopic_id());
		sb.append(", justification=");
		sb.append(getJustification());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.protection_management");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>pm_id</column-name><column-value><![CDATA[");
		sb.append(getPm_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assessment_version_id</column-name><column-value><![CDATA[");
		sb.append(getAssessment_version_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>topic_id</column-name><column-value><![CDATA[");
		sb.append(getTopic_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>justification</column-name><column-value><![CDATA[");
		sb.append(getJustification());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = protection_management.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			protection_management.class
		};
	private long _pm_id;
	private long _assessment_version_id;
	private long _originalAssessment_version_id;
	private boolean _setOriginalAssessment_version_id;
	private long _topic_id;
	private String _justification;
	private long _rating;
	private long _columnBitmask;
	private protection_management _escapedModelProxy;
}