/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.state_trend_whvalues;
import com.iucn.whp.dbservice.service.state_trend_whvaluesLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the state_trend_whvalues service. Represents a row in the &quot;whp_state_trend_whvalues&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link state_trend_whvaluesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see state_trend_whvaluesImpl
 * @see com.iucn.whp.dbservice.model.state_trend_whvalues
 * @generated
 */
public abstract class state_trend_whvaluesBaseImpl
	extends state_trend_whvaluesModelImpl implements state_trend_whvalues {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a state_trend_whvalues model instance should use the {@link state_trend_whvalues} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			state_trend_whvaluesLocalServiceUtil.addstate_trend_whvalues(this);
		}
		else {
			state_trend_whvaluesLocalServiceUtil.updatestate_trend_whvalues(this);
		}
	}
}