/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.thematic_lkp;
import com.iucn.whp.dbservice.model.thematic_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the thematic_lkp service. Represents a row in the &quot;whp_thematic_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.thematic_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link thematic_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see thematic_lkpImpl
 * @see com.iucn.whp.dbservice.model.thematic_lkp
 * @see com.iucn.whp.dbservice.model.thematic_lkpModel
 * @generated
 */
public class thematic_lkpModelImpl extends BaseModelImpl<thematic_lkp>
	implements thematic_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thematic_lkp model instance should use the {@link com.iucn.whp.dbservice.model.thematic_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_thematic_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "thematicid", Types.BIGINT },
			{ "thematic", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_thematic_lkp (thematicid LONG not null primary key,thematic VARCHAR(75) null,description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_thematic_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.thematic_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.thematic_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.thematic_lkp"));

	public thematic_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _thematicid;
	}

	public void setPrimaryKey(long primaryKey) {
		setThematicid(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_thematicid);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return thematic_lkp.class;
	}

	public String getModelClassName() {
		return thematic_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("thematicid", getThematicid());
		attributes.put("thematic", getThematic());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long thematicid = (Long)attributes.get("thematicid");

		if (thematicid != null) {
			setThematicid(thematicid);
		}

		String thematic = (String)attributes.get("thematic");

		if (thematic != null) {
			setThematic(thematic);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getThematicid() {
		return _thematicid;
	}

	public void setThematicid(long thematicid) {
		_thematicid = thematicid;
	}

	public String getThematic() {
		if (_thematic == null) {
			return StringPool.BLANK;
		}
		else {
			return _thematic;
		}
	}

	public void setThematic(String thematic) {
		_thematic = thematic;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			thematic_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public thematic_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (thematic_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		thematic_lkpImpl thematic_lkpImpl = new thematic_lkpImpl();

		thematic_lkpImpl.setThematicid(getThematicid());
		thematic_lkpImpl.setThematic(getThematic());
		thematic_lkpImpl.setDescription(getDescription());

		thematic_lkpImpl.resetOriginalValues();

		return thematic_lkpImpl;
	}

	public int compareTo(thematic_lkp thematic_lkp) {
		long primaryKey = thematic_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		thematic_lkp thematic_lkp = null;

		try {
			thematic_lkp = (thematic_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = thematic_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<thematic_lkp> toCacheModel() {
		thematic_lkpCacheModel thematic_lkpCacheModel = new thematic_lkpCacheModel();

		thematic_lkpCacheModel.thematicid = getThematicid();

		thematic_lkpCacheModel.thematic = getThematic();

		String thematic = thematic_lkpCacheModel.thematic;

		if ((thematic != null) && (thematic.length() == 0)) {
			thematic_lkpCacheModel.thematic = null;
		}

		thematic_lkpCacheModel.description = getDescription();

		String description = thematic_lkpCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			thematic_lkpCacheModel.description = null;
		}

		return thematic_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{thematicid=");
		sb.append(getThematicid());
		sb.append(", thematic=");
		sb.append(getThematic());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.thematic_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>thematicid</column-name><column-value><![CDATA[");
		sb.append(getThematicid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thematic</column-name><column-value><![CDATA[");
		sb.append(getThematic());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = thematic_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			thematic_lkp.class
		};
	private long _thematicid;
	private String _thematic;
	private String _description;
	private thematic_lkp _escapedModelProxy;
}