/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.threat_summary_potential;
import com.iucn.whp.dbservice.service.threat_summary_potentialLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the threat_summary_potential service. Represents a row in the &quot;whp_threat_summary_potential&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link threat_summary_potentialImpl}.
 * </p>
 *
 * @author alok.sen
 * @see threat_summary_potentialImpl
 * @see com.iucn.whp.dbservice.model.threat_summary_potential
 * @generated
 */
public abstract class threat_summary_potentialBaseImpl
	extends threat_summary_potentialModelImpl
	implements threat_summary_potential {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a threat_summary_potential model instance should use the {@link threat_summary_potential} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			threat_summary_potentialLocalServiceUtil.addthreat_summary_potential(this);
		}
		else {
			threat_summary_potentialLocalServiceUtil.updatethreat_summary_potential(this);
		}
	}
}