/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.threat_categories_lkp;
import com.iucn.whp.dbservice.model.threat_categories_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the threat_categories_lkp service. Represents a row in the &quot;whp_threat_categories_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.threat_categories_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link threat_categories_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see threat_categories_lkpImpl
 * @see com.iucn.whp.dbservice.model.threat_categories_lkp
 * @see com.iucn.whp.dbservice.model.threat_categories_lkpModel
 * @generated
 */
public class threat_categories_lkpModelImpl extends BaseModelImpl<threat_categories_lkp>
	implements threat_categories_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a threat_categories_lkp model instance should use the {@link com.iucn.whp.dbservice.model.threat_categories_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_threat_categories_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "threatCategoryid", Types.BIGINT },
			{ "threat_category", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_threat_categories_lkp (threatCategoryid LONG not null primary key,threat_category VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_threat_categories_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.threat_categories_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.threat_categories_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.threat_categories_lkp"));

	public threat_categories_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _threatCategoryid;
	}

	public void setPrimaryKey(long primaryKey) {
		setThreatCategoryid(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_threatCategoryid);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return threat_categories_lkp.class;
	}

	public String getModelClassName() {
		return threat_categories_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("threatCategoryid", getThreatCategoryid());
		attributes.put("threat_category", getThreat_category());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long threatCategoryid = (Long)attributes.get("threatCategoryid");

		if (threatCategoryid != null) {
			setThreatCategoryid(threatCategoryid);
		}

		String threat_category = (String)attributes.get("threat_category");

		if (threat_category != null) {
			setThreat_category(threat_category);
		}
	}

	public long getThreatCategoryid() {
		return _threatCategoryid;
	}

	public void setThreatCategoryid(long threatCategoryid) {
		_threatCategoryid = threatCategoryid;
	}

	public String getThreat_category() {
		if (_threat_category == null) {
			return StringPool.BLANK;
		}
		else {
			return _threat_category;
		}
	}

	public void setThreat_category(String threat_category) {
		_threat_category = threat_category;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			threat_categories_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public threat_categories_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (threat_categories_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		threat_categories_lkpImpl threat_categories_lkpImpl = new threat_categories_lkpImpl();

		threat_categories_lkpImpl.setThreatCategoryid(getThreatCategoryid());
		threat_categories_lkpImpl.setThreat_category(getThreat_category());

		threat_categories_lkpImpl.resetOriginalValues();

		return threat_categories_lkpImpl;
	}

	public int compareTo(threat_categories_lkp threat_categories_lkp) {
		long primaryKey = threat_categories_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		threat_categories_lkp threat_categories_lkp = null;

		try {
			threat_categories_lkp = (threat_categories_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = threat_categories_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<threat_categories_lkp> toCacheModel() {
		threat_categories_lkpCacheModel threat_categories_lkpCacheModel = new threat_categories_lkpCacheModel();

		threat_categories_lkpCacheModel.threatCategoryid = getThreatCategoryid();

		threat_categories_lkpCacheModel.threat_category = getThreat_category();

		String threat_category = threat_categories_lkpCacheModel.threat_category;

		if ((threat_category != null) && (threat_category.length() == 0)) {
			threat_categories_lkpCacheModel.threat_category = null;
		}

		return threat_categories_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{threatCategoryid=");
		sb.append(getThreatCategoryid());
		sb.append(", threat_category=");
		sb.append(getThreat_category());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.threat_categories_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>threatCategoryid</column-name><column-value><![CDATA[");
		sb.append(getThreatCategoryid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>threat_category</column-name><column-value><![CDATA[");
		sb.append(getThreat_category());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = threat_categories_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			threat_categories_lkp.class
		};
	private long _threatCategoryid;
	private String _threat_category;
	private threat_categories_lkp _escapedModelProxy;
}