/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.threat_summary_overall;
import com.iucn.whp.dbservice.service.threat_summary_overallLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the threat_summary_overall service. Represents a row in the &quot;whp_threat_summary_overall&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link threat_summary_overallImpl}.
 * </p>
 *
 * @author alok.sen
 * @see threat_summary_overallImpl
 * @see com.iucn.whp.dbservice.model.threat_summary_overall
 * @generated
 */
public abstract class threat_summary_overallBaseImpl
	extends threat_summary_overallModelImpl implements threat_summary_overall {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a threat_summary_overall model instance should use the {@link threat_summary_overall} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			threat_summary_overallLocalServiceUtil.addthreat_summary_overall(this);
		}
		else {
			threat_summary_overallLocalServiceUtil.updatethreat_summary_overall(this);
		}
	}
}