/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.trend_lkp;
import com.iucn.whp.dbservice.model.trend_lkpModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the trend_lkp service. Represents a row in the &quot;whp_trend_lkp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.trend_lkpModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link trend_lkpImpl}.
 * </p>
 *
 * @author alok.sen
 * @see trend_lkpImpl
 * @see com.iucn.whp.dbservice.model.trend_lkp
 * @see com.iucn.whp.dbservice.model.trend_lkpModel
 * @generated
 */
public class trend_lkpModelImpl extends BaseModelImpl<trend_lkp>
	implements trend_lkpModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trend_lkp model instance should use the {@link com.iucn.whp.dbservice.model.trend_lkp} interface instead.
	 */
	public static final String TABLE_NAME = "whp_trend_lkp";
	public static final Object[][] TABLE_COLUMNS = {
			{ "trend_id", Types.BIGINT },
			{ "trend", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_trend_lkp (trend_id LONG not null primary key,trend VARCHAR(50) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_trend_lkp";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.trend_lkp"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.trend_lkp"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.trend_lkp"));

	public trend_lkpModelImpl() {
	}

	public long getPrimaryKey() {
		return _trend_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setTrend_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_trend_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return trend_lkp.class;
	}

	public String getModelClassName() {
		return trend_lkp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("trend_id", getTrend_id());
		attributes.put("trend", getTrend());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long trend_id = (Long)attributes.get("trend_id");

		if (trend_id != null) {
			setTrend_id(trend_id);
		}

		String trend = (String)attributes.get("trend");

		if (trend != null) {
			setTrend(trend);
		}
	}

	public long getTrend_id() {
		return _trend_id;
	}

	public void setTrend_id(long trend_id) {
		_trend_id = trend_id;
	}

	public String getTrend() {
		if (_trend == null) {
			return StringPool.BLANK;
		}
		else {
			return _trend;
		}
	}

	public void setTrend(String trend) {
		_trend = trend;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			trend_lkp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public trend_lkp toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (trend_lkp)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		trend_lkpImpl trend_lkpImpl = new trend_lkpImpl();

		trend_lkpImpl.setTrend_id(getTrend_id());
		trend_lkpImpl.setTrend(getTrend());

		trend_lkpImpl.resetOriginalValues();

		return trend_lkpImpl;
	}

	public int compareTo(trend_lkp trend_lkp) {
		long primaryKey = trend_lkp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		trend_lkp trend_lkp = null;

		try {
			trend_lkp = (trend_lkp)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = trend_lkp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<trend_lkp> toCacheModel() {
		trend_lkpCacheModel trend_lkpCacheModel = new trend_lkpCacheModel();

		trend_lkpCacheModel.trend_id = getTrend_id();

		trend_lkpCacheModel.trend = getTrend();

		String trend = trend_lkpCacheModel.trend;

		if ((trend != null) && (trend.length() == 0)) {
			trend_lkpCacheModel.trend = null;
		}

		return trend_lkpCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{trend_id=");
		sb.append(getTrend_id());
		sb.append(", trend=");
		sb.append(getTrend());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.trend_lkp");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>trend_id</column-name><column-value><![CDATA[");
		sb.append(getTrend_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trend</column-name><column-value><![CDATA[");
		sb.append(getTrend());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = trend_lkp.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			trend_lkp.class
		};
	private long _trend_id;
	private String _trend;
	private trend_lkp _escapedModelProxy;
}