/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.understanding_benefits;
import com.iucn.whp.dbservice.service.understanding_benefitsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the understanding_benefits service. Represents a row in the &quot;whp_understanding_benefits&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link understanding_benefitsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see understanding_benefitsImpl
 * @see com.iucn.whp.dbservice.model.understanding_benefits
 * @generated
 */
public abstract class understanding_benefitsBaseImpl
	extends understanding_benefitsModelImpl implements understanding_benefits {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a understanding_benefits model instance should use the {@link understanding_benefits} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			understanding_benefitsLocalServiceUtil.addunderstanding_benefits(this);
		}
		else {
			understanding_benefitsLocalServiceUtil.updateunderstanding_benefits(this);
		}
	}
}