/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.unesco_region;
import com.iucn.whp.dbservice.model.unesco_regionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the unesco_region service. Represents a row in the &quot;whp_unesco_region&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.unesco_regionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link unesco_regionImpl}.
 * </p>
 *
 * @author alok.sen
 * @see unesco_regionImpl
 * @see com.iucn.whp.dbservice.model.unesco_region
 * @see com.iucn.whp.dbservice.model.unesco_regionModel
 * @generated
 */
public class unesco_regionModelImpl extends BaseModelImpl<unesco_region>
	implements unesco_regionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unesco_region model instance should use the {@link com.iucn.whp.dbservice.model.unesco_region} interface instead.
	 */
	public static final String TABLE_NAME = "whp_unesco_region";
	public static final Object[][] TABLE_COLUMNS = {
			{ "unesco_region_id", Types.INTEGER },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_unesco_region (unesco_region_id INTEGER not null primary key,name VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_unesco_region";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.unesco_region"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.unesco_region"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.unesco_region"));

	public unesco_regionModelImpl() {
	}

	public int getPrimaryKey() {
		return _unesco_region_id;
	}

	public void setPrimaryKey(int primaryKey) {
		setUnesco_region_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_unesco_region_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return unesco_region.class;
	}

	public String getModelClassName() {
		return unesco_region.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("unesco_region_id", getUnesco_region_id());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer unesco_region_id = (Integer)attributes.get("unesco_region_id");

		if (unesco_region_id != null) {
			setUnesco_region_id(unesco_region_id);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	public int getUnesco_region_id() {
		return _unesco_region_id;
	}

	public void setUnesco_region_id(int unesco_region_id) {
		_unesco_region_id = unesco_region_id;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	@Override
	public unesco_region toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (unesco_region)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		unesco_regionImpl unesco_regionImpl = new unesco_regionImpl();

		unesco_regionImpl.setUnesco_region_id(getUnesco_region_id());
		unesco_regionImpl.setName(getName());

		unesco_regionImpl.resetOriginalValues();

		return unesco_regionImpl;
	}

	public int compareTo(unesco_region unesco_region) {
		int primaryKey = unesco_region.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		unesco_region unesco_region = null;

		try {
			unesco_region = (unesco_region)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = unesco_region.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<unesco_region> toCacheModel() {
		unesco_regionCacheModel unesco_regionCacheModel = new unesco_regionCacheModel();

		unesco_regionCacheModel.unesco_region_id = getUnesco_region_id();

		unesco_regionCacheModel.name = getName();

		String name = unesco_regionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			unesco_regionCacheModel.name = null;
		}

		return unesco_regionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{unesco_region_id=");
		sb.append(getUnesco_region_id());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.unesco_region");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>unesco_region_id</column-name><column-value><![CDATA[");
		sb.append(getUnesco_region_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = unesco_region.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			unesco_region.class
		};
	private int _unesco_region_id;
	private String _name;
	private unesco_region _escapedModelProxy;
}