/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_dsocr;
import com.iucn.whp.dbservice.model.whp_sites_dsocrModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the whp_sites_dsocr service. Represents a row in the &quot;whp_whp_sites_dsocr&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.whp_sites_dsocrModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_dsocrImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_dsocrImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_dsocr
 * @see com.iucn.whp.dbservice.model.whp_sites_dsocrModel
 * @generated
 */
public class whp_sites_dsocrModelImpl extends BaseModelImpl<whp_sites_dsocr>
	implements whp_sites_dsocrModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_dsocr model instance should use the {@link com.iucn.whp.dbservice.model.whp_sites_dsocr} interface instead.
	 */
	public static final String TABLE_NAME = "whp_whp_sites_dsocr";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whp_sites_dsocr_id", Types.BIGINT },
			{ "site_id", Types.BIGINT },
			{ "state_description", Types.VARCHAR },
			{ "dsocr_date", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_whp_sites_dsocr (whp_sites_dsocr_id LONG not null primary key,site_id LONG,state_description VARCHAR(500) null,dsocr_date DATE null)";
	public static final String TABLE_SQL_DROP = "drop table whp_whp_sites_dsocr";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_dsocr"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_dsocr"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.whp_sites_dsocr"));

	public whp_sites_dsocrModelImpl() {
	}

	public long getPrimaryKey() {
		return _whp_sites_dsocr_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setWhp_sites_dsocr_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_whp_sites_dsocr_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return whp_sites_dsocr.class;
	}

	public String getModelClassName() {
		return whp_sites_dsocr.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whp_sites_dsocr_id", getWhp_sites_dsocr_id());
		attributes.put("site_id", getSite_id());
		attributes.put("state_description", getState_description());
		attributes.put("dsocr_date", getDsocr_date());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long whp_sites_dsocr_id = (Long)attributes.get("whp_sites_dsocr_id");

		if (whp_sites_dsocr_id != null) {
			setWhp_sites_dsocr_id(whp_sites_dsocr_id);
		}

		Long site_id = (Long)attributes.get("site_id");

		if (site_id != null) {
			setSite_id(site_id);
		}

		String state_description = (String)attributes.get("state_description");

		if (state_description != null) {
			setState_description(state_description);
		}

		Date dsocr_date = (Date)attributes.get("dsocr_date");

		if (dsocr_date != null) {
			setDsocr_date(dsocr_date);
		}
	}

	public long getWhp_sites_dsocr_id() {
		return _whp_sites_dsocr_id;
	}

	public void setWhp_sites_dsocr_id(long whp_sites_dsocr_id) {
		_whp_sites_dsocr_id = whp_sites_dsocr_id;
	}

	public long getSite_id() {
		return _site_id;
	}

	public void setSite_id(long site_id) {
		_site_id = site_id;
	}

	public String getState_description() {
		if (_state_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _state_description;
		}
	}

	public void setState_description(String state_description) {
		_state_description = state_description;
	}

	public Date getDsocr_date() {
		return _dsocr_date;
	}

	public void setDsocr_date(Date dsocr_date) {
		_dsocr_date = dsocr_date;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			whp_sites_dsocr.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public whp_sites_dsocr toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (whp_sites_dsocr)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		whp_sites_dsocrImpl whp_sites_dsocrImpl = new whp_sites_dsocrImpl();

		whp_sites_dsocrImpl.setWhp_sites_dsocr_id(getWhp_sites_dsocr_id());
		whp_sites_dsocrImpl.setSite_id(getSite_id());
		whp_sites_dsocrImpl.setState_description(getState_description());
		whp_sites_dsocrImpl.setDsocr_date(getDsocr_date());

		whp_sites_dsocrImpl.resetOriginalValues();

		return whp_sites_dsocrImpl;
	}

	public int compareTo(whp_sites_dsocr whp_sites_dsocr) {
		long primaryKey = whp_sites_dsocr.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		whp_sites_dsocr whp_sites_dsocr = null;

		try {
			whp_sites_dsocr = (whp_sites_dsocr)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = whp_sites_dsocr.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<whp_sites_dsocr> toCacheModel() {
		whp_sites_dsocrCacheModel whp_sites_dsocrCacheModel = new whp_sites_dsocrCacheModel();

		whp_sites_dsocrCacheModel.whp_sites_dsocr_id = getWhp_sites_dsocr_id();

		whp_sites_dsocrCacheModel.site_id = getSite_id();

		whp_sites_dsocrCacheModel.state_description = getState_description();

		String state_description = whp_sites_dsocrCacheModel.state_description;

		if ((state_description != null) && (state_description.length() == 0)) {
			whp_sites_dsocrCacheModel.state_description = null;
		}

		Date dsocr_date = getDsocr_date();

		if (dsocr_date != null) {
			whp_sites_dsocrCacheModel.dsocr_date = dsocr_date.getTime();
		}
		else {
			whp_sites_dsocrCacheModel.dsocr_date = Long.MIN_VALUE;
		}

		return whp_sites_dsocrCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{whp_sites_dsocr_id=");
		sb.append(getWhp_sites_dsocr_id());
		sb.append(", site_id=");
		sb.append(getSite_id());
		sb.append(", state_description=");
		sb.append(getState_description());
		sb.append(", dsocr_date=");
		sb.append(getDsocr_date());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.whp_sites_dsocr");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whp_sites_dsocr_id</column-name><column-value><![CDATA[");
		sb.append(getWhp_sites_dsocr_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>site_id</column-name><column-value><![CDATA[");
		sb.append(getSite_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>state_description</column-name><column-value><![CDATA[");
		sb.append(getState_description());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dsocr_date</column-name><column-value><![CDATA[");
		sb.append(getDsocr_date());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = whp_sites_dsocr.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			whp_sites_dsocr.class
		};
	private long _whp_sites_dsocr_id;
	private long _site_id;
	private String _state_description;
	private Date _dsocr_date;
	private whp_sites_dsocr _escapedModelProxy;
}