/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_soouv;
import com.iucn.whp.dbservice.model.whp_sites_soouvModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the whp_sites_soouv service. Represents a row in the &quot;whp_whp_sites_soouv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.whp_sites_soouvModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_soouvImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_soouvImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_soouv
 * @see com.iucn.whp.dbservice.model.whp_sites_soouvModel
 * @generated
 */
public class whp_sites_soouvModelImpl extends BaseModelImpl<whp_sites_soouv>
	implements whp_sites_soouvModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_soouv model instance should use the {@link com.iucn.whp.dbservice.model.whp_sites_soouv} interface instead.
	 */
	public static final String TABLE_NAME = "whp_whp_sites_soouv";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whp_sites_soouv_id", Types.BIGINT },
			{ "site_id", Types.BIGINT },
			{ "description_en", Types.VARCHAR },
			{ "description_fr", Types.VARCHAR },
			{ "soouv_date", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_whp_sites_soouv (whp_sites_soouv_id LONG not null primary key,site_id LONG,description_en VARCHAR(500) null,description_fr VARCHAR(500) null,soouv_date DATE null)";
	public static final String TABLE_SQL_DROP = "drop table whp_whp_sites_soouv";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_soouv"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_soouv"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.whp_sites_soouv"));

	public whp_sites_soouvModelImpl() {
	}

	public long getPrimaryKey() {
		return _whp_sites_soouv_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setWhp_sites_soouv_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_whp_sites_soouv_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return whp_sites_soouv.class;
	}

	public String getModelClassName() {
		return whp_sites_soouv.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whp_sites_soouv_id", getWhp_sites_soouv_id());
		attributes.put("site_id", getSite_id());
		attributes.put("description_en", getDescription_en());
		attributes.put("description_fr", getDescription_fr());
		attributes.put("soouv_date", getSoouv_date());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long whp_sites_soouv_id = (Long)attributes.get("whp_sites_soouv_id");

		if (whp_sites_soouv_id != null) {
			setWhp_sites_soouv_id(whp_sites_soouv_id);
		}

		Long site_id = (Long)attributes.get("site_id");

		if (site_id != null) {
			setSite_id(site_id);
		}

		String description_en = (String)attributes.get("description_en");

		if (description_en != null) {
			setDescription_en(description_en);
		}

		String description_fr = (String)attributes.get("description_fr");

		if (description_fr != null) {
			setDescription_fr(description_fr);
		}

		Date soouv_date = (Date)attributes.get("soouv_date");

		if (soouv_date != null) {
			setSoouv_date(soouv_date);
		}
	}

	public long getWhp_sites_soouv_id() {
		return _whp_sites_soouv_id;
	}

	public void setWhp_sites_soouv_id(long whp_sites_soouv_id) {
		_whp_sites_soouv_id = whp_sites_soouv_id;
	}

	public long getSite_id() {
		return _site_id;
	}

	public void setSite_id(long site_id) {
		_site_id = site_id;
	}

	public String getDescription_en() {
		if (_description_en == null) {
			return StringPool.BLANK;
		}
		else {
			return _description_en;
		}
	}

	public void setDescription_en(String description_en) {
		_description_en = description_en;
	}

	public String getDescription_fr() {
		if (_description_fr == null) {
			return StringPool.BLANK;
		}
		else {
			return _description_fr;
		}
	}

	public void setDescription_fr(String description_fr) {
		_description_fr = description_fr;
	}

	public Date getSoouv_date() {
		return _soouv_date;
	}

	public void setSoouv_date(Date soouv_date) {
		_soouv_date = soouv_date;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			whp_sites_soouv.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public whp_sites_soouv toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (whp_sites_soouv)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		whp_sites_soouvImpl whp_sites_soouvImpl = new whp_sites_soouvImpl();

		whp_sites_soouvImpl.setWhp_sites_soouv_id(getWhp_sites_soouv_id());
		whp_sites_soouvImpl.setSite_id(getSite_id());
		whp_sites_soouvImpl.setDescription_en(getDescription_en());
		whp_sites_soouvImpl.setDescription_fr(getDescription_fr());
		whp_sites_soouvImpl.setSoouv_date(getSoouv_date());

		whp_sites_soouvImpl.resetOriginalValues();

		return whp_sites_soouvImpl;
	}

	public int compareTo(whp_sites_soouv whp_sites_soouv) {
		long primaryKey = whp_sites_soouv.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		whp_sites_soouv whp_sites_soouv = null;

		try {
			whp_sites_soouv = (whp_sites_soouv)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = whp_sites_soouv.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<whp_sites_soouv> toCacheModel() {
		whp_sites_soouvCacheModel whp_sites_soouvCacheModel = new whp_sites_soouvCacheModel();

		whp_sites_soouvCacheModel.whp_sites_soouv_id = getWhp_sites_soouv_id();

		whp_sites_soouvCacheModel.site_id = getSite_id();

		whp_sites_soouvCacheModel.description_en = getDescription_en();

		String description_en = whp_sites_soouvCacheModel.description_en;

		if ((description_en != null) && (description_en.length() == 0)) {
			whp_sites_soouvCacheModel.description_en = null;
		}

		whp_sites_soouvCacheModel.description_fr = getDescription_fr();

		String description_fr = whp_sites_soouvCacheModel.description_fr;

		if ((description_fr != null) && (description_fr.length() == 0)) {
			whp_sites_soouvCacheModel.description_fr = null;
		}

		Date soouv_date = getSoouv_date();

		if (soouv_date != null) {
			whp_sites_soouvCacheModel.soouv_date = soouv_date.getTime();
		}
		else {
			whp_sites_soouvCacheModel.soouv_date = Long.MIN_VALUE;
		}

		return whp_sites_soouvCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{whp_sites_soouv_id=");
		sb.append(getWhp_sites_soouv_id());
		sb.append(", site_id=");
		sb.append(getSite_id());
		sb.append(", description_en=");
		sb.append(getDescription_en());
		sb.append(", description_fr=");
		sb.append(getDescription_fr());
		sb.append(", soouv_date=");
		sb.append(getSoouv_date());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.whp_sites_soouv");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whp_sites_soouv_id</column-name><column-value><![CDATA[");
		sb.append(getWhp_sites_soouv_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>site_id</column-name><column-value><![CDATA[");
		sb.append(getSite_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description_en</column-name><column-value><![CDATA[");
		sb.append(getDescription_en());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description_fr</column-name><column-value><![CDATA[");
		sb.append(getDescription_fr());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>soouv_date</column-name><column-value><![CDATA[");
		sb.append(getSoouv_date());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = whp_sites_soouv.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			whp_sites_soouv.class
		};
	private long _whp_sites_soouv_id;
	private long _site_id;
	private String _description_en;
	private String _description_fr;
	private Date _soouv_date;
	private whp_sites_soouv _escapedModelProxy;
}