/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_site_danger_list;
import com.iucn.whp.dbservice.service.whp_site_danger_listLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the whp_site_danger_list service. Represents a row in the &quot;whp_whp_site_danger_list&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_site_danger_listImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_site_danger_listImpl
 * @see com.iucn.whp.dbservice.model.whp_site_danger_list
 * @generated
 */
public abstract class whp_site_danger_listBaseImpl
	extends whp_site_danger_listModelImpl implements whp_site_danger_list {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_site_danger_list model instance should use the {@link whp_site_danger_list} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			whp_site_danger_listLocalServiceUtil.addwhp_site_danger_list(this);
		}
		else {
			whp_site_danger_listLocalServiceUtil.updatewhp_site_danger_list(this);
		}
	}
}