/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_external_documents;
import com.iucn.whp.dbservice.service.whp_sites_external_documentsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the whp_sites_external_documents service. Represents a row in the &quot;whp_whp_sites_external_documents&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_external_documentsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_external_documentsImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_external_documents
 * @generated
 */
public abstract class whp_sites_external_documentsBaseImpl
	extends whp_sites_external_documentsModelImpl
	implements whp_sites_external_documents {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_external_documents model instance should use the {@link whp_sites_external_documents} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			whp_sites_external_documentsLocalServiceUtil.addwhp_sites_external_documents(this);
		}
		else {
			whp_sites_external_documentsLocalServiceUtil.updatewhp_sites_external_documents(this);
		}
	}
}