/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_visitors;
import com.iucn.whp.dbservice.model.whp_sites_visitorsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the whp_sites_visitors service. Represents a row in the &quot;whp_whp_sites_visitors&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.whp_sites_visitorsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_visitorsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_visitorsImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_visitors
 * @see com.iucn.whp.dbservice.model.whp_sites_visitorsModel
 * @generated
 */
public class whp_sites_visitorsModelImpl extends BaseModelImpl<whp_sites_visitors>
	implements whp_sites_visitorsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_visitors model instance should use the {@link com.iucn.whp.dbservice.model.whp_sites_visitors} interface instead.
	 */
	public static final String TABLE_NAME = "whp_whp_sites_visitors";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whp_sites_visitors_id", Types.BIGINT },
			{ "site_id", Types.BIGINT },
			{ "visitor_count", Types.BIGINT },
			{ "record_date", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_whp_sites_visitors (whp_sites_visitors_id LONG not null primary key,site_id LONG,visitor_count LONG,record_date DATE null)";
	public static final String TABLE_SQL_DROP = "drop table whp_whp_sites_visitors";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_visitors"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_visitors"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.whp_sites_visitors"));

	public whp_sites_visitorsModelImpl() {
	}

	public long getPrimaryKey() {
		return _whp_sites_visitors_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setWhp_sites_visitors_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_whp_sites_visitors_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return whp_sites_visitors.class;
	}

	public String getModelClassName() {
		return whp_sites_visitors.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whp_sites_visitors_id", getWhp_sites_visitors_id());
		attributes.put("site_id", getSite_id());
		attributes.put("visitor_count", getVisitor_count());
		attributes.put("record_date", getRecord_date());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long whp_sites_visitors_id = (Long)attributes.get(
				"whp_sites_visitors_id");

		if (whp_sites_visitors_id != null) {
			setWhp_sites_visitors_id(whp_sites_visitors_id);
		}

		Long site_id = (Long)attributes.get("site_id");

		if (site_id != null) {
			setSite_id(site_id);
		}

		Long visitor_count = (Long)attributes.get("visitor_count");

		if (visitor_count != null) {
			setVisitor_count(visitor_count);
		}

		Date record_date = (Date)attributes.get("record_date");

		if (record_date != null) {
			setRecord_date(record_date);
		}
	}

	public long getWhp_sites_visitors_id() {
		return _whp_sites_visitors_id;
	}

	public void setWhp_sites_visitors_id(long whp_sites_visitors_id) {
		_whp_sites_visitors_id = whp_sites_visitors_id;
	}

	public long getSite_id() {
		return _site_id;
	}

	public void setSite_id(long site_id) {
		_site_id = site_id;
	}

	public long getVisitor_count() {
		return _visitor_count;
	}

	public void setVisitor_count(long visitor_count) {
		_visitor_count = visitor_count;
	}

	public Date getRecord_date() {
		return _record_date;
	}

	public void setRecord_date(Date record_date) {
		_record_date = record_date;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			whp_sites_visitors.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public whp_sites_visitors toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (whp_sites_visitors)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		whp_sites_visitorsImpl whp_sites_visitorsImpl = new whp_sites_visitorsImpl();

		whp_sites_visitorsImpl.setWhp_sites_visitors_id(getWhp_sites_visitors_id());
		whp_sites_visitorsImpl.setSite_id(getSite_id());
		whp_sites_visitorsImpl.setVisitor_count(getVisitor_count());
		whp_sites_visitorsImpl.setRecord_date(getRecord_date());

		whp_sites_visitorsImpl.resetOriginalValues();

		return whp_sites_visitorsImpl;
	}

	public int compareTo(whp_sites_visitors whp_sites_visitors) {
		long primaryKey = whp_sites_visitors.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		whp_sites_visitors whp_sites_visitors = null;

		try {
			whp_sites_visitors = (whp_sites_visitors)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = whp_sites_visitors.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<whp_sites_visitors> toCacheModel() {
		whp_sites_visitorsCacheModel whp_sites_visitorsCacheModel = new whp_sites_visitorsCacheModel();

		whp_sites_visitorsCacheModel.whp_sites_visitors_id = getWhp_sites_visitors_id();

		whp_sites_visitorsCacheModel.site_id = getSite_id();

		whp_sites_visitorsCacheModel.visitor_count = getVisitor_count();

		Date record_date = getRecord_date();

		if (record_date != null) {
			whp_sites_visitorsCacheModel.record_date = record_date.getTime();
		}
		else {
			whp_sites_visitorsCacheModel.record_date = Long.MIN_VALUE;
		}

		return whp_sites_visitorsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{whp_sites_visitors_id=");
		sb.append(getWhp_sites_visitors_id());
		sb.append(", site_id=");
		sb.append(getSite_id());
		sb.append(", visitor_count=");
		sb.append(getVisitor_count());
		sb.append(", record_date=");
		sb.append(getRecord_date());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.whp_sites_visitors");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whp_sites_visitors_id</column-name><column-value><![CDATA[");
		sb.append(getWhp_sites_visitors_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>site_id</column-name><column-value><![CDATA[");
		sb.append(getSite_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>visitor_count</column-name><column-value><![CDATA[");
		sb.append(getVisitor_count());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>record_date</column-name><column-value><![CDATA[");
		sb.append(getRecord_date());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = whp_sites_visitors.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			whp_sites_visitors.class
		};
	private long _whp_sites_visitors_id;
	private long _site_id;
	private long _visitor_count;
	private Date _record_date;
	private whp_sites_visitors _escapedModelProxy;
}