/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_soc_reports;
import com.iucn.whp.dbservice.service.whp_sites_soc_reportsLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the whp_sites_soc_reports service. Represents a row in the &quot;whp_whp_sites_soc_reports&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_soc_reportsImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_soc_reportsImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_soc_reports
 * @generated
 */
public abstract class whp_sites_soc_reportsBaseImpl
	extends whp_sites_soc_reportsModelImpl implements whp_sites_soc_reports {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_soc_reports model instance should use the {@link whp_sites_soc_reports} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			whp_sites_soc_reportsLocalServiceUtil.addwhp_sites_soc_reports(this);
		}
		else {
			whp_sites_soc_reportsLocalServiceUtil.updatewhp_sites_soc_reports(this);
		}
	}
}