/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_indigenous_communities;
import com.iucn.whp.dbservice.model.whp_sites_indigenous_communitiesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the whp_sites_indigenous_communities service. Represents a row in the &quot;whp_whp_sites_indigenous_communities&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.whp_sites_indigenous_communitiesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_indigenous_communitiesImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_indigenous_communitiesImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_indigenous_communities
 * @see com.iucn.whp.dbservice.model.whp_sites_indigenous_communitiesModel
 * @generated
 */
public class whp_sites_indigenous_communitiesModelImpl extends BaseModelImpl<whp_sites_indigenous_communities>
	implements whp_sites_indigenous_communitiesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_indigenous_communities model instance should use the {@link com.iucn.whp.dbservice.model.whp_sites_indigenous_communities} interface instead.
	 */
	public static final String TABLE_NAME = "whp_whp_sites_indigenous_communities";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whp_sites_indigenous_communities_id", Types.BIGINT },
			{ "site_id", Types.BIGINT },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_whp_sites_indigenous_communities (whp_sites_indigenous_communities_id LONG not null primary key,site_id LONG,description VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table whp_whp_sites_indigenous_communities";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_indigenous_communities"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_indigenous_communities"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.whp_sites_indigenous_communities"));

	public whp_sites_indigenous_communitiesModelImpl() {
	}

	public long getPrimaryKey() {
		return _whp_sites_indigenous_communities_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setWhp_sites_indigenous_communities_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_whp_sites_indigenous_communities_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return whp_sites_indigenous_communities.class;
	}

	public String getModelClassName() {
		return whp_sites_indigenous_communities.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whp_sites_indigenous_communities_id",
			getWhp_sites_indigenous_communities_id());
		attributes.put("site_id", getSite_id());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long whp_sites_indigenous_communities_id = (Long)attributes.get(
				"whp_sites_indigenous_communities_id");

		if (whp_sites_indigenous_communities_id != null) {
			setWhp_sites_indigenous_communities_id(whp_sites_indigenous_communities_id);
		}

		Long site_id = (Long)attributes.get("site_id");

		if (site_id != null) {
			setSite_id(site_id);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	public long getWhp_sites_indigenous_communities_id() {
		return _whp_sites_indigenous_communities_id;
	}

	public void setWhp_sites_indigenous_communities_id(
		long whp_sites_indigenous_communities_id) {
		_whp_sites_indigenous_communities_id = whp_sites_indigenous_communities_id;
	}

	public long getSite_id() {
		return _site_id;
	}

	public void setSite_id(long site_id) {
		_site_id = site_id;
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			whp_sites_indigenous_communities.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public whp_sites_indigenous_communities toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (whp_sites_indigenous_communities)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		whp_sites_indigenous_communitiesImpl whp_sites_indigenous_communitiesImpl =
			new whp_sites_indigenous_communitiesImpl();

		whp_sites_indigenous_communitiesImpl.setWhp_sites_indigenous_communities_id(getWhp_sites_indigenous_communities_id());
		whp_sites_indigenous_communitiesImpl.setSite_id(getSite_id());
		whp_sites_indigenous_communitiesImpl.setDescription(getDescription());

		whp_sites_indigenous_communitiesImpl.resetOriginalValues();

		return whp_sites_indigenous_communitiesImpl;
	}

	public int compareTo(
		whp_sites_indigenous_communities whp_sites_indigenous_communities) {
		long primaryKey = whp_sites_indigenous_communities.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		whp_sites_indigenous_communities whp_sites_indigenous_communities = null;

		try {
			whp_sites_indigenous_communities = (whp_sites_indigenous_communities)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = whp_sites_indigenous_communities.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<whp_sites_indigenous_communities> toCacheModel() {
		whp_sites_indigenous_communitiesCacheModel whp_sites_indigenous_communitiesCacheModel =
			new whp_sites_indigenous_communitiesCacheModel();

		whp_sites_indigenous_communitiesCacheModel.whp_sites_indigenous_communities_id = getWhp_sites_indigenous_communities_id();

		whp_sites_indigenous_communitiesCacheModel.site_id = getSite_id();

		whp_sites_indigenous_communitiesCacheModel.description = getDescription();

		String description = whp_sites_indigenous_communitiesCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			whp_sites_indigenous_communitiesCacheModel.description = null;
		}

		return whp_sites_indigenous_communitiesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{whp_sites_indigenous_communities_id=");
		sb.append(getWhp_sites_indigenous_communities_id());
		sb.append(", site_id=");
		sb.append(getSite_id());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"com.iucn.whp.dbservice.model.whp_sites_indigenous_communities");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whp_sites_indigenous_communities_id</column-name><column-value><![CDATA[");
		sb.append(getWhp_sites_indigenous_communities_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>site_id</column-name><column-value><![CDATA[");
		sb.append(getSite_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = whp_sites_indigenous_communities.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			whp_sites_indigenous_communities.class
		};
	private long _whp_sites_indigenous_communities_id;
	private long _site_id;
	private String _description;
	private whp_sites_indigenous_communities _escapedModelProxy;
}