/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.iucn.whp.dbservice.model.impl;

import com.iucn.whp.dbservice.model.whp_sites_inscription_date;
import com.iucn.whp.dbservice.model.whp_sites_inscription_dateModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the whp_sites_inscription_date service. Represents a row in the &quot;whp_whp_sites_inscription_date&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.iucn.whp.dbservice.model.whp_sites_inscription_dateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link whp_sites_inscription_dateImpl}.
 * </p>
 *
 * @author alok.sen
 * @see whp_sites_inscription_dateImpl
 * @see com.iucn.whp.dbservice.model.whp_sites_inscription_date
 * @see com.iucn.whp.dbservice.model.whp_sites_inscription_dateModel
 * @generated
 */
public class whp_sites_inscription_dateModelImpl extends BaseModelImpl<whp_sites_inscription_date>
	implements whp_sites_inscription_dateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a whp_sites_inscription_date model instance should use the {@link com.iucn.whp.dbservice.model.whp_sites_inscription_date} interface instead.
	 */
	public static final String TABLE_NAME = "whp_whp_sites_inscription_date";
	public static final Object[][] TABLE_COLUMNS = {
			{ "whp_sites_inscription_date_id", Types.BIGINT },
			{ "site_id", Types.BIGINT },
			{ "inscription_type_id", Types.INTEGER },
			{ "reference_no", Types.VARCHAR },
			{ "inscription_date", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table whp_whp_sites_inscription_date (whp_sites_inscription_date_id LONG not null primary key,site_id LONG,inscription_type_id INTEGER,reference_no VARCHAR(100) null,inscription_date DATE null)";
	public static final String TABLE_SQL_DROP = "drop table whp_whp_sites_inscription_date";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_inscription_date"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.iucn.whp.dbservice.model.whp_sites_inscription_date"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.iucn.whp.dbservice.model.whp_sites_inscription_date"),
			true);
	public static long INSCRIPTION_TYPE_ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.iucn.whp.dbservice.model.whp_sites_inscription_date"));

	public whp_sites_inscription_dateModelImpl() {
	}

	public long getPrimaryKey() {
		return _whp_sites_inscription_date_id;
	}

	public void setPrimaryKey(long primaryKey) {
		setWhp_sites_inscription_date_id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_whp_sites_inscription_date_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return whp_sites_inscription_date.class;
	}

	public String getModelClassName() {
		return whp_sites_inscription_date.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("whp_sites_inscription_date_id",
			getWhp_sites_inscription_date_id());
		attributes.put("site_id", getSite_id());
		attributes.put("inscription_type_id", getInscription_type_id());
		attributes.put("reference_no", getReference_no());
		attributes.put("inscription_date", getInscription_date());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long whp_sites_inscription_date_id = (Long)attributes.get(
				"whp_sites_inscription_date_id");

		if (whp_sites_inscription_date_id != null) {
			setWhp_sites_inscription_date_id(whp_sites_inscription_date_id);
		}

		Long site_id = (Long)attributes.get("site_id");

		if (site_id != null) {
			setSite_id(site_id);
		}

		Integer inscription_type_id = (Integer)attributes.get(
				"inscription_type_id");

		if (inscription_type_id != null) {
			setInscription_type_id(inscription_type_id);
		}

		String reference_no = (String)attributes.get("reference_no");

		if (reference_no != null) {
			setReference_no(reference_no);
		}

		Date inscription_date = (Date)attributes.get("inscription_date");

		if (inscription_date != null) {
			setInscription_date(inscription_date);
		}
	}

	public long getWhp_sites_inscription_date_id() {
		return _whp_sites_inscription_date_id;
	}

	public void setWhp_sites_inscription_date_id(
		long whp_sites_inscription_date_id) {
		_whp_sites_inscription_date_id = whp_sites_inscription_date_id;
	}

	public long getSite_id() {
		return _site_id;
	}

	public void setSite_id(long site_id) {
		_site_id = site_id;
	}

	public int getInscription_type_id() {
		return _inscription_type_id;
	}

	public void setInscription_type_id(int inscription_type_id) {
		_columnBitmask |= INSCRIPTION_TYPE_ID_COLUMN_BITMASK;

		if (!_setOriginalInscription_type_id) {
			_setOriginalInscription_type_id = true;

			_originalInscription_type_id = _inscription_type_id;
		}

		_inscription_type_id = inscription_type_id;
	}

	public int getOriginalInscription_type_id() {
		return _originalInscription_type_id;
	}

	public String getReference_no() {
		if (_reference_no == null) {
			return StringPool.BLANK;
		}
		else {
			return _reference_no;
		}
	}

	public void setReference_no(String reference_no) {
		_reference_no = reference_no;
	}

	public Date getInscription_date() {
		return _inscription_date;
	}

	public void setInscription_date(Date inscription_date) {
		_inscription_date = inscription_date;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			whp_sites_inscription_date.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public whp_sites_inscription_date toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (whp_sites_inscription_date)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		whp_sites_inscription_dateImpl whp_sites_inscription_dateImpl = new whp_sites_inscription_dateImpl();

		whp_sites_inscription_dateImpl.setWhp_sites_inscription_date_id(getWhp_sites_inscription_date_id());
		whp_sites_inscription_dateImpl.setSite_id(getSite_id());
		whp_sites_inscription_dateImpl.setInscription_type_id(getInscription_type_id());
		whp_sites_inscription_dateImpl.setReference_no(getReference_no());
		whp_sites_inscription_dateImpl.setInscription_date(getInscription_date());

		whp_sites_inscription_dateImpl.resetOriginalValues();

		return whp_sites_inscription_dateImpl;
	}

	public int compareTo(whp_sites_inscription_date whp_sites_inscription_date) {
		long primaryKey = whp_sites_inscription_date.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		whp_sites_inscription_date whp_sites_inscription_date = null;

		try {
			whp_sites_inscription_date = (whp_sites_inscription_date)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = whp_sites_inscription_date.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		whp_sites_inscription_dateModelImpl whp_sites_inscription_dateModelImpl = this;

		whp_sites_inscription_dateModelImpl._originalInscription_type_id = whp_sites_inscription_dateModelImpl._inscription_type_id;

		whp_sites_inscription_dateModelImpl._setOriginalInscription_type_id = false;

		whp_sites_inscription_dateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<whp_sites_inscription_date> toCacheModel() {
		whp_sites_inscription_dateCacheModel whp_sites_inscription_dateCacheModel =
			new whp_sites_inscription_dateCacheModel();

		whp_sites_inscription_dateCacheModel.whp_sites_inscription_date_id = getWhp_sites_inscription_date_id();

		whp_sites_inscription_dateCacheModel.site_id = getSite_id();

		whp_sites_inscription_dateCacheModel.inscription_type_id = getInscription_type_id();

		whp_sites_inscription_dateCacheModel.reference_no = getReference_no();

		String reference_no = whp_sites_inscription_dateCacheModel.reference_no;

		if ((reference_no != null) && (reference_no.length() == 0)) {
			whp_sites_inscription_dateCacheModel.reference_no = null;
		}

		Date inscription_date = getInscription_date();

		if (inscription_date != null) {
			whp_sites_inscription_dateCacheModel.inscription_date = inscription_date.getTime();
		}
		else {
			whp_sites_inscription_dateCacheModel.inscription_date = Long.MIN_VALUE;
		}

		return whp_sites_inscription_dateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{whp_sites_inscription_date_id=");
		sb.append(getWhp_sites_inscription_date_id());
		sb.append(", site_id=");
		sb.append(getSite_id());
		sb.append(", inscription_type_id=");
		sb.append(getInscription_type_id());
		sb.append(", reference_no=");
		sb.append(getReference_no());
		sb.append(", inscription_date=");
		sb.append(getInscription_date());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.iucn.whp.dbservice.model.whp_sites_inscription_date");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>whp_sites_inscription_date_id</column-name><column-value><![CDATA[");
		sb.append(getWhp_sites_inscription_date_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>site_id</column-name><column-value><![CDATA[");
		sb.append(getSite_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inscription_type_id</column-name><column-value><![CDATA[");
		sb.append(getInscription_type_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>reference_no</column-name><column-value><![CDATA[");
		sb.append(getReference_no());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inscription_date</column-name><column-value><![CDATA[");
		sb.append(getInscription_date());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = whp_sites_inscription_date.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			whp_sites_inscription_date.class
		};
	private long _whp_sites_inscription_date_id;
	private long _site_id;
	private int _inscription_type_id;
	private int _originalInscription_type_id;
	private boolean _setOriginalInscription_type_id;
	private String _reference_no;
	private Date _inscription_date;
	private long _columnBitmask;
	private whp_sites_inscription_date _escapedModelProxy;
}